# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/rishi',
                'doc_host': 'https://vedicreader.github.io',
                'git_url': 'https://github.com/vedicreader/rishi',
                'lib_path': 'rishi'},
  'syms': { 'rishi.core': { 'rishi.core.Chat': ('core.html#chat', 'rishi/core.py'),
                            'rishi.core.Chat.__init__': ('core.html#chat.__init__', 'rishi/core.py'),
                            'rishi.core.get_model': ('core.html#get_model', 'rishi/core.py')}}}
