"""One `Chat` for both backends. Name a model, and rishi works out whether it needs litert or llama.cpp - the way [fastllm](https://github.com/AnswerDotAI/fastllm) picks a vendor from the model name.

Docs: https://vedicreader.github.io/rishi/auto.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_auto.ipynb.

# %% auto #0
__all__ = ['backends', 'dflt_backend', 'split_backend', 'infer_backend', 'resolve_backend', 'get_backend', 'Chat', 'AsyncChat']

# %% ../nbs/03_auto.ipynb #c6905953
import asyncio
from importlib import import_module
from fastcore.all import Path, GetAttr

# %% ../nbs/03_auto.ipynb #dc3d5c26
backends = {'litert': 'rishi.litert', 'llama': 'rishi.llama'}
dflt_backend = 'litert'

_pats = {'litert': ('.litertlm', 'litertlm', 'litert-community', 'litert-lm'), 'llama': ('.gguf', 'gguf')}

def split_backend(model):
    "Split `'backend/model'` into `(backend, model)`; the prefix must name a known backend, else `(None, model)`."
    if isinstance(model, str) and '/' in model:
        b, m = model.split('/', 1)
        if b in backends: return b, m
    return None, model

def infer_backend(model):
    "Guess a backend from the shape of a model id or path (`.litertlm` vs `.gguf`), else `None`."
    s = str(model or '').lower()
    if not s: return None
    return next((b for b, ps in _pats.items() if any(p in s for p in ps)), None)

def resolve_backend(model=None, backend=None, model_path=None):
    "Resolve `(backend, model)` from an explicit `backend`, a `backend/` prefix, or the id/path shape."
    pre, model = split_backend(model)
    nm = backend or pre or infer_backend(model) or infer_backend(model_path)
    if nm is None and model is None and model_path is None: nm = dflt_backend
    if nm is None: raise ValueError(
        f"Can't tell which backend {model!r} needs. Pass backend='litert'|'llama', prefix the name "
        f"(e.g. 'llama/{model}'), or give a full repo id or path (.litertlm / .gguf).")
    if nm not in backends: raise ValueError(f"Unknown backend {nm!r}; known backends: {', '.join(backends)}.")
    return nm, model

def get_backend(nm):
    "Import the backend module for `nm`, with an actionable error when its dependencies are missing."
    try: return import_module(backends[nm])
    except ImportError as e:
        extra = " Install it with: pip install 'rishi[llama]'" if nm == 'llama' else ''
        raise ImportError(f"The {nm!r} backend is unavailable ({e}).{extra}") from None

# %% ../nbs/03_auto.ipynb #27cb68d1
def _is_path(model):
    "Does `model` name a local file rather than a hub repo id?"
    return bool(model) and (str(model).lower().endswith(('.gguf', '.litertlm')) or Path(model).exists())

def Chat(model=None, backend=None, **kw):
    "A `Chat` on whichever backend `model` implies; `**kw` passes through to that backend untouched."
    nm, model = resolve_backend(model, backend, kw.get('model_path'))
    if model is not None: kw.setdefault('model_path' if _is_path(model) else 'model_id', model)
    return get_backend(nm).Chat(**kw)

class AsyncChat(GetAttr):
    "Async twin of `Chat` for either backend; blocking calls run in a worker thread."
    _default = 'chat'
    def __init__(self, model=None, backend=None, **kw):
        self.chat = model if hasattr(model, '_send') else Chat(model, backend, **kw)
    async def __call__(self, msg=None, stream=False, max_output_tokens=None,
                       cbs=None # extra callbacks for this turn only
    ):
        'Run one chat turn; `await` the result (an async chunk generator when `stream=True`).'
        if stream: return self._astream(msg, max_output_tokens, cbs)
        return await asyncio.to_thread(self.chat, msg, False, max_output_tokens, cbs)
    async def _astream(self, msg, max_output_tokens=None, cbs=None):
        g = self.chat(msg, stream=True, max_output_tokens=max_output_tokens, cbs=cbs)
        done = object()
        while (o := await asyncio.to_thread(next, g, done)) is not done: yield o
    def close(self): self.chat.close()
    async def __aenter__(self): return self
    async def __aexit__(self, *exc): self.close()
