"""Claude Code's models through the Agent SDK or the `claude` CLI - an agent with its own harness, not a completion endpoint.

Docs: https://vedicreader.github.io/rishi/claude.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_claude.ipynb.

# %% auto #0
__all__ = ['CLAUDE_BIN', 'opus5', 'opus48', 'sonnet5', 'sonnet46', 'haiku45', 'fable5', 'CLAUDE_MODELS', 'CLAUDE_DISALLOWED',
           'CLAUDE_BUILTINS', 'NO_MCP', 'claude_bin', 'sdk_available', 'claude_via', 'norm_claude_usage', 'norm_claude',
           'ClaudeChat', 'UsageStats', 'ChatCallback', 'run_cbs', 'resp_text', 'thought', 'Resp', 'StreamFormatter',
           'display_stream', 'truncated', 'hitl_policy', 'extract_fence', 'mk_toolspec', 'ToolCall']

# %% ../nbs/06_claude.ipynb #cl_imports
import json, shutil, subprocess
from fastcore.all import Path, store_attr, patch, ifnone
from . import core
from .core import *

# %% ../nbs/06_claude.ipynb #cl_reexport
_all_ = ['UsageStats', 'ChatCallback', 'run_cbs', 'resp_text', 'thought', 'Resp', 'StreamFormatter',
         'display_stream', 'truncated', 'hitl_policy', 'extract_fence', 'mk_toolspec', 'ToolCall']

# %% ../nbs/06_claude.ipynb #cl_wire
CLAUDE_BIN = 'claude'   #: the CLI rishi drives; override per chat with `bin=`

# Claude Code's own aliases resolve to the latest build of each; the dated ids work too.
opus5    = 'claude-opus-5'
opus48   = 'claude-opus-4-8'
sonnet5  = 'claude-sonnet-5'
sonnet46 = 'claude-sonnet-4-6'
haiku45  = 'claude-haiku-4-5'
fable5   = 'claude-fable-5'

#: Every id above, for anything that wants to offer the list rather than reach for one of them.
CLAUDE_MODELS = {'opus5': opus5, 'opus48': opus48, 'sonnet5': sonnet5, 'sonnet46': sonnet46,
                 'haiku45': haiku45, 'fable5': fable5}

#: Claude Code's own tools this backend refuses by default. The agent gets its tools from the caller;
#: letting the harness shell out as well is a second, ungoverned way to touch the machine.
CLAUDE_DISALLOWED = ('Bash', 'Write', 'Edit', 'NotebookEdit')

#: Claude Code's own toolset, and why the default is none of it. Your tools reach the model as
#: tags in the system prompt; the harness's reach it as a real tool-use API. Offered both, a model
#: takes the real channel, is told your tool does not exist there, and reports it as broken without
#: ever emitting a tag - 1 call in 10 with the harness's toolset, 19 in 19 without it, across
#: haiku/sonnet/opus and both paths. `()` is `--tools ''`: nothing built in, so a tag is the only
#: way to act. `None` restores the default toolset, and with it the failure.
CLAUDE_BUILTINS = ()

#: Declared on every turn, and deliberately empty. A managed configuration forbids *adding* a
#: dynamic MCP server, so this backend adds none - and it must not reach for `--strict-mcp-config`
#: to say so, because that flag is itself refused when an enterprise config is present ("You cannot
#: use --strict-mcp-config when an enterprise MCP config is present"). Declaring nothing and
#: claiming nothing is the only shape a managed machine accepts.
NO_MCP = '{"mcpServers":{}}'

def claude_bin(bin=CLAUDE_BIN):
    "Absolute path to the `claude` binary, or a `FileNotFoundError` that says how to get one."
    if (p := shutil.which(bin)): return p
    raise FileNotFoundError(
        f'{bin!r} is not on $PATH. Install Claude Code (https://claude.com/claude-code) and run '
        f'`{bin} /login`; rishi drives it as a subprocess and never reads your credentials.')

def sdk_available():
    "Is the Claude Agent SDK importable here?"
    try:
        from claude_agent_sdk import query  # noqa: F401
        return True
    except ImportError: return False

def claude_via(via=None):
    "Which path to take: what you named, else the SDK when it is installed, else the CLI."
    if via not in (None, 'sdk', 'cli'): raise ValueError(f"via must be 'sdk', 'cli' or None, not {via!r}")
    if via == 'sdk' and not sdk_available(): raise ImportError(
        'via=\'sdk\' needs the Claude Agent SDK: pip install \'rishi[claude]\'. The CLI path needs '
        'none of it - leave via=None and rishi takes whichever is here.')
    return via or ('sdk' if sdk_available() else 'cli')

def norm_claude_usage(u, model=None):
    "Claude Code's usage block -> rishi's, so a Claude turn adds up with a local one."
    if not u: return {}
    cache = (u.get('cache_read_input_tokens') or 0) + (u.get('cache_creation_input_tokens') or 0)
    pt, ct = (u.get('input_tokens') or 0) + cache, u.get('output_tokens') or 0
    return {'prompt_tokens': pt, 'completion_tokens': ct, 'total_tokens': pt + ct,
            'cached_tokens': u.get('cache_read_input_tokens') or 0, 'model': model}

def norm_claude(d, model=None):
    "A Claude Code result -> a rishi `Resp`, with `<tool_call>` tags read out of the text."
    if d.get('is_error'): raise RuntimeError(f"claude failed: {d.get('result') or d.get('subtype')}")
    text, th = split_think(d.get('result') or '')
    text, tcs = parse_tool_tags(text)
    res = {'role': 'assistant', 'content': text}
    if th: res['channels'] = {'thought': th}
    if tcs: res['tool_calls'] = tcs
    res['usage'] = norm_claude_usage(d.get('usage'), model)
    return Resp(res)

# %% ../nbs/06_claude.ipynb #cl_chat
class ClaudeChat(ToolLoopMixin, Chat):
    "Chat against a Claude Code model - the same `rishi.core.Chat` API, over the Agent SDK or the CLI."
    _runtime = 'claude'
    _dflt_cbs = [UsageCallback, ToolReminderCallback, SlidingWindowCallback]
    mk_content, mk_msg, mk_msgs = staticmethod(mk_oai_content), staticmethod(mk_oai_msg), staticmethod(mk_oai_msgs)
    local = False   #: the binary is local, the model is not

    def __init__(self, model=None, *, runtime=None, model_path=None, sp='', messages=None, tools=None,
                 ctx_limit=None, approve=None, tool_max_len=None, max_steps=10, parallel_tools=False,
                 max_parallel_tools=None, final_prompt=dflt_final_prompt_,
                 permission_mode='auto',    # Claude Code's gate on its *own* tools; yours are rishi's
                 claude_builtins=CLAUDE_BUILTINS,   # the harness's own toolset; () -> none, None -> its default
                 claude_tools=None,         # of what `claude_builtins` leaves, what it may use; None -> all
                 claude_disallowed=CLAUDE_DISALLOWED,   # ...and the ones it may never use
                 workspace=None,            # directory Claude Code works in; None -> the cwd
                 effort=None,               # 'low'/'medium'/'high'/'xhigh'/'max'; None -> the default
                 via=None,                  # 'sdk' or 'cli'; None -> the SDK when it is installed
                 bin=CLAUDE_BIN, timeout=600, settings=None, cbs=None, default_cbs=True, **opts):
        self.model_id = core.split_runtime(model)[1] or opus5
        self._set_tools(tools)
        store_attr('permission_mode,claude_builtins,claude_tools,claude_disallowed,workspace,effort,bin,timeout,settings,opts')
        self.via = claude_via(via)
        self.ctx_limit, self._ctx_tokens = ctx_limit, 0
        self._setup(model=model, sp=sp, messages=messages, tools=tools, approve=approve,
                    tool_max_len=tool_max_len, max_steps=max_steps, parallel_tools=parallel_tools,
                    max_parallel_tools=max_parallel_tools, final_prompt=final_prompt, cbs=cbs,
                    default_cbs=default_cbs)

    @property
    def use_sdk(self):
        "Is this chat going through the Agent SDK rather than the CLI?"
        return self.via == 'sdk'

    @property
    def token_count(self):
        "the prompt this chat would send next. claude code doesn't give you usage. we estimate"
        return est_tokens(self._prompt()) + est_tokens(self._sp())

    def _sp(self):
        "The briefing plus the tool schemas, for the one channel a managed MCP policy cannot close."
        return tag_tools_sp(self.toolspecs, self.sp)

    def _prompt(self):
        "This turn's whole conversation as text. The briefing is not in here - it has its own channel."
        return render_prompt(self.hist)

    def _note_usage(self, r):
        "Remember what the turn cost. This is billing volume, not occupancy -- see `token_count`."
        self._ctx_tokens = (r.get('usage') or {}).get('total_tokens') or self._ctx_tokens
        return r

    def _recreate_conv(self):
        "rishi's history moved - eviction, `reconfigure`. Nothing to invalidate: every turn re-sends it."
        pass

    def close(self):
        "Nothing to release: a turn is a process or a `query`, and neither outlives it."
        pass

# %% ../nbs/06_claude.ipynb #cl_cli
@patch
def _cmd(self:ClaudeChat, fmt):
    "The `claude` command line for one turn, minus the prompt."
    cmd = [claude_bin(self.bin), '-p', '--output-format', fmt, '--model', self.model_id,
           '--mcp-config', NO_MCP]   # no `--strict-mcp-config`: see `NO_MCP`
    if (sp := self._sp()): cmd += ['--system-prompt', sp]
    if self.permission_mode: cmd += ['--permission-mode', self.permission_mode]
    if self.effort: cmd += ['--effort', self.effort]
    if self.settings: cmd += ['--settings', str(self.settings)]
    if self.workspace: cmd += ['--add-dir', str(self.workspace)]
    # `['']` rather than nothing: `--tools` is variadic, and the empty name is how it is told
    # to offer no built-in tools at all. An empty allowlist is `claude_builtins=()`, not this.
    if self.claude_builtins is not None: cmd += ['--tools', *(self.claude_builtins or [''])]
    if self.claude_tools: cmd += ['--allowed-tools', *self.claude_tools]
    if self.claude_disallowed: cmd += ['--disallowed-tools', *self.claude_disallowed]
    return cmd

@patch
def _run(self:ClaudeChat, fmt, prompt=None):
    """Run one turn and return the finished process; a non-zero exit is the CLI's message, not a traceback.

    The prompt goes in on stdin rather than as the trailing argument. Two reasons, and the first one
    is a bug this had: `--allowed-tools` and `--disallowed-tools` are variadic, so a trailing
    positional is read as one more tool name and the CLI then reports no prompt at all. The second is
    that a rendered conversation outgrows `ARG_MAX` long before it outgrows the context window.
    """
    r = subprocess.run(self._cmd(fmt), input=ifnone(prompt, self._prompt()), capture_output=True,
                       text=True, timeout=self.timeout, cwd=str(self.workspace) if self.workspace else None)
    if r.returncode != 0: raise RuntimeError(f'claude exited {r.returncode}: {(r.stderr or r.stdout).strip()[:400]}')
    return r

# %% ../nbs/06_claude.ipynb #cl_sdk
@patch
def _opts(self:ClaudeChat, sp):
    "Agent SDK options for one turn, with no MCP server for a managed policy to refuse."
    from claude_agent_sdk import ClaudeAgentOptions
    # no `max_turns`: it counts the *harness* turns and raises at the cap, and the loop that matters
    # is rishi's own. With no tools the harness can call, one answer is one turn anyway.
    kw = dict(model=self.model_id, system_prompt=sp or None,
              cwd=str(self.workspace) if self.workspace else None,
              permission_mode=self.permission_mode, settings=self.settings,
              mcp_servers={}, strict_mcp_config=False,   # see `NO_MCP`
              disallowed_tools=list(self.claude_disallowed or ()))
    if self.claude_builtins is not None: kw['tools'] = list(self.claude_builtins)
    if self.claude_tools: kw['allowed_tools'] = list(self.claude_tools)
    if self.effort: kw['effort'] = self.effort
    return ClaudeAgentOptions(**{**kw, **self.opts})

@patch
def _sdk_events(self:ClaudeChat, prompt, sp):
    "One `query` as `(kind, value)` pairs: `thought`, `text`, and one final `result` dict."
    from claude_agent_sdk import query, AssistantMessage, ResultMessage, TextBlock, ThinkingBlock
    async def _agen():
        text, res = [], None
        async for m in query(prompt=prompt, options=self._opts(sp)):
            if isinstance(m, AssistantMessage):
                for b in m.content:
                    if isinstance(b, ThinkingBlock) and b.thinking: yield 'thought', b.thinking
                    elif isinstance(b, TextBlock) and b.text: text.append(b.text); yield 'text', b.text
            elif isinstance(m, ResultMessage): res = m
        if res is None: raise RuntimeError('the Agent SDK ended without a result')
        # `res.result` is the final answer; the accumulated text is the fallback when it is empty
        yield 'result', {'result': res.result or ''.join(text), 'usage': res.usage,
                         'is_error': res.is_error, 'subtype': res.subtype}
    return sync_iter(_agen)

# %% ../nbs/06_claude.ipynb #cl_steps
@patch
def _model_step(self:ClaudeChat, max_output_tokens=None):
    "One wire call, through whichever path this chat uses."
    if self.use_sdk:
        out = next(v for k, v in self._sdk_events(self._prompt(), self._sp()) if k == 'result')
        return self._note_usage(norm_claude(out, self.model_id))
    return self._note_usage(norm_claude(json.loads(self._run('json').stdout), self.model_id))

@patch
def _stream_step(self:ClaudeChat, max_output_tokens=None):
    "The same turn, streamed: thinking on its own channel, and tag calls never rendered as prose."
    split, out = StreamSplit(), None
    if self.use_sdk:
        for kind, v in self._sdk_events(self._prompt(), self._sp()):
            if kind == 'thought': yield {'channels': {'thought': v}}
            elif kind == 'text': yield from split.feed(v)
            else: out = v
    else:
        proc = subprocess.Popen(self._cmd('stream-json') + ['--include-partial-messages'],
                                stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                                text=True, cwd=str(self.workspace) if self.workspace else None)
        with proc:
            proc.stdin.write(self._prompt()); proc.stdin.close()   # stdin, not argv - see `_run`
            for line in proc.stdout:
                if not (line := line.strip()): continue
                try: o = json.loads(line)
                except json.JSONDecodeError: continue
                if o.get('type') == 'assistant':
                    for b in (o.get('message') or {}).get('content') or []:
                        if b.get('type') == 'thinking' and (t := b.get('thinking')): yield {'channels': {'thought': t}}
                        elif (t := b.get('text')): yield from split.feed(t)
                elif o.get('type') == 'result': out = o
        if out is None: raise RuntimeError(f'claude ended without a result: {proc.stderr.read()[:400]}')
    yield from split.finish()
    self._step_res = self._note_usage(norm_claude(out, self.model_id))

@patch
def _oneshot(self:ClaudeChat, prompt, sp='', think=None, max_tokens=None):
    """Stateless one-shot text, through whichever path this chat uses.

    `think` and `max_tokens` have no switch on either path - Claude Code decides how much a model
    deliberates and how long it may answer for - so they are accepted and ignored rather than
    quietly changing the meaning of a cheap job.
    """
    if self.use_sdk:
        out = next(v for k, v in self._sdk_events(prompt, sp) if k == 'result')
        return resp_text(norm_claude(out, self.model_id))
    return resp_text(norm_claude(json.loads(self._run('json', prompt).stdout), self.model_id))
