"""Claude Code's models through the Agent SDK or the `claude` CLI. An agent with its own harness, not a completion endpoint.

Docs: https://vedicreader.github.io/rishi/claude.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_claude.ipynb.

# %% auto #0
__all__ = ['CLAUDE_BIN', 'opus5', 'opus48', 'sonnet5', 'sonnet46', 'haiku45', 'fable5', 'CLAUDE_MODELS', 'CLAUDE_DISALLOWED',
           'NO_MCP', 'ABORTED', 'INTERRUPT_WAIT', 'claude_bin', 'sdk_available', 'claude_via', 'norm_claude_usage',
           'norm_claude', 'mk_claude_content', 'mk_claude_msg', 'mk_claude_msgs', 'ClaudeChat', 'UsageStats',
           'ChatCallback', 'run_cbs', 'resp_text', 'thought', 'Resp', 'StreamFormatter', 'display_stream', 'truncated',
           'hitl_policy', 'extract_fence', 'mk_toolspec', 'ToolCall']

# %% ../nbs/06_claude.ipynb #cl_imports
import asyncio, json, os, shutil, subprocess, time
from base64 import b64encode
from pathlib import Path
from fastcore.all import store_attr, patch, ifnone, listify
from fastcore.aio import run_sync, iter_sync
from . import core
from .core import *

# %% ../nbs/06_claude.ipynb #cl_reexport
_all_ = ['UsageStats', 'ChatCallback', 'run_cbs', 'resp_text', 'thought', 'Resp', 'StreamFormatter',
         'display_stream', 'truncated', 'hitl_policy', 'extract_fence', 'mk_toolspec', 'ToolCall']

# %% ../nbs/06_claude.ipynb #cl_wire
CLAUDE_BIN = 'claude'   #: the CLI rishi drives, overridden per chat with `bin=`
opus5    = 'claude-opus-5'
opus48   = 'claude-opus-4-8'
sonnet5  = 'claude-sonnet-5'
sonnet46 = 'claude-sonnet-4-6'
haiku45  = 'claude-haiku-4-5'
fable5   = 'claude-fable-5'

#: Every id above, for anything that wants to offer the list rather than reach for one of them.
CLAUDE_MODELS = {'opus5': opus5, 'opus48': opus48, 'sonnet5': sonnet5, 'sonnet46': sonnet46,
                 'haiku45': haiku45, 'fable5': fable5}
CLAUDE_DISALLOWED = ('Bash', 'Write', 'Edit', 'NotebookEdit')
NO_MCP = '{"mcpServers":{}}'

def claude_bin(bin=CLAUDE_BIN):
    "Absolute path to the `claude` binary, or a `FileNotFoundError` that says how to get one."
    if (p := shutil.which(bin)): return p
    raise FileNotFoundError(
        f'{bin!r} is not on $PATH. Install Claude Code (https://claude.com/claude-code) and run '
        f'`{bin} /login`. rishi drives it as a subprocess and never reads your credentials.')

def sdk_available():
    "Is the Claude Agent SDK importable here?"
    try:
        from claude_agent_sdk import query  # noqa: F401
        return True
    except ImportError: return False

def claude_via(via=None):
    "Which path to take: what you named, else the SDK when it is installed, else the CLI."
    if via not in (None, 'sdk', 'cli'): raise ValueError(f"via must be 'sdk', 'cli' or None, not {via!r}")
    if via == 'sdk' and not sdk_available(): raise ImportError(
        'via=\'sdk\' needs the Claude Agent SDK: pip install \'rishi[claude]\'. The CLI path needs '
        'none of it. Leave via=None and rishi takes whichever is here.')
    return via or ('sdk' if sdk_available() else 'cli')

def norm_claude_usage(u, model=None):
    "Claude Code's usage block -> rishi's, so a Claude turn adds up with a local one."
    if not u: return {}
    cache = (u.get('cache_read_input_tokens') or 0) + (u.get('cache_creation_input_tokens') or 0)
    pt, ct = (u.get('input_tokens') or 0) + cache, u.get('output_tokens') or 0
    return {'prompt_tokens': pt, 'completion_tokens': ct, 'total_tokens': pt + ct,
            'cached_tokens': u.get('cache_read_input_tokens') or 0, 'model': model}

ABORTED = ('aborted_streaming', 'aborted')
def norm_claude(d, model=None):
    "A Claude Code result -> a rishi `Resp`, with `<tool_call>` tags read out of the text."
    if d.get('is_error') and d.get('terminal_reason') not in ABORTED:
        raise RuntimeError(f"claude failed: {d.get('result') or d.get('subtype')}")
    text, th = split_think(d.get('result') or '')
    text, tcs = parse_tool_tags(text)
    res = {'role': 'assistant', 'content': text}
    if th: res['channels'] = {'thought': th}
    if tcs: res['tool_calls'] = tcs
    res['usage'] = norm_claude_usage(d.get('usage'), model)
    return Resp(res)
INTERRUPT_WAIT = 5

# %% ../nbs/06_claude.ipynb #0b45f039
def mk_claude_content(o):
    """`mk_oai_content`, plus the documents Claude Code takes and OpenAI content has no part for.

    A PDF rides in the same `image_url` envelope the other media use. That envelope is rishi's
    internal shape for "a data URL in the history"; the mime inside it is what `_to_parts` reads to
    choose between an Anthropic `image` block and a `document` one.
    """
    if isinstance(o, (dict, str)): return mk_oai_content(o)
    b = Path(o).read_bytes() if isinstance(o, os.PathLike) else o
    if isinstance(b, bytes):
        mime = core.detect_mime(b) or ''
        if not mime.startswith(('image/', 'audio/')):
            return {'type': 'image_url',
                    'image_url': {'url': f'data:{mime or "application/octet-stream"};base64,{b64encode(b).decode()}'}}
    return mk_oai_content(o)

def mk_claude_msg(content, role='user'):
    "`mk_oai_msg` built out of `mk_claude_content`."
    if content is None or isinstance(content, dict): return content
    parts = [mk_claude_content(o) for o in content] if isinstance(content, list) else [mk_claude_content(content)]
    if all(p.get('type') == 'text' for p in parts): return {'role': role, 'content': '\n'.join(p['text'] for p in parts)}
    return {'role': role, 'content': parts}

def mk_claude_msgs(msgs): return [mk_claude_msg(m) for m in listify(msgs)] if msgs else []


# %% ../nbs/06_claude.ipynb #cl_chat
class ClaudeChat(ToolLoopMixin, Chat):
    "Chat against a Claude Code model, with the same `rishi.core.Chat` API over the Agent SDK or the CLI."
    _runtime = 'claude'
    _media_note = ("this Claude Code chat cannot carry a picture or a document: only a live session can, "
                   "and this one renders the conversation to a text prompt. Use the default "
                   "`stateful=True` with the Agent SDK, or `rishi.remote`/`rishi.ollama`/`rishi.litert`.")
    _dflt_cbs = [UsageCallback, ToolReminderCallback, SlidingWindowCallback]
    mk_content, mk_msg, mk_msgs = staticmethod(mk_claude_content), staticmethod(mk_claude_msg), staticmethod(mk_claude_msgs)
    local, _ctx_live = False, 0

    def __init__(self, model=None, *, runtime=None, model_path=None, sp='', messages=None, tools=None,
                 ctx_limit=None, approve=None, tool_max_len=None, max_steps=10, parallel_tools=False,
                 max_parallel_tools=None, final_prompt=dflt_final_prompt_,
                 permission_mode='auto',    # Claude Code's gate on its *own* tools. Yours are rishi's
                 claude_tools=None,         # Claude Code's own tools, allowlisted. None -> none at all when this chat carries tools
                 claude_disallowed=CLAUDE_DISALLOWED,   # ...and the ones it may never use
                 workspace=None,            # directory Claude Code works in. None -> the cwd
                 effort=None,               # 'low'/'medium'/'high'/'xhigh'/'max'. None -> the default
                 bare=True,                 # answer as a model: no CLAUDE.md, skills, plugins or hooks. See `_cmd`
                 via=None,                  # 'sdk' or 'cli'. None -> the SDK when it is installed
                 stateful=True,             # keep one Claude Code session per chat. See `_connect`
                 bin=CLAUDE_BIN, timeout=600, settings=None, cbs=None, default_cbs=True, **opts):
        self.model_id = core.split_runtime(model)[1] or opus5
        self._set_tools(tools)
        store_attr('permission_mode,claude_tools,claude_disallowed,workspace,effort,bare,bin,timeout,settings,opts')
        self.via = claude_via(via)
        self.stateful = stateful
        self.client = self._last_res = None
        self._stale = False             # a cancelled turn leaves the transcript and `hist` disagreeing
        self._ctx_live = 0              # occupancy the session last reported. See `token_count`
        self._sent = 0                  # how much of `hist` the live session has seen
        self.ctx_limit, self._ctx_tokens = ctx_limit, 0
        self._setup(model=model, sp=sp, messages=messages, tools=tools, approve=approve,
                    tool_max_len=tool_max_len, max_steps=max_steps, parallel_tools=parallel_tools,
                    max_parallel_tools=max_parallel_tools, final_prompt=final_prompt, cbs=cbs,
                    default_cbs=default_cbs)

    @property
    def in_session_mode(self):
        "Does this chat drive one live session, rather than a fresh `query` per turn?"
        return self.use_sdk and self.stateful

    @property
    def _media_ok(self):
        "A live session carries pictures and documents as content blocks. A text prompt cannot."
        return self.in_session_mode

    @property
    def tool_channel(self):
        "Where this chat's tool schemas travel. Always the prompt, to get past a managed MCP policy."
        return 'tags'

    @property
    def use_sdk(self):
        "Is this chat going through the Agent SDK rather than the CLI?"
        return self.via == 'sdk'

    @property
    def token_count(self):
        """What the live session last reported holding, else an estimate of the prompt it would send.

        Never asks the session here. A status bar reads this on the UI thread every repaint, and a
        round-trip to the subprocess from there waits on the same loop the turn is using: the CLI
        froze mid-turn. `_session_turn` refreshes it on the loop instead, once per turn.
        """
        return self._ctx_live or est_tokens(self._prompt()) + est_tokens(self._sp())

    def _sp(self):
        "The briefing plus the tool schemas, for the one channel a managed MCP policy cannot close."
        return tag_tools_sp(self.toolspecs, self.sp)

    def _prompt(self):
        "This turn's whole conversation as text. The briefing has a channel of its own."
        return render_prompt(self.hist)

    def _note_usage(self, r):
        "Remember what the turn cost. This is billing volume, not occupancy. See `token_count`."
        self._ctx_tokens = (r.get('usage') or {}).get('total_tokens') or self._ctx_tokens
        return r

    @property
    def in_session(self):
        "Is a Claude Code session live for this chat? Safe on a half-built one: `__del__` reaches here."
        return getattr(self, 'client', None) is not None

    def _recreate_conv(self):
        "Drop the session, so the next turn opens a fresh one and replays `hist` into it."
        self._disconnect()

    def close(self):
        "End the session. A leaked chat would otherwise leak a `node` process; the loop is fastcore's."
        self._disconnect()

# %% ../nbs/06_claude.ipynb #cl_cli
@patch
def _cmd(self:ClaudeChat, fmt):
    "The `claude` command line for one turn, minus the prompt."
    cmd = [claude_bin(self.bin), '-p', '--output-format', fmt, '--model', self.model_id,
           '--mcp-config', NO_MCP]   # no `--strict-mcp-config`: see `NO_MCP`
    if fmt == 'stream-json': cmd += ['--verbose']   # `-p` refuses stream-json without it
    if self.bare: cmd += ['--safe-mode']
    if (sp := self._sp()): cmd += ['--system-prompt', sp]
    if self.permission_mode: cmd += ['--permission-mode', self.permission_mode]
    if self.effort: cmd += ['--effort', self.effort]
    if self.settings: cmd += ['--settings', str(self.settings)]
    if self.workspace: cmd += ['--add-dir', str(self.workspace)]
    if self.claude_tools: cmd += ['--allowed-tools', *self.claude_tools]
    elif self.toolspecs: cmd += ['--tools', '']
    if self.claude_disallowed: cmd += ['--disallowed-tools', *self.claude_disallowed]
    return cmd

@patch
def _run(self:ClaudeChat, fmt, prompt=None):
    "Run one turn and return the finished process. A non-zero exit is the CLI's message, not a traceback."
    r = subprocess.run(self._cmd(fmt), input=ifnone(prompt, self._prompt()), capture_output=True,
                       text=True, timeout=self.timeout, cwd=str(self.workspace) if self.workspace else None)
    if r.returncode != 0: raise RuntimeError(f'claude exited {r.returncode}: {(r.stderr or r.stdout).strip()[:400]}')
    return r

# %% ../nbs/06_claude.ipynb #cl_sdk
@patch
def _opts(self:ClaudeChat, sp):
    "Agent SDK options for one turn, with no MCP server for a managed policy to refuse."
    from claude_agent_sdk import ClaudeAgentOptions
    kw = dict(model=self.model_id, system_prompt=sp or None,
              cwd=str(self.workspace) if self.workspace else None,
              permission_mode=self.permission_mode, settings=self.settings,
              mcp_servers={}, strict_mcp_config=False,   # see `NO_MCP`
              include_partial_messages=True,             # token deltas, as `_cmd` already asks for
              disallowed_tools=list(self.claude_disallowed or ()))
    if self.claude_tools is not None: kw['allowed_tools'] = list(self.claude_tools)
    elif self.toolspecs: kw['tools'] = []   # rishi's tools are the only channel - see `_cmd`
    if self.effort: kw['effort'] = self.effort
    if self.bare: kw.update(setting_sources=[], skills=[])   # the SDK's `--safe-mode`; see `_cmd`
    return ClaudeAgentOptions(**{**kw, **self.opts})

@patch
def _sdk_events(self:ClaudeChat, prompt, sp):
    "One `query` as `(kind, value)` pairs: `thought`, `text`, and one final `result` dict."
    from claude_agent_sdk import query, AssistantMessage, ResultMessage, TextBlock, ThinkingBlock
    async def _agen():
        text, res = [], None
        ait = query(prompt=prompt, options=self._opts(sp)).__aiter__()
        while True:
            try: m = await asyncio.wait_for(ait.__anext__(), self.timeout)
            except StopAsyncIteration: break
            except asyncio.TimeoutError:
                raise TimeoutError(f'Claude Code sent nothing for {self.timeout}s') from None
            if isinstance(m, AssistantMessage):
                for b in m.content:
                    if isinstance(b, ThinkingBlock) and b.thinking: yield 'thought', b.thinking
                    elif isinstance(b, TextBlock) and b.text: text.append(b.text); yield 'text', b.text
            elif isinstance(m, ResultMessage): res = m
        if res is None: raise RuntimeError('the Agent SDK ended without a result')
        yield 'result', {'result': res.result or ''.join(text), 'usage': res.usage, 'is_error': res.is_error, 'subtype': res.subtype}
    return sync_iter(_agen, stop=self._cancel)

# %% ../nbs/06_claude.ipynb #95f0e8ec
@patch
def _connect(self:ClaudeChat):
    "The live session, opened on first use. `_sp()` is fixed here: the SDK has no way to change it later."
    if self.client is not None: return self.client
    from claude_agent_sdk import ClaudeSDKClient
    client = ClaudeSDKClient(options=self._opts(self._sp()))
    run_sync(asyncio.wait_for(client.connect(), self.timeout))
    self.client = client        # `_sent` belongs to `_disconnect`: resetting it here would
    return client               # undo the delta this turn just computed

@patch
def _disconnect(self:ClaudeChat):
    "End the session if there is one. The loop outlives it, ready for the next."
    c = getattr(self, 'client', None)
    self.client, self._sent, self._last_res, self._stale = None, 0, None, False
    if c is None: return
    try: run_sync(asyncio.wait_for(c.disconnect(), self.timeout))
    except Exception: pass          # a dead subprocess is already disconnected

@patch
def _delta(self:ClaudeChat):
    "The slice of `hist` the session has not been sent, as one rendered prompt."
    if self._sent < len(self.hist) and self.hist[self._sent] is self._last_res:
        self._sent += 1             # the session wrote this one; sending it back would echo it
    out = render_prompt(self.hist[self._sent:])
    self._sent = len(self.hist)
    return out

# %% ../nbs/06_claude.ipynb #d3ad2ce7
@patch
def cancel(self:ClaudeChat):
    "Stop the turn, and tell the session to stop generating rather than only stopping the reader."
    out = super(ClaudeChat, self).cancel()
    if self.in_session:
        try: run_sync(asyncio.wait_for(self.client.interrupt(), INTERRUPT_WAIT))
        except Exception: pass
        self._stale = True
    return out

@patch
def _ctx_usage(self:ClaudeChat):
    "What the live session says its window holds, or None."
    if not self.in_session: return None
    try: return run_sync(asyncio.wait_for(self.client.get_context_usage(), INTERRUPT_WAIT))
    except Exception: return None

# %% ../nbs/06_claude.ipynb #da4e0a44
@patch
def _to_parts(self:ClaudeChat, msgs):
    "rishi's OpenAI-shaped messages as aidialog `Part`s, media included."
    from aidialog.msg_parts import Text, InputImage, InputFile
    out = []
    for m in msgs:
        who = core._roles.get(m.get('role'), m.get('role', '?'))   # private, so not via the star import
        c = m.get('content')
        if isinstance(c, str):
            if c: out.append(Text(f'## {who}\n{c}'))
            continue
        for prt in (c or []):
            if not isinstance(prt, dict): continue
            t = prt.get('type')
            if t == 'text': out.append(Text(f'## {who}\n{prt.get("text","")}'))
            elif t == 'image_url':
                url = (prt.get('image_url') or {}).get('url', '')
                out.append(InputFile(url) if 'application/pdf' in url[:40] else InputImage(url))
            elif t == 'input_audio': raise TypeError(
                'Claude Code takes no audio input. Use `rishi.remote`, `rishi.ollama` or `rishi.litert`.')
    return out

@patch
def _delta(self:ClaudeChat):
    "What the session has not been sent: a rendered string, or Anthropic blocks when media is in it."
    if self._sent < len(self.hist) and self.hist[self._sent] is self._last_res:
        self._sent += 1             # the session wrote this one; sending it back would echo it
    new = self.hist[self._sent:]
    self._sent = len(self.hist)
    if not any(is_media(p) for m in new for p in (m.get('content') or []) if isinstance(p, dict)):
        return render_prompt(new)
    from aidialog.msg_parts import Msg
    from fastllm.anthropic import denorm_user
    return denorm_user(Msg(role='user', content=self._to_parts(new)))['content']

# %% ../nbs/06_claude.ipynb #26df6fe0
@patch
def _session_turn(self:ClaudeChat, prompt):
    "One turn on the live session, in `_sdk_events`' `(kind, value)` shape."
    from claude_agent_sdk import AssistantMessage, ResultMessage, TextBlock, ThinkingBlock
    client = self._connect()
    async def _agen():
        text, res = [], None
        if isinstance(prompt, str): await client.query(prompt)
        else:                                          # content blocks need the streaming-input shape
            async def _one():
                yield {'type': 'user', 'message': {'role': 'user', 'content': prompt},
                       'parent_tool_use_id': None, 'session_id': 'default'}
            await client.query(_one())
        ait = client.receive_response().__aiter__()
        while True:
            if self._cancel.is_set(): break
            try: m = await asyncio.wait_for(ait.__anext__(), self.timeout)
            except StopAsyncIteration: break
            except asyncio.TimeoutError:
                raise TimeoutError(f'Claude Code sent nothing for {self.timeout}s') from None
            if isinstance(m, AssistantMessage):
                for b in m.content:
                    if isinstance(b, ThinkingBlock) and b.thinking: yield 'thought', b.thinking
                    elif isinstance(b, TextBlock) and b.text: text.append(b.text); yield 'text', b.text
            elif isinstance(m, ResultMessage): res = m
        if res is None: raise RuntimeError('the Claude Code session ended without a result')
        # already on the loop, so this is a local await rather than a cross-thread wait
        try: self._ctx_live = (await client.get_context_usage() or {}).get('totalTokens') or self._ctx_live
        except Exception: pass
        yield 'result', {'result': res.result or ''.join(text), 'usage': res.usage,
                         'is_error': res.is_error, 'subtype': res.subtype}
    return iter_sync(_agen())

@patch
def _events(self:ClaudeChat):
    "This turn's events: the delta on a live session, else the whole conversation on a fresh query."
    if not self.in_session_mode: return self._sdk_events(self._prompt(), self._sp())
    if self._stale: self._disconnect()   # a cancelled turn: start again from what rishi holds
    self._connect()                      # before the delta, not after: connecting must not
    return self._session_events(self._delta())   # come between computing it and sending it

@patch
def _session_events(self:ClaudeChat, prompt):
    "`_session_turn`, with one reconnect if the session died before it said anything."
    started = False
    try:
        for o in self._session_turn(prompt): started = True; yield o
    except Exception:
        if started: raise
        self._disconnect(); self._connect()
        for o in self._session_turn(render_prompt(self.hist)): yield o
        self._sent = len(self.hist)

# %% ../nbs/06_claude.ipynb #cl_steps
@patch
def _model_step(self:ClaudeChat, max_output_tokens=None):
    "One wire call, through whichever path this chat uses."
    if self.use_sdk:
        out = next(v for k, v in self._events() if k == 'result')
        self._last_res = res = self._note_usage(norm_claude(out, self.model_id))
        return res
    return self._note_usage(norm_claude(json.loads(self._run('json').stdout), self.model_id))

@patch
def _stream_step(self:ClaudeChat, max_output_tokens=None):
    "The same turn, streamed. Thinking gets its own channel, and tag calls are never rendered as prose."
    split, out = StreamSplit(), None
    if self.use_sdk:
        for kind, v in self._events():
            if kind == 'thought': yield {'channels': {'thought': v}}
            elif kind == 'text': yield from split.feed(v)
            else: out = v
    else:
        proc = subprocess.Popen(self._cmd('stream-json') + ['--include-partial-messages'],
                                stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                                text=True, cwd=str(self.workspace) if self.workspace else None)
        # `with proc` waits for the CLI on the way out, without a timeout. A cancelled turn abandons
        # this generator, so kill the process rather than block the caller until it finishes alone.
        with killed_on_exit(proc):
            proc.stdin.write(self._prompt()); proc.stdin.close()   # stdin, not argv: see `_run`
            for line in proc.stdout:
                if not (line := line.strip()): continue
                try: o = json.loads(line)
                except json.JSONDecodeError: continue
                if o.get('type') == 'stream_event':
                    dl = (o.get('event') or {}).get('delta') or {}
                    if (t := dl.get('thinking')): yield {'channels': {'thought': t}}
                    elif (t := dl.get('text')): yield from split.feed(t)
                elif o.get('type') == 'result': out = o
        if out is None: raise RuntimeError(f'claude ended without a result: {proc.stderr.read()[:400]}')
    yield from split.finish()
    self._step_res = self._last_res = self._note_usage(norm_claude(out, self.model_id))

@patch
def _oneshot(self:ClaudeChat, prompt, sp='', think=None, max_tokens=None):
    "Stateless one-shot text, through whichever path this chat uses."
    if self.use_sdk:
        out = next(v for k, v in self._sdk_events(prompt, sp) if k == 'result')
        return resp_text(norm_claude(out, self.model_id))
    return resp_text(norm_claude(json.loads(self._run('json', prompt).stdout), self.model_id))
