"""GitHub Copilot models through the `Chat` API, using a Copilot subscription instead of a vendor key.

Docs: https://vedicreader.github.io/rishi/copilot.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_copilot.ipynb.

# %% auto #0
__all__ = ['COPILOT_API', 'COPILOT_TOKEN_URL', 'COPILOT_CLIENT_ID', 'EDITOR_VERSION', 'PLUGIN_VERSION', 'USER_AGENT',
           'INTEGRATION_ID', 'API_VERSION', 'COPILOT_ENVS', 'GITHUB_ENVS', 'OAUTH_ENVS', 'DEVICE_CODE_URL',
           'ACCESS_TOKEN_URL', 'copilot_default', 'copilot_hdrs', 'oauth_paths', 'find_oauth', 'read_oauth',
           'copilot_oauth', 'CopilotToken', 'copilot_exchange', 'CopilotAuth', 'copilot_catalog', 'copilot_models',
           'copilot_ctx', 'save_oauth', 'copilot_login', 'CopilotChat']

# %% ../nbs/07_copilot.ipynb #cp_imports
import json, os, time
import httpx
from dataclasses import dataclass, replace
from fastcore.all import L, Path, store_attr, first
import rishi.core
from urai import Chat, ChatOpts, ToolCall, display_stream, get_runtime, resolve_runtime, resp_text
from .remote import RemoteChat

# %% ../nbs/07_copilot.ipynb #cp_wire
#: Where Copilot listens when the token exchange names no endpoint of its own.
COPILOT_API = 'https://api.githubcopilot.com'
#: Trades a GitHub OAuth token for a short-lived Copilot one.
COPILOT_TOKEN_URL = 'https://api.github.com/copilot_internal/v2/token'
#: The OAuth app the editors sign in as, and the only client id GitHub mints Copilot tokens for.
COPILOT_CLIENT_ID = 'Iv1.b507a08c87ecfe98'

#: Which editor Copilot is told it is talking to. Rebind these to say otherwise.
EDITOR_VERSION = 'vscode/1.99.3'
PLUGIN_VERSION = 'copilot-chat/0.26.7'
USER_AGENT     = 'GitHubCopilotChat/0.26.7'
INTEGRATION_ID = 'vscode-chat'
API_VERSION    = '2025-04-01'

def copilot_hdrs(auth=None, *, integration_id=INTEGRATION_ID, vision=False, initiator=None,
                 intent='conversation-panel'):
    "Headers Copilot wants on every request. `auth` is a whole `Authorization` value."
    h = {'editor-version': EDITOR_VERSION, 'editor-plugin-version': PLUGIN_VERSION,
         'user-agent': USER_AGENT, 'copilot-integration-id': integration_id,
         'x-github-api-version': API_VERSION}
    if intent: h['openai-intent'] = intent
    if auth: h['Authorization'] = auth
    if vision: h['copilot-vision-request'] = 'true'
    if initiator: h['x-initiator'] = initiator
    return h

# %% ../nbs/07_copilot.ipynb #cp_creds
COPILOT_ENVS = ('GITHUB_COPILOT_OAUTH_TOKEN', 'GH_COPILOT_TOKEN')
GITHUB_ENVS = ('GH_TOKEN', 'GITHUB_TOKEN')
OAUTH_ENVS = COPILOT_ENVS + GITHUB_ENVS   #: every variable read, though not all at the same moment

def oauth_paths():
    "Files a Copilot sign-in may have left a GitHub OAuth token in, best first."
    cfg = Path(os.getenv('XDG_CONFIG_HOME') or Path.home()/'.config')
    ps  = [cfg/'rishi'/'copilot.json'] + [cfg/'github-copilot'/f for f in ('apps.json', 'hosts.json')]
    if (la := os.getenv('LOCALAPPDATA')):
        ps += [Path(la)/'github-copilot'/f for f in ('apps.json', 'hosts.json')]
    return ps + [Path.home()/'.copilot'/'config.json']

def find_oauth(o, depth=0):
    "The `oauth_token` in a decoded config file, however deep the editor nested it."
    if depth > 4 or not isinstance(o, dict): return None
    if isinstance(t := o.get('oauth_token'), str) and t: return t
    return first(x for x in (find_oauth(v, depth+1) for v in o.values()) if x)

def read_oauth(p):
    "The GitHub OAuth token in config file `p`, or `None` if it has none or is not there."
    try: return find_oauth(json.loads(Path(p).read_text()))
    except Exception: return None

def _env_oauth(ks):
    "The first of environment variables `ks` that holds anything."
    return first(t for k in ks if (t := os.getenv(k)))

def copilot_oauth(token=None):
    "A GitHub OAuth token: what you passed, else `COPILOT_ENVS`, else an editor sign-in, else `GITHUB_ENVS`."
    if token: return token
    if (t := _env_oauth(COPILOT_ENVS)): return t
    for p in oauth_paths():
        if (t := read_oauth(p)): return t
    if (t := _env_oauth(GITHUB_ENVS)): return t
    raise RuntimeError(
        'No GitHub OAuth token for Copilot. Set one of ' + ', '.join(OAUTH_ENVS) + ', or sign in to '
        'Copilot in an editor, or run `from rishi.copilot import copilot_login; copilot_login()`.')

# %% ../nbs/07_copilot.ipynb #cp_token
@dataclass(frozen=True)
class CopilotToken:
    "One minted Copilot token: the bearer, the endpoint it is good for, and when it dies."
    key: str
    base_url: str = COPILOT_API
    expires_at: float = 0.      # unix seconds; 0 for a token rishi did not mint and cannot time

    def stale(self, skew=300):
        "Is it inside `skew` seconds of expiry? An untimed token is never stale."
        return bool(self.expires_at) and time.time() >= self.expires_at - skew

def copilot_exchange(oauth=None, *, url=COPILOT_TOKEN_URL, timeout=30):
    "Trade a GitHub OAuth token for a `CopilotToken`."
    r = httpx.get(url, timeout=timeout,
                  headers={**copilot_hdrs(f'token {copilot_oauth(oauth)}'), 'Accept': 'application/json'})
    if r.status_code in (401, 403, 404): raise PermissionError(
        f'GitHub refused the Copilot token exchange ({r.status_code}). That account needs an active '
        'Copilot subscription, and the OAuth token has to come from an app Copilot knows: an editor '
        'sign-in or `copilot_login()`, not a personal access token. A personal access token is what '
        'the 404 means: to an app Copilot does not know, the endpoint is not there at all.')
    r.raise_for_status()
    d = r.json()
    exp = float(d.get('expires_at') or 0)
    if exp > 1e11: exp /= 1000      # some responses count in milliseconds
    return CopilotToken(d['token'], (d.get('endpoints') or {}).get('api') or COPILOT_API, exp)

class CopilotAuth:
    "A Copilot token that re-mints itself. Share one and every chat holding it stays signed in."
    def __init__(self, oauth=None, *, key=None, base_url=None, skew=300):
        store_attr()
        self.tok = CopilotToken(key, base_url or COPILOT_API) if key else None

    def token(self, force=False):
        "The live token, minted when there is none and re-minted when it is nearly out of time."
        if self.key: return self.tok    # yours, and rishi has nothing to renew it with
        if force or self.tok is None or self.tok.stale(self.skew):
            t = copilot_exchange(self.oauth)
            self.tok = replace(t, base_url=self.base_url) if self.base_url else t
        return self.tok

    def __repr__(self):
        t = self.tok
        return f'CopilotAuth({"signed in" if t else "not yet"}, {t.base_url if t else COPILOT_API})'

def copilot_catalog(auth=None, timeout=30):
    "Every model this account can reach, as `{id: entry}` the way Copilot describes them."
    t = (auth or CopilotAuth()).token()
    r = httpx.get(f"{t.base_url.rstrip('/')}/models", headers=copilot_hdrs(f'Bearer {t.key}'), timeout=timeout)
    r.raise_for_status()
    return {m['id']: m for m in (r.json().get('data') or []) if m.get('id')}

def copilot_models(auth=None, timeout=30, kind='chat'):
    "Model ids this account can reach. Copilot is the authority, not a table in here. `kind=None` keeps the embedding and completion ones too."
    return [i for i, m in copilot_catalog(auth, timeout).items()
            if not kind or (m.get('capabilities') or {}).get('type') == kind]

def copilot_ctx(entry):
    "The prompt window Copilot reports for one catalogue entry, or `None` where it reports none."
    lim = ((entry or {}).get('capabilities') or {}).get('limits') or {}
    return lim.get('max_prompt_tokens') or lim.get('max_context_window_tokens') or None

# %% ../nbs/07_copilot.ipynb #cp_login
DEVICE_CODE_URL  = 'https://github.com/login/device/code'   #: GitHub's device flow
ACCESS_TOKEN_URL = 'https://github.com/login/oauth/access_token'

def save_oauth(token, path=None):
    "Write a GitHub OAuth token where `copilot_oauth` looks first, readable only by you."
    p = Path(path or oauth_paths()[0])
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps({'oauth_token': token}))
    p.chmod(0o600)
    return p

def copilot_login(client_id=COPILOT_CLIENT_ID, *, scope='read:user', save=True, printer=print, timeout=30):
    "Run GitHub's device flow: print a code, wait while you enter it, return the OAuth token."
    hdrs = {'Accept': 'application/json', 'User-Agent': USER_AGENT}
    d = httpx.post(DEVICE_CODE_URL, json={'client_id': client_id, 'scope': scope},
                   headers=hdrs, timeout=timeout).json()
    if not d.get('device_code'): raise RuntimeError(f'GitHub declined the device code request: {d}')
    printer(f"Open {d['verification_uri']} and enter {d['user_code']}")
    wait, deadline = float(d.get('interval') or 5), time.time() + float(d.get('expires_in') or 900)
    body = {'client_id': client_id, 'device_code': d['device_code'],
            'grant_type': 'urn:ietf:params:oauth:grant-type:device_code'}
    while time.time() < deadline:
        time.sleep(wait)
        r = httpx.post(ACCESS_TOKEN_URL, json=body, headers=hdrs, timeout=timeout).json()
        if (tok := r.get('access_token')):
            if save: printer(f'Saved to {save_oauth(tok)}')
            return tok
        if r.get('error') == 'slow_down': wait += float(r.get('interval') or 5)   # GitHub asks for a longer poll
        elif r.get('error') != 'authorization_pending':
            raise RuntimeError(f"device flow failed: {r.get('error_description') or r.get('error')}")
    raise TimeoutError('the device code expired before it was entered')

# %% ../nbs/07_copilot.ipynb #cp_chat
#: What `CopilotChat()` asks for when you name no model. `copilot_models()` is the authority on what
#: your account can reach, and that list moves faster than a constant in here could.
copilot_default = 'gpt-4.1'

class CopilotChat(RemoteChat):
    "Chat against a GitHub Copilot model: `RemoteChat` pointed at Copilot, with its headers and its half-hour token."
    _runtime = 'copilot'
    local = False   #: the subscription is yours, the machine is GitHub's

    def __init__(self, model=None, *,
                 oauth_token=None,   # a GitHub OAuth token, instead of the one on disk
                 auth=None,          # a `CopilotAuth` to share, instead of building one
                 integration_id=INTEGRATION_ID,
                 hdrs=None,          # extra headers, merged over Copilot's own
                 **kw):              # portable options; see `urai.ChatOpts`
        o = ChatOpts.create(kw.pop('opts', None), **kw)
        self.auth = auth or CopilotAuth(oauth_token, key=o.key, base_url=o.base_url or None)
        self.integration_id, self.hdrs = integration_id, dict(hdrs or {})
        super().__init__(model or copilot_default, opts=o)

    def _has_media(self):
        "Does the history carry an image or audio part? Copilot gates those behind a header."
        return any(isinstance(p, dict) and p.get('type') in ('image_url', 'input_audio')
                   for m in self.hist for p in L(m.get('content')))

    def _initiator(self):
        "`user` for a turn a person opened, `agent` once the model is round-tripping its own tool calls."
        return 'agent' if any(m.get('role') in ('assistant', 'tool') for m in self.hist) else 'user'

    def _kw(self, stream=False, **turn):
        "`RemoteChat._kw` plus Copilot's endpoint, a live token, and the headers it insists on."
        kw = super()._kw(stream, **turn)
        t  = self.auth.token()
        kw.update(api_key=t.key, base_url=t.base_url, vendor_name=None, api_name='openai_chat')
        kw['xtra_hdrs'] = {**copilot_hdrs(integration_id=self.integration_id, vision=self._has_media(),
                                          initiator=self._initiator()),
                           **(kw.get('xtra_hdrs') or {}), **self.hdrs}
        return kw
