"""litert model initialisation and tools

Docs: https://vedicreader.github.io/rishi/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['gemma4_e4b', 'gemma4_e2b', 'gemma4_12b', 'mk_content', 'mk_msg', 'mk_msgs', 'UsageStats', 'ChatCallback', 'run_cbs',
           'mk_tr_details', 'StreamFormatter', 'display_stream', 'ToolReminderCallback', 'ChatToolHandler', 'get_model',
           'Chat']

# %% ../nbs/00_core.ipynb #da4d26dd
import json, re
from html import escape
from mimetypes import guess_type
from litert_lm import (Engine, Backend, Conversation, Session, Message, Contents,
                       Content, Role, ToolCall, ToolEventHandler, set_min_log_severity)
from litert_lm._messages import (Text, ImageBytes, ImageFile, AudioBytes, AudioFile,
                                 ToolResponse, normalize_message)
from huggingface_hub import hf_hub_download, list_repo_files
from fastcore.all import Path, store_attr, patch, L, GetAttr, ifnone
from safepyrun import RunPython

# %% ../nbs/00_core.ipynb #6e295c9a
def mk_content(o):
    "Convert `o` to a litert `Content`."
    if isinstance(o, Content): return o
    if isinstance(o, str): return Text(o)
    if isinstance(o, bytes): return ImageBytes(o)
    if isinstance(o, Path):
        mime = guess_type(str(o))[0] or ''
        return AudioFile(str(o)) if mime.startswith('audio/') else ImageFile(str(o))
    raise TypeError(f"Unsupported content type: {type(o)}")

def mk_msg(content, role='user'):
    "Create a litert `Message` from str/bytes/list/dict/Message."
    if content is None: return None
    if isinstance(content, Message): return content
    if isinstance(content, dict): return Message(Role(content['role']), Contents.of(content['content']))
    parts = [mk_content(o) for o in content] if isinstance(content, list) else [mk_content(content)]
    return Message(Role(role), Contents(parts))

def mk_msgs(msgs):
    "Normalize a list of messages to litert message dicts."
    if not msgs: return []
    if not isinstance(msgs, list): msgs = [msgs]
    return [normalize_message(m if isinstance(m, (Message, dict)) else mk_msg(m)) for m in msgs]

# %% ../nbs/00_core.ipynb #142b81b8
class UsageStats:
    "Token usage for a chat turn, fed by `conv.token_count` diffs."
    def __init__(self, prompt_tokens=0, completion_tokens=0, total_tokens=0, n=0): store_attr()

    def __add__(self, other):
        if other is None: return self
        return UsageStats(*[getattr(self, k) + getattr(other, k)
            for k in ('prompt_tokens', 'completion_tokens', 'total_tokens', 'n')])
    def __radd__(self, other): return self if other in (None, 0) else self.__add__(other)

    def __repr__(self):
        return ' | '.join([f"total={self.total_tokens:,}", f"in={self.prompt_tokens:,}",
                           f"out={self.completion_tokens:,}", f"turns={self.n}"])

    def fmt(self):
        "Markdown `<details>` token block."
        if not self.total_tokens: return ''
        return f"\n\n<details><summary>{self.total_tokens:,} tokens</summary>\n\n`{self!r}`\n\n</details>\n"

# %% ../nbs/00_core.ipynb #99646223
class ChatCallback(GetAttr):
    "Base chat callback; reads chat state via `GetAttr` (`self.turn_msg` -> `chat.turn_msg`)."
    order, _default, chat, run = 0, 'chat', None, True
    def __repr__(self): return type(self).__name__

def run_cbs(chat, event):
    "Dispatch `event` to enabled callbacks in `order`; forward any yielded stream items."
    for cb in chat.cbs.sorted('order'):
        if cb.run and hasattr(cb, event):
            r = getattr(cb, event)()
            if r is not None: yield from r

# %% ../nbs/00_core.ipynb #e7d000a9
def _resp_text(resp):
    "Join text parts of a litert response/chunk dict."
    c = resp.get('content', []) if isinstance(resp, dict) else ''
    if isinstance(c, str): return c
    return ''.join(p.get('text', '') for p in c if isinstance(p, dict) and p.get('type') == 'text')

def _tc_summary(name, args, result=None):
    "One-line `<code>` summary of a tool call."
    params = ', '.join(f"{k}={v!r}" for k, v in (args or {}).items())
    res = f" -> {result}" if result is not None else ''
    return '<code>' + escape(f"{name}({params}){res}") + '</code>'

def mk_tr_details(name, args, result, mx=2000):
    "`<details>` JSON block for a completed tool call."
    body = json.dumps({'call': {'function': name, 'arguments': args}, 'result': str(result)[:mx]}, indent=2)
    return f"\n\n<details><summary>{_tc_summary(name, args, result)}</summary>\n\n```json\n{body}\n```\n\n</details>\n\n"

class StreamFormatter:
    "Format a litert response stream to markdown."
    def __init__(self, mx=2000): self.outp = ''; store_attr()
    def format_item(self, o):
        "Format one litert chunk dict."
        res = _resp_text(o)
        for p in (o.get('content', []) if isinstance(o, dict) else []):
            if isinstance(p, dict) and p.get('type') == 'tool_call':
                res += f"\n- ⏳ {_tc_summary(p.get('name', ''), p.get('arguments', {}))}\n"
        self.outp += res
        return res
    def format_stream(self, rs):
        "Yield markdown strings for each chunk."
        for o in rs: yield self.format_item(o)

def display_stream(rs, **kwargs):
    "Markdown-display a litert stream via IPython."
    from IPython.display import display, Markdown
    fmt, md = StreamFormatter(**kwargs), ''
    h = display(Markdown(' '), display_id=True)
    for o in fmt.format_stream(rs):
        md += o
        if md: h.update(Markdown(md))
    return fmt

# %% ../nbs/00_core.ipynb #172c44f0
_tool_reminder = ("\n<system-reminder>After every tool call result, briefly summarise in prose "
                  "what you found before continuing or calling another tool.</system-reminder>")

class ToolReminderCallback(ChatCallback):
    "Inject a tool-summary reminder into the outgoing message when tools are registered."
    order = 30
    def __init__(self, tool_reminder=_tool_reminder): store_attr()
    def before_send(self):
        if self.chat.tools and self.chat.turn_msg is not None:
            self.chat.turn_msg.contents.contents.append(Text(self.tool_reminder))

# %% ../nbs/00_core.ipynb #b8dfc247
class ChatToolHandler(ToolEventHandler):
    "Bridge litert's in-engine tool loop to Chat callbacks and history."
    def __init__(self, chat): self.chat = chat
    def approve_tool_call(self, tool_call):
        self.chat.turn_tc = tool_call
        self.chat.hist.append({'role': 'model', 'tool_calls': [tool_call]})
        for _ in run_cbs(self.chat, 'before_tool_calls'): pass
        return True
    def process_tool_response(self, tool_response):
        self.chat.turn_tool_result = tool_response
        name = self.chat.turn_tc.get('function', {}).get('name', '')
        self.chat.hist.append({'role': 'tool', 'content': [
            {'type': 'tool_response', 'name': name, 'response': tool_response}]})
        for _ in run_cbs(self.chat, 'after_tool_calls'): pass
        return tool_response

# %% ../nbs/00_core.ipynb #f717f851d413e77
gemma4_e4b='litert-community/gemma-4-E4B-it-litert-lm'
gemma4_e2b='litert-community/gemma-4-E2B-it-litert-lm'
gemma4_12b='litert-community/gemma-4-12B-it-litert-lm'

# %% ../nbs/00_core.ipynb #40fb869354982708
def get_model(model_id, model_path=None):
    "Return a local `.litertlm` path, downloading the model file from HF on first use."
    if model_path and Path(model_path).exists(): return model_path
    fn = next(f for f in list_repo_files(model_id) if f.endswith('.litertlm'))
    return hf_hub_download(model_id, fn)

_dflt_cbs = [ToolReminderCallback]

class Chat:
    "fastllm-style sync chat over a local litert_lm Gemma engine."
    def __init__(self, model_id=gemma4_e2b, model_path=None, backend=Backend.CPU, multimodal=True,
                 sp='', messages=None, tools=None, ctx_limit=4096, cbs=None, default_cbs=True, **kwargs):
        assert model_id or model_path, "model_id or model_path must be provided"
        mm = dict(vision_backend=backend, audio_backend=backend) if multimodal else {}
        self.engine = Engine(get_model(model_id, model_path), backend=backend, **mm)
        self.tools = L(tools)
        self.hist = mk_msgs(messages)
        preface = ([{'role': 'system', 'content': sp}] if sp else []) + self.hist
        self.conv = self.engine.create_conversation(messages=preface or None, tools=list(self.tools) or None,
            tool_event_handler=ChatToolHandler(self), automatic_tool_calling=True)
        store_attr('ctx_limit,sp')
        self.use, self.cbs, self.turn_msg, self.turn_res = UsageStats(), L(), None, None
        if default_cbs: self.add_cbs(_dflt_cbs)
        self.add_cbs(cbs)

    def add_cb(self, cb):
        "Register a callback (class or instance); binds `cb.chat`."
        if isinstance(cb, type): cb = cb()
        cb.chat = self; self.cbs.append(cb); return self
    def add_cbs(self, cbs):
        "Register multiple callbacks."
        L(cbs).map(self.add_cb); return self

    @property
    def token_count(self): return self.conv.token_count
    @property
    def pct_full(self): return self.conv.token_count / self.ctx_limit

    def _track(self, tc0):
        "Fold this turn's usage into `self.use` from a `token_count` diff."
        tc1 = self.conv.token_count
        out = len(self.engine.tokenize(_resp_text(self.turn_res)))
        self.use += UsageStats(prompt_tokens=max((tc1 - tc0) - out, 0), completion_tokens=out,
                               total_tokens=tc1 - tc0, n=1)

    def __call__(self, msg=None, stream=False, max_output_tokens=None):
        "Run one chat turn; returns the litert response dict (or a stream generator)."
        self.use, self.turn_msg = UsageStats(), mk_msg(msg)
        if self.turn_msg is not None: self.hist.append(normalize_message(self.turn_msg))
        for _ in run_cbs(self, 'after_msgs'): pass
        for _ in run_cbs(self, 'before_send'): pass
        if stream: return self._stream(max_output_tokens)
        tc0 = self.conv.token_count
        self.turn_res = self.conv.send_message(self.turn_msg, max_output_tokens=max_output_tokens)
        self._track(tc0); self.hist.append(self.turn_res)
        for _ in run_cbs(self, 'after_response'): pass
        return self.turn_res

    def print_hist(self):
        "Print each message on its own line."
        for m in self.hist: print(f"{m.get('role','?')}: {_resp_text(m) or m}")

# %% ../nbs/00_core.ipynb #4aadf302
def _merge_chunks(chunks):
    "Reconstruct an assistant response dict from streamed litert chunks."
    return {'role': 'assistant', 'content': [{'type': 'text', 'text': ''.join(_resp_text(c) for c in chunks)}]}

@patch
def _stream(self: Chat, max_output_tokens=None):
    "Yield markdown for a streaming turn, then track usage + history."
    tc0, fmt, chunks = self.conv.token_count, StreamFormatter(), []
    for o in self.conv.send_message_async(self.turn_msg, max_output_tokens=max_output_tokens):
        chunks.append(o); yield fmt.format_item(o)
    self.turn_res = _merge_chunks(chunks)
    self._track(tc0); self.hist.append(self.turn_res)
    for _ in run_cbs(self, 'after_response'): pass
