"""Registering Rishi's backends with Urai.

Docs: https://vedicreader.github.io/rishi/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['BACKENDS', 'mk_oai_content', 'mk_oai_msg', 'mk_oai_msgs', 'browser_approval', 'runtimes', 'litert_caps',
           'ollama_caps_', 'use_system_certs_', 'repo_root', 'mv_skill_md']

# %% ../nbs/00_core.ipynb #d122bb29
import ast, asyncio, inspect, warnings
from fastcore.all import Path, first
from urai import (Caps, Runtime, RUNTIMES, register_runtime, infer_runtime, resolve_runtime, resolve,
                  model_caps, cfg_caps, mmproj_caps, hosted_caps, is_path, use_system_certs,
                  mk_content, mk_msg, mk_msgs, http_approval)

# %% ../nbs/00_core.ipynb #ed11fe02
_all_ = ['BACKENDS', 'litert_caps', 'ollama_caps_', 'use_system_certs_', 'repo_root', 'mv_skill_md']

# %% ../nbs/00_core.ipynb #5f88136c
import safepyrun.core as _spc

async def _rishi_run_python(code, g=None, ok_dests=None):
    _spc._rp_globals.set(g)
    inject = {'__builtins__': _spc._builtins, '__name__': '<python>'}
    protect = list(inject) + list(_spc._noexport)   # host helpers must not be shadowed back into g
    saved = {k: g[k] for k in protect if k in g}; had = set(saved)
    g.update(inject)
    async def run(src, is_exec=True):
        comp = compile(src, _spc.srcfn(src), 'exec' if is_exec else 'eval',
                       flags=ast.PyCF_ALLOW_TOP_LEVEL_AWAIT)
        r = eval(comp, g)                          # one namespace: defs see top-level imports
        return (await r) if inspect.isawaitable(r) else r
    tree = ast.parse(code)
    warnings.filterwarnings('ignore', category=SyntaxWarning)
    res = None
    if tree.body and isinstance(tree.body[-1], ast.Expr):
        last = tree.body.pop()
        if tree.body: await run(ast.unparse(ast.Module(tree.body, [])))
        res = await run(ast.unparse(ast.Expression(last.value)), False)
    else: await run(code)
    for k in protect:                              # restore host names to their pre-run state
        if k in had: g[k] = saved[k]
        else: g.pop(k, None)
    return res

setattr(_spc, '__run_python', _rishi_run_python)

# %% ../nbs/00_core.ipynb #dc247d61
def litert_caps(model=None, model_path=None):
    "litert builds vision and audio backends whenever `multimodal` is on, so every model takes both."
    return Caps(('text', 'image', 'audio'), ('text',), (), 'runtime')

def ollama_caps_(model=None, model_path=None):
    "Ollama is the one runtime that can just be asked: the daemon holds the weights."
    try: from rishi.ollama import ollama_caps
    except ImportError: return None
    return ollama_caps(model)

# %% ../nbs/00_core.ipynb #b9763ec0
#: Every runtime rishi serves, in the order `infer_runtime` should try them.
BACKENDS = [
    Runtime('litert', 'rishi.litert.LitertChat', optional=True, caps=litert_caps,
            pats=('.litertlm', 'litertlm', 'litert-community', 'litert-lm')),
    Runtime('ollama', 'rishi.ollama.OllamaChat', optional=True, caps=ollama_caps_,
            pats=('hf.co/', 'huggingface.co/')),
    Runtime('llama',  'rishi.llama.LlamaChat',   optional=True, caps=mmproj_caps,
            pats=('.gguf', 'gguf')),
    Runtime('mlx',    'rishi.mlx.MlxChat',       optional=True, caps=cfg_caps,
            pats=('mlx-community', 'mlx_lm', '-mlx', 'mlx-')),
    Runtime('remote', 'rishi.remote.RemoteChat', local=False,
            pats=('claude-', 'gpt-', 'gemini-', 'kimi-', 'deepseek-', 'grok-',
                  'sonnet', 'opus', 'haiku', 'fable')),
    Runtime('claude',  'rishi.claude.ClaudeChat',  local=False),
    Runtime('copilot', 'rishi.copilot.CopilotChat', local=False),
]

for _rt in BACKENDS: register_runtime(_rt, dflt=_rt.name == 'litert')

# %% ../nbs/00_core.ipynb #8bae17e8
#: Compatibility aliases for names Rishi used before Urai.
mk_oai_content, mk_oai_msg, mk_oai_msgs = mk_content, mk_msg, mk_msgs
browser_approval = http_approval
runtimes = RUNTIMES
_is_path = is_path

def use_system_certs_(force=False):
    "Deprecated alias for `urai.use_system_certs`."
    return use_system_certs(force)

# %% ../nbs/00_core.ipynb #1086ffd6
def repo_root() -> Path:
    "Root of the current git repository, or None if not in one."
    return first((Path.cwd(), *Path.cwd().parents), lambda p: (p/'.git').exists())

def mv_skill_md(dry_run=True, dir=None):
    "Copy the bundled `skill.md` into the `.claude` and `.agents` skill directories."
    base = Path(__file__).parent if '__file__' in globals() else Path.cwd()
    if not (src := first((base/'skill.md', base.parent/'skill.md'), Path.exists)): return
    root = Path(dir or repo_root() or '.')
    ts = [root/'.agents/skills/rishi/SKILL.md', root/'.claude/skills/rishi/SKILL.md']
    if dry_run: print(f'Would copy {src} to: {list(map(str, ts))}')
    else:
        for p in ts: p.mk_write(src.read_text(encoding='utf-8'))
        print(f'Installed -> {list(map(str, ts))}')
