"""Cursor's models via the `cursor-agent` CLI or SDK — not a completion endpoint but an agent with its own prompt overhead (~16k input tokens/turn).

Docs: https://vedicreader.github.io/rishi/cursor.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_cursor.ipynb.

# %% auto #0
__all__ = ['CURSOR_BIN', 'cursor_default', 'grok45', 'composer25', 'opus5', 'opus48', 'opus47', 'opus46', 'opus45', 'fable5',
           'sonnet5', 'sonnet46', 'sonnet45', 'sonnet4', 'haiku45', 'gpt56_sol', 'gpt56_terra', 'gpt56_luna', 'gpt55',
           'gpt54', 'gpt54_mini', 'gpt54_nano', 'gpt53_codex', 'gpt52', 'gpt51', 'gpt5_mini', 'gemini36_flash',
           'gemini35_flash', 'gemini31_pro', 'gemini3_flash', 'gemini25_flash', 'kimi_k3', 'kimi_k27_code', 'glm52',
           'CURSOR_MODELS', 'cursor_bin', 'cursor_via', 'sdk_available', 'cursor_models', 'sdk_mode', 'cursor_model',
           'render_prompt', 'norm_cursor', 'norm_cursor_usage', 'CursorChat', 'UsageStats', 'ChatCallback', 'run_cbs',
           'resp_text', 'thought', 'Resp', 'StreamFormatter', 'display_stream', 'truncated', 'hitl_policy',
           'extract_fence', 'mk_toolspec', 'ToolCall']

# %% ../nbs/05_cursor.ipynb #cu_imports
import json, os, shutil, subprocess
from fastcore.all import Path, store_attr, patch, ifnone
from . import core
from .core import *

# %% ../nbs/05_cursor.ipynb #cu_reexport
_all_ = ['UsageStats', 'ChatCallback', 'run_cbs', 'resp_text', 'thought', 'Resp', 'StreamFormatter',
         'display_stream', 'truncated', 'hitl_policy', 'extract_fence', 'mk_toolspec', 'ToolCall']

# %% ../nbs/05_cursor.ipynb #cu_wire
CURSOR_BIN = 'cursor-agent'   #: the CLI rishi drives; override per chat with `bin=`

# Cursor's own ids, as the SDK reports them - and as the CLI accepts them too, though `cursor-agent
# models` lists decorated variants instead (`cursor-grok-4.5-high`, `-low-fast`) with the effort baked
# into the name. The SDK takes the effort as a model parameter, so the plain name is the one that
# works everywhere. `cursor_models()` reports what the active path lists, and is the authority.
cursor_default = 'default'
grok45         = 'grok-4.5'
composer25     = 'composer-2.5'
opus5          = 'claude-opus-5'
opus48         = 'claude-opus-4-8'
opus47         = 'claude-opus-4-7'
opus46         = 'claude-opus-4-6'
opus45         = 'claude-opus-4-5'
fable5         = 'claude-fable-5'
sonnet5        = 'claude-sonnet-5'
sonnet46       = 'claude-sonnet-4-6'
sonnet45       = 'claude-sonnet-4-5'
sonnet4        = 'claude-sonnet-4'
haiku45        = 'claude-haiku-4-5'
gpt56_sol      = 'gpt-5.6-sol'
gpt56_terra    = 'gpt-5.6-terra'
gpt56_luna     = 'gpt-5.6-luna'
gpt55          = 'gpt-5.5'
gpt54          = 'gpt-5.4'
gpt54_mini     = 'gpt-5.4-mini'
gpt54_nano     = 'gpt-5.4-nano'
gpt53_codex    = 'gpt-5.3-codex'
gpt52          = 'gpt-5.2'
gpt51          = 'gpt-5.1'
gpt5_mini      = 'gpt-5-mini'
gemini36_flash = 'gemini-3.6-flash'
gemini35_flash = 'gemini-3.5-flash'
gemini31_pro   = 'gemini-3.1-pro'
gemini3_flash  = 'gemini-3-flash'
gemini25_flash = 'gemini-2.5-flash'
kimi_k3        = 'kimi-k3'
kimi_k27_code  = 'kimi-k2.7-code'
glm52          = 'glm-5.2'

#: Every id above, for anything that wants to offer the list rather than reach for one of them.
CURSOR_MODELS = {'cursor_default': cursor_default, 'grok45': grok45, 'composer25': composer25,
                 'opus5': opus5, 'opus48': opus48, 'opus47': opus47, 'opus46': opus46, 'opus45': opus45,
                 'fable5': fable5, 'sonnet5': sonnet5, 'sonnet46': sonnet46, 'sonnet45': sonnet45,
                 'sonnet4': sonnet4, 'haiku45': haiku45, 'gpt56_sol': gpt56_sol, 'gpt56_terra': gpt56_terra,
                 'gpt56_luna': gpt56_luna, 'gpt55': gpt55, 'gpt54': gpt54, 'gpt54_mini': gpt54_mini,
                 'gpt54_nano': gpt54_nano, 'gpt53_codex': gpt53_codex, 'gpt52': gpt52, 'gpt51': gpt51,
                 'gpt5_mini': gpt5_mini, 'gemini36_flash': gemini36_flash, 'gemini35_flash': gemini35_flash,
                 'gemini31_pro': gemini31_pro, 'gemini3_flash': gemini3_flash, 'gemini25_flash': gemini25_flash,
                 'kimi_k3': kimi_k3, 'kimi_k27_code': kimi_k27_code, 'glm52': glm52}

def cursor_bin(bin=CURSOR_BIN):
    "Absolute path to the `cursor-agent` binary, or a `FileNotFoundError` that says how to get one."
    if (p := shutil.which(bin)): return p
    raise FileNotFoundError(
        f'{bin!r} is not on $PATH. Install the Cursor CLI (https://cursor.com/cli) and run '
        f'`{bin} login`; rishi drives it as a subprocess and never reads your credentials.')

def cursor_via(via=None, api_key=None):
    "Which path to take: what you named, else the SDK when there is a key and a package for it."
    if via not in (None, 'sdk', 'cli'): raise ValueError(f"via must be 'sdk', 'cli' or None, not {via!r}")
    return via or ('sdk' if sdk_available(api_key) else 'cli')

def sdk_available(api_key=None):
    "Can the Python SDK be used here - installed, with a key to use it with?"
    if not (api_key or os.getenv('CURSOR_API_KEY')): return False
    try:
        from cursor_sdk import Cursor # noqa: F401
        return True
    except ImportError: return False

def cursor_models(bin=CURSOR_BIN, api_key=None, via=None):
    """The model ids this account can actually reach; Cursor is the source of truth, not a table in here.

    Asked through whichever credential there is - `Cursor.models.list` when the SDK has a key, and
    `cursor-agent models` otherwise. The SDK path has no business shelling out to a CLI it does not
    otherwise need, and a machine with a key but no CLI installed is a perfectly ordinary machine.
    """
    if cursor_via(via, api_key) == 'sdk':
        from cursor_sdk import Cursor
        return [m.id for m in Cursor.models.list(api_key=api_key)]
    out = subprocess.run([cursor_bin(bin), 'models'], capture_output=True, text=True).stdout
    return [l.split(' - ')[0].strip() for l in out.splitlines() if ' - ' in l]

#: rishi asks for read-only by default, and the two paths spell that differently: the CLI has `ask`
#: (Q&A) and `plan`, the SDK has only `agent` and `plan`. `ask` therefore means `plan` to the SDK -
#: passing it through would serialize to an enum Cursor does not know and be ignored, which is the
#: worst of the three outcomes: a read-only request that quietly runs an agent that can write.
_sdk_modes = {'ask': 'plan', 'plan': 'plan', 'agent': 'agent'}

def sdk_mode(mode):
    "rishi's mode in the SDK's vocabulary, or a `ValueError` rather than a silently ignored one."
    if mode is None: return None
    if mode not in _sdk_modes: raise ValueError(f'unknown mode {mode!r}; use {", ".join(_sdk_modes)} or None')
    return _sdk_modes[mode]

def cursor_model(model, effort=None, fast=None, via='cli'):
    """A model id with its effort and speed attached, spelled the way the active path spells them.

    The SDK carries both as model *parameters* on a `ModelSelection`; the CLI takes the bracket form
    (`grok-4.5[effort=high,fast=true]`) it documents. Same two arguments either way, so a chat that
    moves between paths asks for the same thing rather than being rewritten.
    """
    if not effort and fast is None: return model
    vals = ([('effort', str(effort))] if effort else []) + ([('fast', str(bool(fast)).lower())] if fast is not None else [])
    if via != 'sdk': return f"{model}[{','.join(f'{k}={v}' for k, v in vals)}]"
    from cursor_sdk import ModelSelection, ModelParameterValue
    return ModelSelection(id=model, params=[ModelParameterValue(id=k, value=v) for k, v in vals])

_roles = {'user': 'User', 'assistant': 'Assistant', 'tool': 'Tool result', 'system': 'System'}

def render_prompt(hist, sp=''):
    "A conversation as the one block of text `cursor-agent` takes; `sp` leads, since there is no system channel."
    out = [sp] if sp else []
    for m in hist:
        if not (txt := resp_text(m)) and not m.get('tool_calls'): continue
        who = _roles.get(m.get('role'), m.get('role', '?'))
        if m.get('role') == 'tool': who = f"Tool result ({m.get('name', '?')})"
        calls = '\n'.join(f'<tool_call>\n{json.dumps({"name": tc_name(tc), "arguments": tc.get("function", {}).get("arguments") or {}})}\n</tool_call>'
                           for tc in (m.get('tool_calls') or []))
        out.append(f"## {who}\n{txt}{chr(10) + calls if calls else ''}")
    return '\n\n'.join(out)

def norm_cursor(d, model=None):
    "A `cursor-agent` JSON result -> a rishi `Resp`, with `<tool_call>` tags read out of the text."
    if d.get('is_error'): raise RuntimeError(f"cursor-agent failed: {d.get('result') or d.get('subtype')}")
    text, th = split_think(d.get('result') or '')
    text, tcs = parse_tool_tags(text)
    res = {'role': 'assistant', 'content': text}
    if th: res['channels'] = {'thought': th}
    if tcs: res['tool_calls'] = tcs
    res['usage'] = norm_cursor_usage(d.get('usage'), model)
    return Resp(res)

def norm_cursor_usage(u, model=None):
    "`cursor-agent`'s usage block -> rishi's, so a Cursor turn adds up with a local one."
    if not u: return {}
    pt, ct = u.get('inputTokens', 0), u.get('outputTokens', 0)
    return {'prompt_tokens': pt, 'completion_tokens': ct, 'total_tokens': pt + ct,
            'cached_tokens': u.get('cacheReadTokens', 0), 'model': model}

# %% ../nbs/05_cursor.ipynb #cu_chat
class CursorChat(ToolLoopMixin, Chat):
    "Chat against a Cursor CLI model - the same `rishi.core.Chat` API, driving `cursor-agent` headless."
    _runtime = 'cursor'
    _dflt_cbs = [UsageCallback, ToolReminderCallback, SlidingWindowCallback]
    mk_content, mk_msg, mk_msgs = staticmethod(mk_oai_content), staticmethod(mk_oai_msg), staticmethod(mk_oai_msgs)
    local = False   #: the binary is local, the model is not - see the note at the top of this page

    def __init__(self, model=None, *, runtime=None, model_path=None, sp='', messages=None, tools=None,
                 ctx_limit=None, approve=None, tool_max_len=None, max_steps=10, parallel_tools=False,
                 max_parallel_tools=None, final_prompt=dflt_final_prompt_,
                 mode='ask',          # 'ask' (read-only Q&A) or 'plan'; None lets cursor-agent edit and run things
                 sandbox='enabled',   # 'enabled'/'disabled'; None leaves the CLI's own config alone
                 trust=False,         # trust this workspace without prompting - the CLI refuses an untrusted one
                 workspace=None,      # directory cursor-agent works in; None -> the cwd
                 effort=None,         # 'low'/'medium'/'high'/'xhigh'/'max'; None -> the model's own default
                 fast=None,           # ask for the fast build of the model; None -> the model's own default
                 via=None,            # 'sdk' or 'cli'; None -> the SDK when there is a key and the package
                 api_key=None,        # SDK key; None -> $CURSOR_API_KEY. The CLI path needs none of this
                 cursor_tools=None,        # Cursor's *own* tools, allowlisted; None -> whatever `mode` allows
                 cursor_disallowed=('shell',),  # ...and the ones it may never use, whatever `mode` says
                 bin=CURSOR_BIN, timeout=600, cbs=None, default_cbs=True):
        self.model_id = core.split_runtime(model)[1] or grok45
        self._set_tools(tools)
        store_attr('mode,sandbox,trust,workspace,bin,timeout,api_key,cursor_tools,cursor_disallowed,effort,fast')
        self.via = cursor_via(via, api_key)
        self._agent, self._sent = None, 0
        self.ctx_limit, self._ctx_tokens = ctx_limit, 0
        self._setup(model=model, sp=sp, messages=messages, tools=tools, approve=approve,
                    tool_max_len=tool_max_len, max_steps=max_steps, parallel_tools=parallel_tools,
                    max_parallel_tools=max_parallel_tools, final_prompt=final_prompt, cbs=cbs, default_cbs=default_cbs)

    @property
    def use_sdk(self):
        "Is this chat going through the Python SDK rather than the CLI?"
        return self.via == 'sdk'

    @property
    def token_count(self):
        "Tokens the last turn reported; there is no live context read-out through the CLI."
        return self._ctx_tokens

    def _cmd(self, fmt):
        "The `cursor-agent` command line for one turn, minus the prompt."
        cmd = [cursor_bin(self.bin), '-p', '--output-format', fmt,
               '--model', cursor_model(self.model_id, self.effort, self.fast)]
        if self.mode: cmd += ['--mode', self.mode]
        if self.sandbox: cmd += ['--sandbox', self.sandbox]
        if self.trust: cmd += ['--trust']
        if self.workspace: cmd += ['--workspace', str(self.workspace)]
        return cmd

    def _prompt(self):
        "This turn's whole conversation as text, with the tool schemas in it when there are any."
        return render_prompt(self.hist, tag_tools_sp(self.toolspecs, self.sp))

    def _run(self, fmt, prompt=None):
        "Run one turn and return the finished process; a non-zero exit is the CLI's message, not a traceback."
        r = subprocess.run(self._cmd(fmt) + [ifnone(prompt, self._prompt())],
                           capture_output=True, text=True, timeout=self.timeout)
        if r.returncode != 0: raise RuntimeError(f'cursor-agent exited {r.returncode}: {(r.stderr or r.stdout).strip()[:400]}')
        return r

    def _note_usage(self, r):
        "Remember what the turn cost, since `token_count` is the only context read-out there is."
        self._ctx_tokens = (r.get('usage') or {}).get('total_tokens') or self._ctx_tokens
        return r

    def _recreate_conv(self):
        "rishi's history moved - eviction, `reconfigure` - so the live agent's memory of it is now wrong."
        self.close()

    def _model_step(self, max_output_tokens=None):
        "One wire call: through the live agent when there is one, else a whole conversation through the CLI."
        if self.use_sdk: return self._sdk_step(max_output_tokens)
        return self._note_usage(norm_cursor(json.loads(self._run('json').stdout), self.model_id))

    def _stream_step(self, max_output_tokens=None):
        "The same turn as `stream-json`: thinking deltas on their own channel, text as it lands."
        if self.use_sdk:
            yield from self._sdk_stream_step(max_output_tokens)
            return
        proc = subprocess.Popen(self._cmd('stream-json') + ['--stream-partial-output', self._prompt()],
                                stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        split, res = StreamSplit(), None
        with proc:
            for line in proc.stdout:
                if not (line := line.strip()): continue
                try: o = json.loads(line)
                except json.JSONDecodeError: continue
                if o.get('type') == 'thinking' and (t := o.get('text')): yield {'channels': {'thought': t}}
                elif o.get('type') == 'assistant':
                    for p in (o.get('message') or {}).get('content') or []:
                        if (t := p.get('text')): yield from split.feed(t)
                elif o.get('type') == 'result': res = o
            yield from split.finish()
        if res is None: raise RuntimeError(f'cursor-agent ended without a result: {proc.stderr.read()[:400]}')
        self._step_res = self._note_usage(norm_cursor(res, self.model_id))

    def _oneshot(self, prompt, sp='', think=None, max_tokens=None):
        """Stateless one-shot text, through whichever path this chat uses.

        `think` and `max_tokens` have no switch on either path - Cursor decides how much a model
        deliberates and how long it may answer for - so they are accepted and ignored rather than
        quietly changing the meaning of a cheap job.
        """
        msg = f'{sp}\n\n{prompt}' if sp else prompt
        if self.use_sdk:
            agent = self._mk_agent()
            try: return resp_text(self._sdk_resp(agent.send(msg)))
            finally:
                try: agent.close()
                except Exception: pass
        r = self._run('json', msg)
        return resp_text(norm_cursor(json.loads(r.stdout), self.model_id))

# %% ../nbs/05_cursor.ipynb #cu_sdk
@patch
def _mk_agent(self:CursorChat):
    "A live SDK agent for this chat: one login, one session, many turns."
    from cursor_sdk import Agent, AgentOptions, LocalAgentOptions, SandboxOptions
    local = LocalAgentOptions(cwd=str(self.workspace or Path.cwd()),
                              sandbox_options=None if self.sandbox is None else
                              SandboxOptions(enabled=self.sandbox not in (False, 'disabled')))
    opts = AgentOptions(model=cursor_model(self.model_id, self.effort, self.fast, via='sdk'),
                        api_key=self.api_key, mode=sdk_mode(self.mode),
                        tools=self.cursor_tools, disallowed_tools=self.cursor_disallowed, local=local)
    return Agent.create(opts)

@patch(as_prop=True)
def agent(self:CursorChat):
    "The live agent, built on first use and kept until something invalidates the conversation."
    if self._agent is None: self._agent, self._sent = self._mk_agent(), 0
    return self._agent

@patch
def _tail(self:CursorChat):
    """The part of the conversation the live agent has not seen; the briefing rides on the first one.

    A continuing agent remembers its own replies, so they are left out - what it needs is what
    happened since: the question, and any tool result the loop has produced for it. A rebuilt agent
    remembers nothing and gets everything.
    """
    new = self.hist[self._sent:]
    if self._sent: new = [m for m in new if m.get('role') != 'assistant']
    pre = tag_tools_sp(self.toolspecs, self.sp) if not self._sent else ''
    # the caller marks it sent once the agent has taken it: a send that raises must not leave the
    # briefing behind, or every turn after a network blip goes out unbriefed and short a message
    return render_prompt(new, pre), len(self.hist)

@patch
def _sdk_resp(self:CursorChat, run):
    "A finished SDK `Run` -> a rishi `Resp`, through the same normalizer the CLI path uses."
    res = run.wait()
    if (st := getattr(res, 'status', 'finished')) not in ('finished', None):
        raise RuntimeError(f'cursor-sdk run {st}: {resp_text({"content": getattr(res, "result", "")}) or "no detail"}')
    u = getattr(res, 'usage', None)
    usage = {'inputTokens': getattr(u, 'input_tokens', 0), 'outputTokens': getattr(u, 'output_tokens', 0),
             'cacheReadTokens': getattr(u, 'cache_read_tokens', 0)} if u else None
    return norm_cursor({'result': getattr(res, 'result', None) or '', 'usage': usage}, self.model_id)

@patch
def _sdk_step(self:CursorChat, max_output_tokens=None):
    "One turn through the live agent: only what it has not already been told goes out."
    msg, n = self._tail()
    run = self.agent.send(msg)
    self._sent = n
    return self._note_usage(self._sdk_resp(run))

@patch
def _sdk_stream_step(self:CursorChat, max_output_tokens=None):
    "The same turn, streamed; thinking has its own channel and tag calls never render as prose."
    msg, n = self._tail()
    run, split = self.agent.send(msg), StreamSplit()
    self._sent = n
    for m in run.messages():
        if (t := getattr(m, 'type', None)) == 'thinking':
            if (tx := getattr(m, 'text', '')): yield {'channels': {'thought': tx}}
        elif t == 'assistant':
            for b in getattr(getattr(m, 'message', None), 'content', None) or []:
                if getattr(b, 'type', None) == 'text' and (tx := getattr(b, 'text', '')): yield from split.feed(tx)
    yield from split.finish()
    self._step_res = self._note_usage(self._sdk_resp(run))

@patch
def close(self:CursorChat):
    "Let the live agent go; the next turn builds another."
    if self._agent is not None:
        try: self._agent.close()
        except Exception: pass
        self._agent, self._sent = None, 0
