"""Google's [litert_lm](https://github.com/google-ai-edge/litert-lm) backend for `.litertlm` Gemma builds: litert message helpers, GPU and NPU backends, KV-cache usage, and `bench()`.

Docs: https://vedicreader.github.io/rishi/litert.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_litert.ipynb.

# %% auto #0
__all__ = ['gemma4_e4b', 'gemma4_e2b', 'gemma4_12b', 'LITERT_GPU', 'ChatToolHandler', 'LitertChat', 'bench', 'LitertBroker']

# %% ../nbs/02_litert.ipynb #acd92ae986b06129
import json, re, os, asyncio, io, base64, uuid, warnings
from html import escape
from mimetypes import guess_type
from contextlib import ExitStack, redirect_stdout
from litert_lm import (ActivationDataType, Engine, Backend, ConstrainedDecodingConfig, Conversation, Session, Message, Contents, Content, Role, ToolCall,
                       ToolEventHandler, SamplerConfig, Benchmark, set_min_log_severity)
from litert_lm._messages import Text, ImageBytes, ImageFile, AudioBytes, AudioFile, ToolResponse, normalize_message
from huggingface_hub import hf_hub_download, list_repo_files, scan_cache_dir
from fastcore.all import Path, store_attr, patch, L, GetAttr, ifnone, detect_mime, first, listify, img_bytes, AttrDict, in_, str2bool
from safepyrun import RunPython
import rishi.core
from urai import (BrokerChat, Chat, ChatBroker, ChatCallback, ChatOpts, ContextWindowExceededError, Resp, SlidingWindowCallback,
                  StreamFormatter, UsageStats, budget_msg_, evict_middle, extract_fence, is_ctx_error, is_path,
                  get_runtime, resp_text, run_cbs, split_runtime, thought, tool_reminder_)


# %% ../nbs/02_litert.ipynb #6e295c9a
def _mk_content(o):
    'Convert `o` to a litert `Content`, sniffing bytes/files for image vs audio.'
    if isinstance(o, Content): return o
    if isinstance(o, str): return Text(o)
    if isinstance(o, bytes): return AudioBytes(o) if (detect_mime(o) or '').startswith('audio/') else ImageBytes(o)
    if isinstance(o, Path): return AudioFile(str(o)) if (guess_type(str(o))[0] or '').startswith('audio/') else ImageFile(str(o))
    raise TypeError(f"Unsupported content type: {type(o)}")

def _mk_msg(content, role='user'):
    'Create a litert `Message` from str/bytes/list/dict/Message.'
    if content is None: return None
    if isinstance(content, Message): return content
    if isinstance(content, dict): return Message(Role(content['role']), Contents.of(content['content']))
    parts = [_mk_content(o) for o in content] if isinstance(content, list) else [_mk_content(content)]
    return Message(Role(role), Contents(parts))

def _mk_msgs(msgs):
    'Normalize a list of messages to litert message dicts.'
    if not msgs: return []
    return [normalize_message(m if isinstance(m, (Message, dict)) else _mk_msg(m)) for m in listify(msgs)]

# %% ../nbs/02_litert.ipynb #e2f22e05c7e09016
def _call_id(): return f"call_{uuid.uuid4().hex[:8]}"

_ph = {'image': '[image]', 'audio': '[audio]'}
def _canon_content(c):
    "litert content (str or list of parts) -> a canonical string, with media as `[image]`/`[audio]`."
    if c is None or isinstance(c, str): return c
    return '\n'.join(p.get('text', '') if p.get('type') == 'text' else _ph.get(p.get('type'), '[media]')
                     for p in c if isinstance(p, dict))

def _fmt2hist(m, dflt_role='user'):
    "One litert message (str/`Message`/native dict/`Resp`) -> a canonical rishi history dict."
    if isinstance(m, str): return {'role': 'user', 'content': m}
    if isinstance(m, Message): m = m.to_json()
    elif not isinstance(m, dict): m = _mk_msg(m).to_json()
    role = 'assistant' if m.get('role') == 'model' else m.get('role', dflt_role)
    content = m.get('content')
    if role == 'tool':
        if isinstance(content, list):
            tr = first(content, lambda p: isinstance(p, dict) and p.get('type') == 'tool_response') or {}
            out = {'role': 'tool', 'name': tr.get('name', ''), 'content': str(tr.get('response', ''))}
        else: out = {'role': 'tool', 'content': content if isinstance(content, str) else str(content)}
        if m.get('name'): out['name'] = m['name']
        if m.get('tool_call_id'): out['tool_call_id'] = m['tool_call_id']
        return out
    out = {'role': role}
    if (cc := _canon_content(content)) is not None: out['content'] = cc
    if m.get('channels'): out['channels'] = dict(m['channels'])
    if m.get('tool_calls'):
        out['tool_calls'] = [{'id': tc.get('id') or _call_id(), 'type': 'function',
                              'function': {'name': tc.get('function', {}).get('name', ''),
                                           'arguments': tc.get('function', {}).get('arguments', {})}}
                             for tc in m['tool_calls']]
        out.setdefault('content', '')
    return out

def _data_uri_bytes(url):
    "Decode a `data:...;base64,...` URI to bytes, else None."
    if isinstance(url, str) and url.startswith('data:') and ';base64,' in url:
        return base64.b64decode(url.split(';base64,', 1)[1])
    return None

def _litert_contents(c):
    "Canonical content (str or OpenAI-style parts) -> a litert `Contents`."
    if c is None: return Contents.empty()
    if isinstance(c, str): return Contents.of(c)
    parts = []
    for p in c:
        if not isinstance(p, dict): continue
        t = p.get('type')
        if t == 'text': parts.append(Text(p.get('text', '')))
        elif t == 'image_url':
            u = p.get('image_url', {}); url = u.get('url') if isinstance(u, dict) else u
            parts.append(ImageBytes(b) if (b := _data_uri_bytes(url)) is not None else ImageFile(url))
        elif t == 'input_audio': parts.append(AudioBytes(base64.b64decode((p.get('input_audio') or {}).get('data', ''))))
    return Contents(parts)

def _hist2fmt1(m):
    "One canonical rishi history dict (or raw input) -> a litert `Message` for the engine."
    if isinstance(m, Message): return m
    if isinstance(m, str): return Message.user(m)
    if not isinstance(m, dict): return _mk_msg(m)
    role = m.get('role', 'user')
    if role == 'tool': return Message.tool(Contents([ToolResponse(m.get('name', ''), m.get('content', ''))]))
    tcs = [ToolCall(tc.get('function', {}).get('name', ''), tc.get('function', {}).get('arguments', {}))
           for tc in (m.get('tool_calls') or [])]
    return Message(Role('model' if role == 'assistant' else role), _litert_contents(m.get('content')),
                   tool_calls=tcs, channels=(m.get('channels') or None))

def _to_litert_msg(m):
    "Raw input or a (canonical/native) chat dict -> a litert `Message` for the engine preface."
    return m if isinstance(m, Message) else (_hist2fmt1(m) if isinstance(m, dict) else _mk_msg(m))



# %% ../nbs/02_litert.ipynb #29afb8197a5161ee
class _ToolReminderCallback(ChatCallback):
    'Inject a tool-summary reminder into the outgoing message when tools are registered.'
    order = 30
    def __init__(self, tool_reminder=tool_reminder_): store_attr()
    def before_send(self):
        if self.chat.tools and self.chat.turn_msg is not None: self.chat.turn_msg.contents.contents.append(Text(self.tool_reminder))


# %% ../nbs/02_litert.ipynb #5f80e3d39946d7b
class _HistoryCallback(ChatCallback):
    'Record the outgoing message and the response into `chat.hist` (canonical form).'
    order = 0
    def before_send(self):
        if self.chat.turn_msg is not None:
            self.chat.hist.append(_fmt2hist(self.chat.turn_msg))
            self.chat._turn_msg_recorded = True
    def after_response(self): self.chat.hist.append(_fmt2hist(self.chat.turn_res, 'assistant'))

class _UsageCallback(ChatCallback):
    'Fold each response\'s token usage into `chat.use` from a `token_count` diff.'
    order = 10
    def after_response(self):
        c = self.chat; delta = c.conv.token_count - c._tc0
        out = len(c.engine.tokenize(resp_text(c.turn_res)))
        new_prompt, cached = max(delta - out, 0), c._tc0
        c.use += UsageStats(prompt_tokens=cached + new_prompt, completion_tokens=out,
                            total_tokens=cached + delta, n=1, cached_tokens=cached)


# %% ../nbs/02_litert.ipynb #1d26406d13cefa08
#: Tool name from an OpenAI-shaped tool-call dict.
def _tc_name(tc): return tc.get('function', {}).get('name', '')

class ChatToolHandler(ToolEventHandler):
    "Bridge litert's in-engine tool loop to Chat callbacks, HITL approval, the tool-call budget, and history."
    def __init__(self, chat): self.chat = chat
    def approve_tool_call(self, tool_call):
        c = self.chat
        c.turn_tc = tool_call
        for _ in run_cbs(c, 'before_tool_calls'): pass
        over = c._budget_exceeded or (c.max_steps is not None and c._steps >= c.max_steps)
        ok = False if over else (c.approve(tool_call) if c.approve else True)
        if ok: c._steps += 1
        else: c._budget_exceeded = c._budget_exceeded or over
        fn = tool_call.get('function', {}); self._tcid = _call_id()
        c.hist.append({'role': 'assistant', 'content': '',
            'tool_calls': [{'id': self._tcid, 'type': 'function',
                            'function': {'name': fn.get('name', ''), 'arguments': fn.get('arguments', {})}}]})
        if not ok: c.hist.append({'role': 'tool', 'tool_call_id': self._tcid, 'name': fn.get('name', ''),
                                  'content': budget_msg_ if over else 'Denied by human operator'})
        return ok
    def process_tool_response(self, tool_response):
        mx = getattr(self.chat, 'tool_max_len', None)
        if mx and isinstance(tool_response, str) and len(tool_response) > mx:
            tool_response = tool_response[:mx] + ' …[truncated]'
        self.chat.turn_tool_result = tool_response
        self.chat.hist.append({'role': 'tool', 'tool_call_id': getattr(self, '_tcid', None),
                               'name': _tc_name(self.chat.turn_tc), 'content': str(tool_response)})
        for _ in run_cbs(self.chat, 'after_tool_calls'): pass
        return tool_response


# %% ../nbs/02_litert.ipynb #6aa00146bc49f9c1
#: Default litert-community model ids.
gemma4_e4b='litert-community/gemma-4-E4B-it-litert-lm'
gemma4_e2b='litert-community/gemma-4-E2B-it-litert-lm'
gemma4_12b='litert-community/gemma-4-12B-it-litert-lm'


# %% ../nbs/02_litert.ipynb #335a97782120c273
#: `RISHI_LITERT_GPU=0` forces CPU when GPU/NPU init fails.
_special_build = re.compile(r'(-(gpu|web|npu)|_)[^/]*\.litertlm$')
def _portable(p):
    "Whether `p` is portable across LiteRT backends."
    return bool(p) and not _special_build.search(str(p))

LITERT_GPU = str2bool(os.getenv('RISHI_LITERT_GPU', '1').lower())
def _litertlm(fs):
    "Select a portable `.litertlm`, excluding web builds."
    return first(sorted([p for p in fs if p.endswith('.litertlm') and 'web' not in p], key=lambda p: not _portable(p)))

def _cached_model(model_id):
    "Local `.litertlm` path from the HF cache without hitting the network, else None."
    try: repo = first(scan_cache_dir().repos, lambda r: r.repo_id == model_id)
    except Exception: return None
    return _litertlm(str(f.file_path) for r in repo.revisions for f in r.files) if repo else None

def _get_model(model_id, model_path=None):
    "Return a local `.litertlm` path: `model_path`, else HF cache, else download."
    if model_path and Path(model_path).exists(): return model_path
    hit = _cached_model(model_id)
    if _portable(hit): return hit
    try: fn = _litertlm(list_repo_files(model_id))
    except Exception:
        if hit: return hit
        raise
    if not fn and not hit: raise FileNotFoundError(f"No .litertlm file found for {model_id}")
    return hf_hub_download(model_id, fn) if _portable(fn) or not hit else hit

def _is_gpu(be):
    "Whether `be` is litert's GPU backend, as an instance or as the class."
    return isinstance(be, Backend.GPU) or (isinstance(be, type) and issubclass(be, Backend.GPU))

#: Header names of the encoders a multimodal engine can be given a backend for.
_encoders = {'vision_backend': b'tf_lite_vision_encoder', 'audio_backend': b'tf_lite_audio_encoder'}
def _mm_kw(mod, vbe, abe):
    "Return backends for encoders present in `mod`."
    try:
        with open(mod, 'rb') as f: head = f.read(1<<16)
    except OSError: head = b''.join(_encoders.values())
    out = {}
    for k, v in (('vision_backend', vbe), ('audio_backend', abe)):
        if _encoders[k] in head: out[k] = ifnone(v, Backend.CPU())
        elif v is not None: warnings.warn(f"{Path(mod).name} carries no {k.split('_')[0]} encoder; building without one.")
    return out

def _gpu_act(be, kw):
    "Use float32 GPU activations unless the caller chose a dtype."
    return {} if 'activation_data_type' in kw or not _is_gpu(be) else {'activation_data_type': ActivationDataType.FLOAT32}

def _merge_chunks(chunks):
    "Reconstruct an assistant response dict (text + thinking) from streamed litert chunks."
    text, th = ''.join(resp_text(c) for c in chunks), ''.join(thought(c) for c in chunks)
    r = {'role': 'assistant', 'content': [{'type': 'text', 'text': text}]}
    if th: r['channels'] = {'thought': th}
    return Resp(r)

_dflt_cbs = [_HistoryCallback, _UsageCallback, _ToolReminderCallback, SlidingWindowCallback]

class LitertChat(Chat):
    "Sync chat over a local litert_lm engine."
    _runtime = 'litert'
    _dflt_cbs = _dflt_cbs
    mk_content, mk_msg, mk_msgs = staticmethod(_mk_content), staticmethod(_mk_msg), staticmethod(_mk_msgs)

    @staticmethod
    def fmt2hist(msgs):
        "litert-native messages -> canonical rishi history dicts."
        return [_fmt2hist(m) for m in listify(msgs)]
    @staticmethod
    def hist2fmt(msgs):
        "Canonical rishi history dicts -> litert `Message`s for the engine."
        return [_hist2fmt1(m) for m in listify(msgs)]

    @classmethod
    def create_engine(cls, model_id=gemma4_e2b, model_path=None, be=None, vbe=None, abe=None,
                      multimodal=True, cache_dir=None, enable_speculative_decoding=None, **kw):
        'Build a litert `Engine` on the GPU unless told otherwise, creating `cache_dir` if given. `@patch` to customize.'
        be, vbe, abe = kw.pop('backend', be), kw.pop('vision_backend', vbe), kw.pop('audio_backend', abe)
        if cache_dir: Path(cache_dir).mkdir(parents=True, exist_ok=True)
        mod = _get_model(model_id, model_path)
        def _mk(b):
            mm = _mm_kw(mod, vbe, abe) if multimodal else {}
            return Engine(mod, backend=b, cache_dir=cache_dir or '',
                          enable_speculative_decoding=enable_speculative_decoding, **_gpu_act(b, kw), **mm, **kw)
        if be is not None: return _mk(be)
        if LITERT_GPU:
            try: return _mk(Backend.GPU())
            except Exception as e:
                warnings.warn(f'litert GPU backend unavailable ({type(e).__name__}: {e}) - falling back to the '
                              'CPU. Set RISHI_LITERT_GPU=0 to stop asking for it.')
        return _mk(Backend.CPU())

    #: litert takes the window when it builds the engine, and nests it inside `eng_kw`
    _opt_map = {'ctx': 'eng_kw.max_num_tokens'}
    _opt_skip = ('effort', 'tool_mode', 'api_key', 'base_url')   # nothing local takes these

    def __init__(self, model=None, *, runtime=None, model_path=None, opts=None,
                 engine=None,        # an engine to share instead of building one
                 backend=None,       # litert's hardware backend: `Backend.CPU()` or `Backend.GPU()`
                 multimodal=True,    # build the vision and audio backends too
                 cache_dir=None, enable_speculative_decoding=None,
                 eng_kw=None,        # passed to `create_engine` verbatim
                 filter_think=True,  # keep thought tokens out of the KV cache
                 sampler_config=None,  # a litert `SamplerConfig`, instead of the portable sampling options
                 constrain=None,     # constrained decoding; default is on when there are tools
                 conv_kw=None,       # passed to `create_conversation` verbatim
                 **kw):              # portable options; see `urai.ChatOpts`
        o = ChatOpts.create(opts, **kw)
        if o.parallel_tools: raise NotImplementedError(
            "litert runs its tool loop inside the engine, so it can't dispatch calls in parallel; "
            "use runtime='llama' (or 'mlx') for parallel_tools=True.")
        model = split_runtime(model)[1]
        model_id = None if model is None or is_path(model) else model
        model_path = model_path or (model if model and is_path(model) else None)
        self._stack, self._conv_stack = ExitStack(), ExitStack()
        ekw = dict(eng_kw or {})
        if o.ctx: ekw.setdefault('max_num_tokens', o.ctx)
        self._own_engine = engine is None
        if self._own_engine:
            engine = self.create_engine(model_id or gemma4_e2b, model_path, backend,
                multimodal=multimodal, cache_dir=cache_dir,
                enable_speculative_decoding=enable_speculative_decoding, **ekw)
            self.engine = self._stack.enter_context(engine)
        else: self.engine = engine
        # the system prompt is kept apart from `hist` and re-applied on every rebuild, so eviction
        # can never drop it: it is the anchor a sliding window is supposed to preserve
        self._sys_pre = [{'role': 'system', 'content': o.sp}] if o.sp else []
        if sampler_config is None and any(x is not None for x in (o.temp, o.top_k, o.top_p, o.seed)):
            sampler_config = SamplerConfig(temperature=o.temp, top_k=o.top_k, top_p=o.top_p, seed=o.seed)
        cvk = dict(sampler_config=sampler_config, max_output_tokens=o.max_output_tokens or None,
                   **(conv_kw or {}))
        if o.think: cvk['extra_context'] = {**cvk.get('extra_context', {}), 'enable_thinking': True}
        if filter_think: cvk['filter_channel_content_from_kv_cache'] = True
        if (legacy := cvk.pop('enable_constrained_decoding', None)) is not None:
            warnings.warn("enable_constrained_decoding was litert's own name for this and is "
                          'not accepted any more; pass constrain=True/False to rishi instead.',
                          DeprecationWarning, stacklevel=2)
            if constrain is None: constrain = bool(legacy)
        self._constrain = constrain
        self._conv_kw, self.tools, self.conv = cvk, L(o.tools), None
        self.tool_handler = ChatToolHandler(self)
        self._mk_conv(self._sys_pre + [_to_litert_msg(m) for m in listify(o.messages)])
        self.ctx_limit = o.ctx or None
        self._setup(model, o)

    def _constrained(self):
        "The `constrained_decoding_config` to build with, or `None`. Default is on when there are tools."
        if 'constrained_decoding_config' in self._conv_kw: return None
        want = bool(self.tools) if self._constrain is None else bool(self._constrain)
        return ConstrainedDecodingConfig(enable=True) if want else None

    def _mk_conv(self, messages=None):
        "Build the conversation from `messages`, releasing any current one first."
        self._conv_stack.close()
        self._conv_stack = ExitStack()
        kw = dict(self._conv_kw)
        if (cd := self._constrained()) is not None: kw['constrained_decoding_config'] = cd
        self.conv = self._conv_stack.enter_context(self.engine.create_conversation(
            messages=messages or None, tools=list(self.tools) or None,
            tool_event_handler=self.tool_handler, **kw))
        return self.conv

    def _set_sp(self, sp):
        "The system prompt lives outside `hist` here, so `reconfigure` has to replace it explicitly."
        self._sys_pre = [{'role': 'system', 'content': sp}] if sp else []

    def _recreate_conv(self):
        "Rebuild the `Conversation` from the current (possibly evicted) `hist`, re-applying the system prompt."
        self._mk_conv(self._sys_pre + [_to_litert_msg(m) for m in self.hist])

    def recover_context(self, err, **kw):
        "Recover a full context by evicting the middle of history and retrying the current message."
        return self._retry_evicted(err, **kw)

    def _retry_evicted(self, err, keep_first=2, keep_last=6, **turn):
        "The window filled up mid-turn: evict the middle of `hist`, rebuild, and send the same turn again."
        kept, dropped = evict_middle(self.hist, keep_first, keep_last)
        if not dropped:
            raise ContextWindowExceededError(f"context window full and nothing left to evict: {err}") from err
        self.hist[:] = kept
        self.evicted = getattr(self, 'evicted', 0) + len(dropped)
        # The outgoing message may already be in Python history, but it is about to be
        # sent again. Do not put that copy in the rebuilt engine preface.
        prior = self.hist[:-1] if self._turn_msg_recorded else self.hist
        self._mk_conv(self._sys_pre + [_to_litert_msg(m) for m in prior])
        self._tc0 = self.conv.token_count            # the rebuilt cache is a new baseline for usage
        try: return self.conv.send_message(self.turn_msg, **self._turn_kw(turn))
        except RuntimeError as e:
            raise ContextWindowExceededError(
                f"could not recover after evicting {len(dropped)} messages: {err}") from err

    @property
    def token_count(self): return self.conv.token_count
    @property
    def cached_tokens(self):
        "Tokens already resident in this conversation's KV cache and reusable by the next turn."
        return self.conv.token_count
    def cancel(self):
        "Cancel the in-flight generation, and set the flag the shared loop reads."
        super().cancel()
        if self.conv is not None: self.conv.cancel_process()
        return True
    def count_tokens(self, text):
        "Number of tokens in `text` per the engine tokenizer."
        return len(self.engine.tokenize(text))
    def render(self, msg):
        "The exact templated string litert will send for `msg`."
        return self.conv.render_message_to_string(_mk_msg(msg))
    def _turn_kw(self, turn):
        "What litert's `send_message` takes from this turn's generation options."
        t = self.map_opts(turn); t.pop('eng_kw', None)   # the window was fixed when the engine built
        return {'max_output_tokens': t.get('max_output_tokens')}

    def _send(self, msg, **kw):
        'Send one message through the callback pipeline, evicting and retrying once if the window fills.'
        self.turn_msg = _mk_msg(msg)
        self._turn_msg_recorded = False
        for _ in run_cbs(self, 'before_send'): pass
        self._tc0 = self.conv.token_count      # after the callbacks: one may have rebuilt `conv`
        try: r = self.conv.send_message(self.turn_msg, **self._turn_kw(kw))
        except RuntimeError as e:
            if not is_ctx_error(self, e): raise
            r = self.recover_context(e, **kw)
        self.turn_res = Resp(r)
        for _ in run_cbs(self, 'after_response'): pass
        return self.turn_res
    def _stream(self, msg, cbs=None, **kw):
        'Stream a turn as markdown chunks. Per-call `cbs` live only for this turn.'
        added = self.add_cbs(cbs); prev = getattr(self, '_streaming', False); self._streaming = True
        try:
            self.turn_msg = _mk_msg(msg)
            for _ in run_cbs(self, 'before_send'): pass
            self._tc0 = self.conv.token_count   # after the callbacks: one may have rebuilt `conv`
            fmt, chunks = StreamFormatter(), []
            for o in self.conv.send_message_async(self.turn_msg, **self._turn_kw(kw)):
                chunks.append(o); yield self._emit(o, fmt)
            self.turn_res = _merge_chunks(chunks)
            yield from run_cbs(self, 'after_response')
            return self.turn_res   # stream's final Resp, captured by SaveReturn / AsyncChat `.value`
        finally: self._streaming = prev; self.remove_cbs(added)
    def _oneshot(self, prompt, sp='', think=None, max_tokens=None):
        """Stateless one-shot completion text via a throwaway conversation."""
        kw = {'extra_context': {'enable_thinking': True}} if think else {}
        if max_tokens is not None: kw['max_output_tokens'] = int(max_tokens)
        pre = [{'role': 'system', 'content': sp}] if sp else None
        with self.engine.create_conversation(messages=pre, **kw) as conv:
            return resp_text(conv.send_message(prompt))
    def _structured_call(self, prompt, schema, sp):
        "Forced tool call, falling back to parsing a JSON reply when the model answers in prose."
        pre = [{'role': 'system', 'content': sp}] if sp else None
        with self.engine.create_conversation(messages=pre, tools=[schema], automatic_tool_calling=False) as conv:
            r = conv.send_message(prompt)
        if tcs := r.get('tool_calls'): return tcs[0].get('function', {}).get('arguments', {})
        try: return json.loads(extract_fence(resp_text(r), 'json'))
        except (json.JSONDecodeError, TypeError) as e: raise ValueError(f"model neither called the tool nor returned JSON; reply: {resp_text(r)[:200]!r}") from e
    def close(self):
        "Release this chat's conversation and, only when owned, its engine (idempotent)."
        if getattr(self, '_conv_stack', None) is not None: self._conv_stack.close(); self._conv_stack = None
        if getattr(self, '_own_engine', False) and getattr(self, '_stack', None) is not None:
            self._stack.close()
        self._stack = None
        self.conv = None


# %% ../nbs/02_litert.ipynb #bea63711
def bench(model_id=gemma4_e2b, model_path=None, backend=Backend.CPU(), prefill_tokens=64, decode_tokens=64, **kw):
    "Benchmark init time, TTFT, and prefill/decode tokens-per-sec via litert's `Benchmark`."
    return Benchmark(_get_model(model_id, model_path), backend=backend, prefill_tokens=prefill_tokens, decode_tokens=decode_tokens, **kw).run()


# %% ../nbs/02_litert.ipynb #90e13724
class LitertBroker(ChatBroker):
    'Shared LiteRT engine broker. Each client gets an isolated `LitertChat` conversation.'
    def __init__(self, address, engine=None, model_id=gemma4_e2b, **engine_kw):
        super().__init__(address, LitertChat, engine, model_id, **engine_kw)
