"""A fastllm-style `Chat` over litert_lm - message helpers, an ordered callback system, human-in-the-loop tool approval, sync streaming, and `token_count`-based usage tracking.

Docs: https://vedicreader.github.io/rishi/litert.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_litert.ipynb.

# %% auto #0
__all__ = ['gemma4_e4b', 'gemma4_e2b', 'gemma4_12b', 'ChatToolHandler', 'LitertChat', 'bench']

# %% ../nbs/02_litert.ipynb #acd92ae986b06129
import json, re, os, asyncio, io, base64, uuid
from html import escape
from mimetypes import guess_type
from contextlib import ExitStack, redirect_stdout
from litert_lm import (Engine, Backend, Conversation, Session, Message, Contents, Content, Role, ToolCall,
                       ToolEventHandler, SamplerConfig, Benchmark, set_min_log_severity)
from litert_lm._messages import Text, ImageBytes, ImageFile, AudioBytes, AudioFile, ToolResponse, normalize_message
from huggingface_hub import hf_hub_download, list_repo_files, scan_cache_dir
from fastcore.all import Path, store_attr, patch, L, GetAttr, ifnone, detect_mime, first, listify, img_bytes, AttrDict, in_
from safepyrun import RunPython
from . import core
from .core import *


# %% ../nbs/02_litert.ipynb #6e295c9a
def _mk_content(o):
    'Convert `o` to a litert `Content`, sniffing bytes/files for image vs audio.'
    if isinstance(o, Content): return o
    if isinstance(o, str): return Text(o)
    if isinstance(o, bytes): return AudioBytes(o) if (detect_mime(o) or '').startswith('audio/') else ImageBytes(o)
    if isinstance(o, Path): return AudioFile(str(o)) if (guess_type(str(o))[0] or '').startswith('audio/') else ImageFile(str(o))
    raise TypeError(f"Unsupported content type: {type(o)}")

def _mk_msg(content, role='user'):
    'Create a litert `Message` from str/bytes/list/dict/Message.'
    if content is None: return None
    if isinstance(content, Message): return content
    if isinstance(content, dict): return Message(Role(content['role']), Contents.of(content['content']))
    parts = [_mk_content(o) for o in content] if isinstance(content, list) else [_mk_content(content)]
    return Message(Role(role), Contents(parts))

def _mk_msgs(msgs):
    'Normalize a list of messages to litert message dicts.'
    if not msgs: return []
    return [normalize_message(m if isinstance(m, (Message, dict)) else _mk_msg(m)) for m in listify(msgs)]

# %% ../nbs/02_litert.ipynb #4a2c4afb
def _call_id(): return f"call_{uuid.uuid4().hex[:8]}"

_ph = {'image': '[image]', 'audio': '[audio]'}
def _canon_content(c):
    "litert content (str or list of parts) -> a canonical string; media -> `[image]`/`[audio]`."
    if c is None or isinstance(c, str): return c
    return '\n'.join(p.get('text', '') if p.get('type') == 'text' else _ph.get(p.get('type'), '[media]')
                     for p in c if isinstance(p, dict))

def _fmt2hist(m, dflt_role='user'):
    "One litert message (str/`Message`/native dict/`Resp`) -> a canonical rishi history dict."
    if isinstance(m, str): return {'role': 'user', 'content': m}
    if isinstance(m, Message): m = m.to_json()
    elif not isinstance(m, dict): m = _mk_msg(m).to_json()
    role = 'assistant' if m.get('role') == 'model' else m.get('role', dflt_role)
    content = m.get('content')
    if role == 'tool':
        if isinstance(content, list):
            tr = first(content, lambda p: isinstance(p, dict) and p.get('type') == 'tool_response') or {}
            out = {'role': 'tool', 'name': tr.get('name', ''), 'content': str(tr.get('response', ''))}
        else: out = {'role': 'tool', 'content': content if isinstance(content, str) else str(content)}
        if m.get('name'): out['name'] = m['name']
        if m.get('tool_call_id'): out['tool_call_id'] = m['tool_call_id']
        return out
    out = {'role': role}
    if (cc := _canon_content(content)) is not None: out['content'] = cc
    if m.get('channels'): out['channels'] = dict(m['channels'])
    if m.get('tool_calls'):
        out['tool_calls'] = [{'id': tc.get('id') or _call_id(), 'type': 'function',
                              'function': {'name': tc.get('function', {}).get('name', ''),
                                           'arguments': tc.get('function', {}).get('arguments', {})}}
                             for tc in m['tool_calls']]
        out.setdefault('content', '')
    return out

def _data_uri_bytes(url):
    "Decode a `data:...;base64,...` URI to bytes, else None."
    if isinstance(url, str) and url.startswith('data:') and ';base64,' in url:
        return base64.b64decode(url.split(';base64,', 1)[1])
    return None

def _litert_contents(c):
    "Canonical content (str or OpenAI-style parts) -> a litert `Contents`."
    if c is None: return Contents.empty()
    if isinstance(c, str): return Contents.of(c)
    parts = []
    for p in c:
        if not isinstance(p, dict): continue
        t = p.get('type')
        if t == 'text': parts.append(Text(p.get('text', '')))
        elif t == 'image_url':
            u = p.get('image_url', {}); url = u.get('url') if isinstance(u, dict) else u
            parts.append(ImageBytes(b) if (b := _data_uri_bytes(url)) is not None else ImageFile(url))
        elif t == 'input_audio': parts.append(AudioBytes(base64.b64decode((p.get('input_audio') or {}).get('data', ''))))
    return Contents(parts)

def _hist2fmt1(m):
    "One canonical rishi history dict (or raw input) -> a litert `Message` for the engine."
    if isinstance(m, Message): return m
    if isinstance(m, str): return Message.user(m)
    if not isinstance(m, dict): return _mk_msg(m)
    role = m.get('role', 'user')
    if role == 'tool': return Message.tool(Contents([ToolResponse(m.get('name', ''), m.get('content', ''))]))
    tcs = [ToolCall(tc.get('function', {}).get('name', ''), tc.get('function', {}).get('arguments', {}))
           for tc in (m.get('tool_calls') or [])]
    return Message(Role('model' if role == 'assistant' else role), _litert_contents(m.get('content')),
                   tool_calls=tcs, channels=(m.get('channels') or None))

def _to_litert_msg(m):
    "Raw input or a (canonical/native) chat dict -> a litert `Message` for the engine preface."
    return m if isinstance(m, Message) else (_hist2fmt1(m) if isinstance(m, dict) else _mk_msg(m))


# %% ../nbs/02_litert.ipynb #172c44f0
class _ToolReminderCallback(ChatCallback):
    'Inject a tool-summary reminder into the outgoing message when tools are registered.'
    order = 30
    def __init__(self, tool_reminder=tool_reminder_): store_attr()
    def before_send(self):
        if self.chat.tools and self.chat.turn_msg is not None: self.chat.turn_msg.contents.contents.append(Text(self.tool_reminder))


# %% ../nbs/02_litert.ipynb #a090e557
class _HistoryCallback(ChatCallback):
    'Record the outgoing message and the response into `chat.hist` (canonical form).'
    order = 0
    def before_send(self):
        if self.chat.turn_msg is not None: self.chat.hist.append(_fmt2hist(self.chat.turn_msg))
    def after_response(self): self.chat.hist.append(_fmt2hist(self.chat.turn_res, 'assistant'))

class _UsageCallback(ChatCallback):
    'Fold each response\'s token usage into `chat.use` from a `token_count` diff.'
    order = 10
    def after_response(self):
        c = self.chat; delta = c.conv.token_count - c._tc0
        out = len(c.engine.tokenize(resp_text(c.turn_res)))
        c.use += UsageStats(prompt_tokens=max(delta - out, 0), completion_tokens=out, total_tokens=delta, n=1)


# %% ../nbs/02_litert.ipynb #b8dfc247
def _tc_name(tc): return tc.get('function', {}).get('name', '')

class ChatToolHandler(ToolEventHandler):
    "Bridge litert's in-engine tool loop to Chat callbacks, HITL approval, the tool-call budget, and history."
    def __init__(self, chat): self.chat = chat
    def approve_tool_call(self, tool_call):
        c = self.chat
        c.turn_tc = tool_call
        for _ in run_cbs(c, 'before_tool_calls'): pass
        over = c._budget_exceeded or (c.max_steps is not None and c._steps >= c.max_steps)
        ok = False if over else (c.approve(tool_call) if c.approve else True)
        if ok: c._steps += 1
        else: c._budget_exceeded = c._budget_exceeded or over
        fn = tool_call.get('function', {}); self._tcid = _call_id()
        c.hist.append({'role': 'assistant', 'content': '',
            'tool_calls': [{'id': self._tcid, 'type': 'function',
                            'function': {'name': fn.get('name', ''), 'arguments': fn.get('arguments', {})}}]})
        if not ok: c.hist.append({'role': 'tool', 'tool_call_id': self._tcid, 'name': fn.get('name', ''),
                                  'content': budget_msg_ if over else 'Denied by human operator'})
        return ok
    def process_tool_response(self, tool_response):
        mx = getattr(self.chat, 'tool_max_len', None)
        if mx and isinstance(tool_response, str) and len(tool_response) > mx:
            tool_response = tool_response[:mx] + ' …[truncated]'
        self.chat.turn_tool_result = tool_response
        self.chat.hist.append({'role': 'tool', 'tool_call_id': getattr(self, '_tcid', None),
                               'name': _tc_name(self.chat.turn_tc), 'content': str(tool_response)})
        for _ in run_cbs(self.chat, 'after_tool_calls'): pass
        return tool_response

# %% ../nbs/02_litert.ipynb #f717f851d413e77
gemma4_e4b='litert-community/gemma-4-E4B-it-litert-lm'
gemma4_e2b='litert-community/gemma-4-E2B-it-litert-lm'
gemma4_12b='litert-community/gemma-4-12B-it-litert-lm'

# %% ../nbs/02_litert.ipynb #40fb869354982708
def _litertlm(fs):
    "First native `.litertlm` path in `fs` (skips `-web`/other builds)."
    return first(fs, lambda p: p.endswith('.litertlm') and 'web' not in p)

def _cached_model(model_id):
    "Local `.litertlm` path from the HF cache without hitting the network, else None."
    try: repo = first(scan_cache_dir().repos, lambda r: r.repo_id == model_id)
    except Exception: return None
    return _litertlm(str(f.file_path) for r in repo.revisions for f in r.files) if repo else None

def _get_model(model_id, model_path=None):
    "Return a local `.litertlm` path: `model_path`, else HF cache, else download."
    if model_path and Path(model_path).exists(): return model_path
    if (hit := _cached_model(model_id)): return hit
    if not (fn := _litertlm(list_repo_files(model_id))): raise FileNotFoundError(f"No .litertlm file found for {model_id}")
    return hf_hub_download(model_id, fn)

def _merge_chunks(chunks):
    "Reconstruct an assistant response dict (text + thinking) from streamed litert chunks."
    text, th = ''.join(resp_text(c) for c in chunks), ''.join(thought(c) for c in chunks)
    r = {'role': 'assistant', 'content': [{'type': 'text', 'text': text}]}
    if th: r['channels'] = {'thought': th}
    return Resp(r)

_dflt_cbs = [_HistoryCallback, _UsageCallback, _ToolReminderCallback]

class LitertChat(core.Chat):
    "Sync chat over a local litert_lm engine."
    _runtime = 'litert'
    _dflt_cbs = _dflt_cbs
    mk_content, mk_msg, mk_msgs = staticmethod(_mk_content), staticmethod(_mk_msg), staticmethod(_mk_msgs)

    @staticmethod
    def fmt2hist(msgs):
        "litert-native messages -> canonical rishi history dicts."
        return [_fmt2hist(m) for m in listify(msgs)]
    @staticmethod
    def hist2fmt(msgs):
        "Canonical rishi history dicts -> litert `Message`s for the engine."
        return [_hist2fmt1(m) for m in listify(msgs)]

    @classmethod
    def create_engine(cls, model_id=gemma4_e2b, model_path=None, be=Backend.CPU(), vbe=Backend.CPU(),
                      abe=Backend.CPU(), multimodal=True, cache_dir=None, enable_speculative_decoding=None, **kw):
        'Build a litert `Engine`; creates `cache_dir` if given. Override/`@patch` to customize.'
        if cache_dir: Path(cache_dir).mkdir(parents=True, exist_ok=True)
        mod, mm = _get_model(model_id, model_path), dict(vision_backend=vbe, audio_backend=abe) if multimodal else {}
        return Engine(mod, backend=be, cache_dir=cache_dir or '', enable_speculative_decoding=enable_speculative_decoding, **mm, **kw)

    def __init__(self, model=None, *, runtime=None, model_path=None, engine=None, backend=Backend.CPU(),
                 multimodal=True, cache_dir=None, enable_speculative_decoding=None, eng_kw=None,
                 sp='', messages=None, tools=None, ctx_limit=None, approve=None, tool_max_len=None,
                 max_steps=10, final_prompt=dflt_final_prompt_, parallel_tools=False,
                 think=False, filter_think=True, temp=None, top_k=None, top_p=None,
                 seed=None, sampler_config=None, max_output_tokens=None, conv_kw=None, cbs=None, default_cbs=True):
        if parallel_tools: raise NotImplementedError(
            "litert runs its tool loop inside the engine, so it can't dispatch calls in parallel; "
            "use runtime='llama' (or 'mlx') for parallel_tools=True.")
        model = core.split_runtime(model)[1]
        model_id = None if model is None or core._is_path(model) else model
        model_path = model_path or (model if model and core._is_path(model) else None)
        self._stack = ExitStack()
        if not engine: engine = self.create_engine(model_id or gemma4_e2b, model_path, backend,
            multimodal=multimodal, cache_dir=cache_dir, enable_speculative_decoding=enable_speculative_decoding, **(eng_kw or {}))
        self.engine = self._stack.enter_context(engine)
        preface = ([{'role': 'system', 'content': sp}] if sp else []) + [_to_litert_msg(m) for m in listify(messages)]
        if sampler_config is None and any(x is not None for x in (temp, top_k, top_p, seed)):
            sampler_config = SamplerConfig(temperature=temp, top_k=top_k, top_p=top_p, seed=seed)
        cvk = dict(sampler_config=sampler_config, max_output_tokens=max_output_tokens, **(conv_kw or {}))
        if think: cvk['extra_context'] = {**cvk.get('extra_context', {}), 'enable_thinking': True}
        if filter_think: cvk['filter_channel_content_from_kv_cache'] = True
        self.conv = self._stack.enter_context(engine.create_conversation(messages=preface or None,
            tools=list(L(tools)) or None, tool_event_handler=ChatToolHandler(self), **cvk))
        self.ctx_limit = ctx_limit
        self._setup(model=model, sp=sp, messages=messages, tools=tools, approve=approve,
                    tool_max_len=tool_max_len, max_steps=max_steps, final_prompt=final_prompt,
                    cbs=cbs, default_cbs=default_cbs)

    @property
    def token_count(self): return self.conv.token_count
    def cancel(self):
        "Cancel the in-flight generation."
        self.conv.cancel_process()
    def count_tokens(self, text):
        "Number of tokens in `text` per the engine tokenizer."
        return len(self.engine.tokenize(text))
    def render(self, msg):
        "The exact templated string litert will send for `msg`."
        return self.conv.render_message_to_string(_mk_msg(msg))
    def _send(self, msg, max_output_tokens=None):
        'Send one message through the callback pipeline.'
        self.turn_msg, self._tc0 = _mk_msg(msg), self.conv.token_count
        for _ in run_cbs(self, 'before_send'): pass
        self.turn_res = Resp(self.conv.send_message(self.turn_msg, max_output_tokens=max_output_tokens))
        for _ in run_cbs(self, 'after_response'): pass
        return self.turn_res
    def _stream(self, msg, max_output_tokens=None, cbs=None):
        'Stream a turn as markdown chunks; per-call `cbs` live only for this turn.'
        added = self.add_cbs(cbs); prev = getattr(self, '_streaming', False); self._streaming = True
        try:
            self.turn_msg, self._tc0 = _mk_msg(msg), self.conv.token_count
            for _ in run_cbs(self, 'before_send'): pass
            fmt, chunks = StreamFormatter(), []
            for o in self.conv.send_message_async(self.turn_msg, max_output_tokens=max_output_tokens):
                chunks.append(o); yield fmt.format_item(o)
            self.turn_res = _merge_chunks(chunks)
            yield from run_cbs(self, 'after_response')
            return self.turn_res   # stream's final Resp, captured by SaveReturn / AsyncChat `.value`
        finally: self._streaming = prev; self.remove_cbs(added)
    def _oneshot(self, prompt, sp):
        "Stateless one-shot completion text via a throwaway conversation."
        with self.engine.create_conversation(messages=[{'role': 'system', 'content': sp}] if sp else None) as conv:
            return resp_text(conv.send_message(prompt))
    def _structured_call(self, prompt, schema, sp):
        "Forced tool call; falls back to parsing a JSON reply when the model answers in prose."
        pre = [{'role': 'system', 'content': sp}] if sp else None
        with self.engine.create_conversation(messages=pre, tools=[schema], automatic_tool_calling=False) as conv:
            r = conv.send_message(prompt)
        if tcs := r.get('tool_calls'): return tcs[0].get('function', {}).get('arguments', {})
        try: return json.loads(extract_fence(resp_text(r), 'json'))
        except (json.JSONDecodeError, TypeError) as e: raise ValueError(f"model neither called the tool nor returned JSON; reply: {resp_text(r)[:200]!r}") from e
    def close(self):
        "Release the conversation/engine (idempotent)."
        if getattr(self, '_stack', None) is not None: self._stack.close(); self._stack = None

# %% ../nbs/02_litert.ipynb #bea63711
def bench(model_id=gemma4_e2b, model_path=None, backend=Backend.CPU(), prefill_tokens=64, decode_tokens=64, **kw):
    "Benchmark init time, TTFT, and prefill/decode tokens-per-sec via litert's `Benchmark`."
    return Benchmark(_get_model(model_id, model_path), backend=backend, prefill_tokens=prefill_tokens, decode_tokens=decode_tokens, **kw).run()

