"""The same `Chat` API as `rishi.core`, over [llama-cpp-python](https://github.com/abetlen/llama-cpp-python) GGUF models - OpenAI-style message helpers, tool schemas via [toolslm](https://github.com/AnswerDotAI/toolslm), a Python-side tool loop with human-in-the-loop approval, `<think>` channel handling, sync/async streaming, and usage tracking.

Docs: https://vedicreader.github.io/rishi/llama.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_llama.ipynb.

# %% auto #0
__all__ = ['qwen3_06b', 'qwen3_17b', 'qwen3_4b', 'gemma3_1b', 'gemma3_4b', 'mk_content', 'mk_msg', 'mk_msgs', 'mk_tool',
           'split_think', 'parse_tool_tags', 'norm_resp', 'StreamSplit', 'UsageCallback', 'ToolReminderCallback',
           'get_model', 'Chat', 'AsyncChat', 'UsageStats', 'ChatCallback', 'run_cbs', 'resp_text', 'thought', 'Resp',
           'StreamFormatter', 'display_stream', 'mk_tr_details', 'truncated', 'hitl_policy', 'extract_fence']

# %% ../nbs/01_llama.ipynb #10a30d78
import json, re, os, uuid, asyncio
from base64 import b64encode
from llama_cpp import Llama
from toolslm.funccall import get_schema, mk_ns, call_func
from huggingface_hub import hf_hub_download, list_repo_files, scan_cache_dir
from fastcore.all import Path, store_attr, patch, L, GetAttr, ifnone, detect_mime, first, listify, AttrDict
from . import core
from .core import (UsageStats, ChatCallback, run_cbs, resp_text, thought, Resp, StreamFormatter,
                        display_stream, mk_tr_details, truncated, hitl_policy, extract_fence,
                        _matches, _qa_sp, _tool_reminder)

# %% ../nbs/01_llama.ipynb #3dcb0e40
_all_ = ['UsageStats', 'ChatCallback', 'run_cbs', 'resp_text', 'thought', 'Resp', 'StreamFormatter',
         'display_stream', 'mk_tr_details', 'truncated', 'hitl_policy', 'extract_fence']

# %% ../nbs/01_llama.ipynb #08664b43
def mk_content(o):
    'Convert `o` to an OpenAI-style content part (text, or a base64 `image_url` for image bytes/files).'
    if isinstance(o, dict): return o
    if isinstance(o, str): return {'type': 'text', 'text': o}
    if isinstance(o, os.PathLike): o = Path(o).read_bytes()
    if isinstance(o, bytes):
        mime = detect_mime(o) or 'application/octet-stream'
        if not mime.startswith('image/'): raise TypeError(f"llama.cpp chat supports only image attachments, got {mime}")
        return {'type': 'image_url', 'image_url': {'url': f"data:{mime};base64,{b64encode(o).decode()}"}}
    raise TypeError(f"Unsupported content type: {type(o)}")

def mk_msg(content, role='user'):
    'Create an OpenAI-style message dict from str/bytes/list/dict.'
    if content is None or isinstance(content, dict): return content
    parts = [mk_content(o) for o in content] if isinstance(content, list) else [mk_content(content)]
    if all(p.get('type') == 'text' for p in parts): return {'role': role, 'content': '\n'.join(p['text'] for p in parts)}
    return {'role': role, 'content': parts}

def mk_msgs(msgs):
    'Normalize a list of messages to OpenAI-style dicts.'
    return [mk_msg(m) for m in listify(msgs)] if msgs else []

# %% ../nbs/01_llama.ipynb #de644a6c
def mk_tool(f):
    'OpenAI/llama.cpp tool spec for callable `f` (via toolslm `get_schema`); spec dicts pass through.'
    if isinstance(f, dict): return f
    return {'type': 'function', 'function': get_schema(f, pname='parameters')}

# %% ../nbs/01_llama.ipynb #fa88990b
_think_re = re.compile(r'<think>(.*?)</think>', re.DOTALL)
_toolcall_re = re.compile(r'<tool_call>\s*(.*?)\s*</tool_call>', re.DOTALL)

def split_think(text):
    "Split `<think>...</think>` blocks out of `text`; returns `(clean_text, thought)`."
    text = text or ''
    ths = [m.strip() for m in _think_re.findall(text)]
    text = _think_re.sub('', text)
    if '<think>' in text:  # unterminated, e.g. cut off at the token cap
        text, _, rest = text.partition('<think>')
        ths.append(rest.strip())
    return text.strip('\n'), '\n'.join(th for th in ths if th)

def _mk_tag_tc(s):
    "Build a tool_call dict from the JSON inside a `<tool_call>` block, or None."
    try: d = json.loads(s)
    except (json.JSONDecodeError, TypeError): return None
    if not isinstance(d, dict) or 'name' not in d: return None
    return {'id': f"call_{uuid.uuid4().hex[:8]}", 'type': 'function',
            'function': {'name': d.get('name', ''), 'arguments': d.get('arguments') or {}}}

def parse_tool_tags(text):
    "Parse Hermes/Qwen-style `<tool_call>{json}</tool_call>` blocks; returns `(clean_text, tool_calls)`."
    tcs = [tc for m in _toolcall_re.findall(text or '') if (tc := _mk_tag_tc(m))]
    return _toolcall_re.sub('', text or '').strip('\n'), tcs

# %% ../nbs/01_llama.ipynb #af678dd6
def _parse_args(a):
    "Parse OpenAI JSON-string tool arguments to a dict (dicts pass through)."
    if isinstance(a, dict): return a
    try: return json.loads(a) if a else {}
    except json.JSONDecodeError: return {}

def norm_resp(r):
    "Normalize a llama.cpp chat completion to a rishi-style `Resp` dict."
    ch = r['choices'][0]
    m = ch.get('message') or {}
    text, th = split_think(m.get('content') or '')
    text, tag_tcs = parse_tool_tags(text)
    tcs = [{'id': tc.get('id'), 'type': 'function',
            'function': {'name': tc.get('function', {}).get('name', ''),
                         'arguments': _parse_args(tc.get('function', {}).get('arguments'))}}
           for tc in (m.get('tool_calls') or [])] + tag_tcs
    res = {'role': 'assistant', 'content': text}
    if th: res['channels'] = {'thought': th}
    if tcs: res['tool_calls'] = tcs
    if ch.get('finish_reason') == 'length': res['truncated'] = True
    if 'usage' in r: res['usage'] = dict(r['usage'])
    return Resp(res)

def _oai_msg(m):
    "Project a history entry to what llama.cpp expects: drop rishi-only keys, re-encode tool-call args as JSON."
    out = {k: m[k] for k in ('role', 'content', 'tool_calls', 'tool_call_id', 'name') if m.get(k) is not None}
    if 'tool_calls' in out:
        out['tool_calls'] = [{'id': tc.get('id') or f'call_{i}', 'type': 'function',
                              'function': {'name': tc['function'].get('name', ''),
                                           'arguments': a if isinstance((a := tc['function'].get('arguments')), str)
                                                        else json.dumps(a or {})}}
                             for i, tc in enumerate(out['tool_calls'])]
        out.setdefault('content', '')
    return out

def _sum_usage(us):
    "Sum OpenAI usage dicts (ignoring Nones); None if nothing to sum."
    us = [u for u in us if u]
    if not us: return None
    return {k: sum(u.get(k, 0) for u in us) for k in ('prompt_tokens', 'completion_tokens', 'total_tokens')}

# %% ../nbs/01_llama.ipynb #c4059899
_tags = ('<think>', '</think>', '<tool_call>', '</tool_call>')

class StreamSplit:
    "Stateful splitter for streamed text: `<think>` -> thought chunks, `<tool_call>` blocks held back and parsed."
    def __init__(self):
        self.buf, self.state, self.text, self.thought, self.tool_calls, self._tc_buf, self._strip = '', 'text', '', '', [], '', False
    def _held(self):
        "Length of the longest `buf` suffix that could still become a tag."
        for n in range(min(len(self.buf), max(map(len, _tags)) - 1), 0, -1):
            if any(t.startswith(self.buf[-n:]) for t in _tags): return n
        return 0
    def _emit_text(self, out):
        if self._strip: out = out.lstrip('\n')
        if not out: return None
        self._strip = False; self.text += out
        return {'content': [{'type': 'text', 'text': out}]}
    def feed(self, s):
        "Consume a text delta; yield litert-style chunk dicts."
        self.buf += s
        while True:
            if self.state == 'text':
                cands = [(k, t, st) for k, t, st in ((self.buf.find('<think>'), '<think>', 'think'),
                                                     (self.buf.find('<tool_call>'), '<tool_call>', 'tool')) if k >= 0]
                if not cands:
                    n = self._held()
                    out, self.buf = self.buf[:len(self.buf) - n], self.buf[len(self.buf) - n:]
                    if (c := self._emit_text(out)): yield c
                    return
                k, tag, st = min(cands)
                out, self.buf, self.state = self.buf[:k], self.buf[k + len(tag):], st
                if (c := self._emit_text(out)): yield c
            elif self.state == 'think':
                k = self.buf.find('</think>')
                if k < 0:
                    n = self._held()
                    out, self.buf = self.buf[:len(self.buf) - n], self.buf[len(self.buf) - n:]
                    if out: self.thought += out; yield {'channels': {'thought': out}}
                    return
                out, self.buf, self.state, self._strip = self.buf[:k], self.buf[k + len('</think>'):], 'text', True
                if out: self.thought += out; yield {'channels': {'thought': out}}
            else:  # tool
                k = self.buf.find('</tool_call>')
                if k < 0:
                    n = self._held()
                    self._tc_buf += self.buf[:len(self.buf) - n]; self.buf = self.buf[len(self.buf) - n:]
                    return
                self._tc_buf += self.buf[:k]
                self.buf, self.state, self._strip = self.buf[k + len('</tool_call>'):], 'text', True
                if (tc := _mk_tag_tc(self._tc_buf)): self.tool_calls.append(tc)
                self._tc_buf = ''
    def finish(self):
        "Flush leftovers: unterminated think becomes thought; an unclosed tool block is parsed if possible."
        s, self.buf = self.buf, ''
        if self.state == 'think':
            if s: self.thought += s; yield {'channels': {'thought': s}}
        elif self.state == 'tool':
            if (tc := _mk_tag_tc(self._tc_buf + s)): self.tool_calls.append(tc)
            self._tc_buf = ''
        elif (c := self._emit_text(s)): yield c

def _acc_tc(acc, deltas):
    "Fold streamed OpenAI `tool_calls` deltas into `acc` (a list of partial tool_call dicts)."
    for d in deltas or []:
        i = d.get('index', 0)
        while len(acc) <= i: acc.append({'id': None, 'type': 'function', 'function': {'name': '', 'arguments': ''}})
        if d.get('id'): acc[i]['id'] = d['id']
        f = d.get('function') or {}
        if f.get('name'): acc[i]['function']['name'] += f['name']
        if f.get('arguments'): acc[i]['function']['arguments'] += f['arguments']

# %% ../nbs/01_llama.ipynb #ecdd4161
class UsageCallback(ChatCallback):
    "Fold each turn's `usage` block (summed across tool rounds) into `chat.use`."
    order = 10
    def after_response(self):
        u = self.chat.turn_res.get('usage') or {}
        self.chat.use += UsageStats(u.get('prompt_tokens', 0), u.get('completion_tokens', 0), u.get('total_tokens', 0), 1)

class ToolReminderCallback(ChatCallback):
    'Inject a tool-summary reminder into the outgoing message when tools are registered.'
    order = 30
    def __init__(self, tool_reminder=_tool_reminder): store_attr()
    def before_send(self):
        m = self.chat.turn_msg
        if not self.chat.tools or m is None: return
        if isinstance(m.get('content'), str): m['content'] += self.tool_reminder
        elif isinstance(m.get('content'), list): m['content'].append({'type': 'text', 'text': self.tool_reminder})

# %% ../nbs/01_llama.ipynb #84426f78
qwen3_06b = 'Qwen/Qwen3-0.6B-GGUF'
qwen3_17b = 'Qwen/Qwen3-1.7B-GGUF'
qwen3_4b  = 'Qwen/Qwen3-4B-GGUF'
gemma3_1b = 'ggml-org/gemma-3-1b-it-GGUF'
gemma3_4b = 'ggml-org/gemma-3-4b-it-GGUF'

def _gguf(fs, quant='Q4_K_M'):
    "First `.gguf` path in `fs` matching `quant` (case-insensitive), else the first one (skips `mmproj` files)."
    ggufs = L(fs).filter(lambda p: p.lower().endswith('.gguf') and 'mmproj' not in p.lower())
    return first(ggufs, lambda p: quant.lower() in p.lower()) or first(ggufs)

def _cached_model(model_id, quant='Q4_K_M'):
    "Local `.gguf` path from the HF cache without hitting the network, else None."
    try: repo = first(scan_cache_dir().repos, lambda r: r.repo_id == model_id)
    except Exception: return None
    return _gguf([str(f.file_path) for r in repo.revisions for f in r.files], quant) if repo else None

def get_model(model_id, model_path=None, quant='Q4_K_M'):
    "Return a local `.gguf` path: `model_path`, else HF cache, else download."
    if model_path and Path(model_path).exists(): return str(model_path)
    if (hit := _cached_model(model_id, quant)): return hit
    if not (fn := _gguf(list_repo_files(model_id), quant)): raise FileNotFoundError(f"No .gguf file found for {model_id}")
    return hf_hub_download(model_id, fn)

# %% ../nbs/01_llama.ipynb #62bf39bf
_dflt_cbs = [UsageCallback, ToolReminderCallback]

class Chat:
    "Sync chat over a local llama.cpp model - the `rishi.core.Chat` API with a Python-side tool loop."
    @classmethod
    def create_engine(cls, model_id=qwen3_17b, model_path=None, quant='Q4_K_M', n_ctx=8192,
                      n_gpu_layers=0, verbose=False, **kw):
        'Build a `llama_cpp.Llama`. Override/`@patch` to customize.'
        return Llama(get_model(model_id, model_path, quant), n_ctx=n_ctx, n_gpu_layers=n_gpu_layers, verbose=verbose, **kw)

    def __init__(self,
        engine:Llama=None, # llama_cpp.Llama, or None to build one
        model_id:str=qwen3_17b, # huggingface GGUF repo id
        model_path:os.PathLike=None, # local .gguf model path
        quant:str='Q4_K_M', # preferred quant when picking a .gguf from the repo
        n_ctx:int=8192, # context window for the engine
        n_gpu_layers:int=0, # layers to offload to GPU (-1 = all)
        eng_kw=None, # extra llama_cpp.Llama kwargs
        sp='', # system prompt
        messages=None, # message history to prefill the conversation
        tools=None, # tools: python callables or OpenAI tool-spec dicts
        ctx_limit=None, # context window for pct_full (defaults to the engine's n_ctx)
        approve=None, # approval function for tool calls
        tool_max_len=None, # truncate string tool results longer than this (protects context)
        max_steps=10, # max tool-call rounds per turn
        think=None, # True/False appends '/think' or '/no_think' to the system prompt (Qwen-style soft switch)
        temp=None, top_k=None, top_p=None, seed=None, # sampler knobs
        max_output_tokens=None,
        comp_kw=None, # extra create_chat_completion kwargs
        cbs=None, # callbacks to register
        default_cbs=True # add default callbacks (UsageCallback, ToolReminderCallback)
    ):
        self._own_engine = engine is None
        if engine is None:
            engine = self.create_engine(model_id, model_path, quant, n_ctx=n_ctx, n_gpu_layers=n_gpu_layers, **(eng_kw or {}))
        self.engine = engine
        self.tools = L(tools)
        self.toolspecs = [mk_tool(t) for t in self.tools]
        self.ns = mk_ns([t for t in self.tools if callable(t)])
        self.hist = mk_msgs(messages)
        self._samp = {k: v for k, v in dict(temperature=temp, top_k=top_k, top_p=top_p, seed=seed).items() if v is not None}
        store_attr('sp,approve,tool_max_len,max_steps,think,max_output_tokens')
        self.ctx_limit, self.comp_kw = ifnone(ctx_limit, engine.n_ctx()), comp_kw or {}
        self.use, self.cbs, self.turn_msg, self.turn_res, self._ctx_tokens = UsageStats(), L(), None, None, 0
        if default_cbs: self.add_cbs(_dflt_cbs)
        self.add_cbs(cbs)

    add_cb, add_cbs, remove_cb, remove_cbs, print_hist = (
        core.Chat.add_cb, core.Chat.add_cbs, core.Chat.remove_cb, core.Chat.remove_cbs, core.Chat.print_hist)

    def close(self):
        "Release the engine (only if this Chat created it); idempotent."
        if self._own_engine and getattr(self, 'engine', None) is not None:
            if (c := getattr(self.engine, 'close', None)): c()
            self.engine = None
    def __del__(self):
        try: self.close()
        except Exception: pass

    @property
    def token_count(self):
        "Tokens in the model context after the last turn (prompt + completion)."
        return self._ctx_tokens
    @property
    def pct_full(self): return self.token_count / self.ctx_limit
    def count_tokens(self, text):
        "Number of tokens in `text` per the engine tokenizer."
        return len(self.engine.tokenize(text.encode('utf-8'), add_bos=False, special=True))

    def _sys_msgs(self):
        sp = self.sp or ''
        if self.think is not None: sp = f"{sp}\n{'/think' if self.think else '/no_think'}".strip()
        return [{'role': 'system', 'content': sp}] if sp else []

    def _msgs(self): return self._sys_msgs() + [_oai_msg(m) for m in self.hist]

    def _step(self, max_output_tokens=None, stream=False):
        return self.engine.create_chat_completion(self._msgs(), tools=self.toolspecs or None, stream=stream,
            max_tokens=ifnone(max_output_tokens, self.max_output_tokens), **self._samp, **self.comp_kw)

    def _run_tools(self, res):
        "Record `res` in `hist`, then execute its tool calls (with approval), appending the results."
        self.hist.append(res)
        for tc in res.get('tool_calls') or []:
            self.turn_tc = tc
            for _ in run_cbs(self, 'before_tool_calls'): pass
            if self.approve is None or self.approve(tc):
                try: out = call_func(tc['function']['name'], tc['function']['arguments'], ns=self.ns)
                except Exception as e: out = f"{type(e).__name__}: {e}"
            else: out = 'Denied by human operator'
            if self.tool_max_len and isinstance(out, str) and len(out) > self.tool_max_len:
                out = out[:self.tool_max_len] + ' ...[truncated]'
            self.turn_tool_result = out
            self.hist.append({'role': 'tool', 'tool_call_id': tc.get('id'), 'name': tc['function'].get('name', ''),
                              'content': str(out)})
            for _ in run_cbs(self, 'after_tool_calls'): pass

    def _send(self, msg, max_output_tokens=None):
        'Send one message through the callback pipeline, running the tool loop up to `max_steps` rounds.'
        self.turn_msg = mk_msg(msg)
        for _ in run_cbs(self, 'before_send'): pass
        if self.turn_msg is not None: self.hist.append(self.turn_msg)
        us, steps = [], 0
        while True:
            res = norm_resp(self._step(max_output_tokens))
            us.append(res.get('usage'))
            if not res.get('tool_calls') or steps >= self.max_steps: break
            self._run_tools(res); steps += 1
        if (u := _sum_usage(us)): res['usage'] = u
        self._ctx_tokens = (us[-1] or {}).get('total_tokens', self._ctx_tokens)
        self.turn_res = res
        self.hist.append(res)
        for _ in run_cbs(self, 'after_response'): pass
        return self.turn_res

    def _stream_step(self, max_output_tokens=None):
        "Stream one completion; yields chunk dicts and leaves the merged `Resp` on `self._step_res`."
        split, tcs, fin = StreamSplit(), [], None
        for r in self._step(max_output_tokens, stream=True):
            ch = r['choices'][0]
            fin = ch.get('finish_reason') or fin
            d = ch.get('delta') or {}
            _acc_tc(tcs, d.get('tool_calls'))
            yield from split.feed(d.get('content') or '')
        yield from split.finish()
        tcs = [{'id': tc['id'] or f'call_{i}', 'type': 'function',
                'function': {'name': tc['function']['name'], 'arguments': _parse_args(tc['function']['arguments'])}}
               for i, tc in enumerate(tcs)] + split.tool_calls
        res = {'role': 'assistant', 'content': split.text}
        if split.thought: res['channels'] = {'thought': split.thought}
        if tcs: res['tool_calls'] = tcs
        if fin == 'length': res['truncated'] = True
        out = self.count_tokens(split.text + split.thought) if (split.text or split.thought) else 0
        n = self.engine.n_tokens
        res['usage'] = {'prompt_tokens': max(n - out, 0), 'completion_tokens': out, 'total_tokens': n}
        self._step_res = Resp(res)

    def _stream(self, msg, max_output_tokens=None, cbs=None):
        'Stream a turn as markdown chunks; per-call `cbs` live only for this turn.'
        added = self.add_cbs(cbs)
        try:
            self.turn_msg = mk_msg(msg)
            for _ in run_cbs(self, 'before_send'): pass
            if self.turn_msg is not None: self.hist.append(self.turn_msg)
            fmt, us, steps = StreamFormatter(), [], 0
            while True:
                for o in self._stream_step(max_output_tokens):
                    if (s := fmt.format_item(o)): yield s
                if fmt._inthink: fmt._inthink = False; yield '\n\n'
                res = self._step_res
                us.append(res.get('usage'))
                if not res.get('tool_calls') or steps >= self.max_steps: break
                for tc in res['tool_calls']:
                    yield fmt.format_item({'content': [{'type': 'tool_call', 'name': tc['function'].get('name', ''),
                                                        'arguments': tc['function'].get('arguments', {})}]})
                self._run_tools(res); steps += 1
            if (u := _sum_usage(us)): res['usage'] = u
            self._ctx_tokens = (us[-1] or {}).get('total_tokens', self._ctx_tokens)
            self.turn_res = res
            self.hist.append(res)
            for _ in run_cbs(self, 'after_response'): pass
        finally: self.remove_cbs(added)

    def __call__(self, msg:list|str|dict|bytes|os.PathLike=None, stream=False, max_output_tokens=None,
                 cbs=None # extra callbacks for this turn only (added before, removed after)
    ):
        'Run one chat turn; returns a `Resp` dict (or a markdown-chunk generator when `stream=True`).'
        self.use = UsageStats()
        if stream: return self._stream(msg, max_output_tokens, cbs)
        added = self.add_cbs(cbs)
        try: return self._send(msg, max_output_tokens)
        finally: self.remove_cbs(added)

# %% ../nbs/01_llama.ipynb #038660da
@patch
def classify(self:Chat, text, labels, sp='Reply with only the single best label and nothing else.'):
    "One-shot label for `text`, run stateless on this chat's engine (isolated from the conversation)."
    p = f"{text}\n\nChoose exactly one label from: {', '.join(labels)}."
    msgs = ([{'role': 'system', 'content': sp}] if sp else []) + [{'role': 'user', 'content': p}]
    out = resp_text(norm_resp(self.engine.create_chat_completion(msgs, **self._samp))).lower()
    return first(labels, lambda l: l.lower() in out) or out.strip()

@patch
def structured(self:Chat, prompt, schema, sp='Call the tool to answer.'):
    "One-shot structured output via a forced (grammar-constrained) tool call; returns `schema(**arguments)`."
    spec = mk_tool(schema)
    nm = spec['function']['name']
    msgs = ([{'role': 'system', 'content': sp}] if sp else []) + [{'role': 'user', 'content': prompt}]
    r = norm_resp(self.engine.create_chat_completion(msgs, tools=[spec],
            tool_choice={'type': 'function', 'function': {'name': nm}}, **self._samp))
    if not (tcs := r.get('tool_calls')): raise ValueError(f"model did not call the tool; reply: {resp_text(r)[:200]!r}")
    return schema(**tcs[0]['function']['arguments'])

@patch
def check(self:Chat, question, expected, grade_fn=_matches, llm_judge=False, judge=None, tag='answer', sp=_qa_sp):
    'Ask `question` stateless, extract the ```<tag> answer, and grade it against `expected`.'
    msgs = ([{'role': 'system', 'content': sp}] if sp else []) + [{'role': 'user', 'content': question}]
    a = extract_fence(resp_text(norm_resp(self.engine.create_chat_completion(msgs, **self._samp))), tag)
    ok = (judge or self).grades(question, expected, a) if (llm_judge or judge) else grade_fn(a, expected)
    return AttrDict(question=question, expected=expected, answer=a, ok=ok)

Chat.run_py, Chat.grades = core.Chat.run_py, core.Chat.grades

# %% ../nbs/01_llama.ipynb #79aae1e1
class AsyncChat(GetAttr):
    "Async facade over `Chat`: same API; blocking llama.cpp calls run in a worker thread."
    _default = 'chat'
    def __init__(self, *args, **kwargs):
        self.chat = args[0] if args and isinstance(args[0], Chat) else Chat(*args, **kwargs)
    async def __call__(self, msg=None, stream=False, max_output_tokens=None,
                       cbs=None # extra callbacks for this turn only
    ):
        'Run one chat turn; `await` the result (an async chunk generator when `stream=True`).'
        if stream: return self._astream(msg, max_output_tokens, cbs)
        return await asyncio.to_thread(self.chat, msg, False, max_output_tokens, cbs)
    async def _astream(self, msg, max_output_tokens=None, cbs=None):
        g = self.chat(msg, stream=True, max_output_tokens=max_output_tokens, cbs=cbs)
        done = object()
        while (o := await asyncio.to_thread(next, g, done)) is not done: yield o
    def close(self): self.chat.close()
    async def __aenter__(self): return self
    async def __aexit__(self, *exc): self.close()
