"""The same `Chat` API as `rishi.core`, over [llama-cpp-python](https://github.com/abetlen/llama-cpp-python) GGUF models - OpenAI-style message helpers, tool schemas via [toolslm](https://github.com/AnswerDotAI/toolslm), a Python-side tool loop with human-in-the-loop approval, `<think>` channel handling, sync/async streaming, and usage tracking.

Docs: https://vedicreader.github.io/rishi/llama.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_llama.ipynb.

# %% auto #0
__all__ = ['qwen3_06b', 'qwen3_17b', 'qwen3_4b', 'gemma3_1b', 'gemma3_4b', 'qwen3_6_fusion', 'ornith_9b', 'ornith_31b',
           'get_mmproj', 'gpu_offload_supported', 'read_audio', 'LlamaChat', 'UsageStats', 'ChatCallback', 'run_cbs',
           'resp_text', 'thought', 'Resp', 'StreamFormatter', 'display_stream', 'mk_tr_details', 'truncated',
           'hitl_policy', 'extract_fence', 'mk_toolspec', 'split_think', 'parse_tool_tags', 'norm_resp', 'StreamSplit']

# %% ../nbs/01_llama.ipynb #10a30d78
import json, re, os, io, uuid, ctypes, asyncio
import numpy as np
from base64 import b64encode
from dataclasses import is_dataclass, dataclass
from typing import get_type_hints
from llama_cpp import Llama
from huggingface_hub import hf_hub_download, list_repo_files, scan_cache_dir
from fastcore.all import Path, store_attr, patch, L, GetAttr, ifnone, detect_mime, first, listify, AttrDict
from . import core
from .core import *

# %% ../nbs/01_llama.ipynb #3dcb0e40
# names that used to live here and now come from `rishi.core`; re-exported so `from rishi.llama import *`
# (and any code that imported them from here) keeps working unchanged
_all_ = ['UsageStats', 'ChatCallback', 'run_cbs', 'resp_text', 'thought', 'Resp', 'StreamFormatter',
         'display_stream', 'mk_tr_details', 'truncated', 'hitl_policy', 'extract_fence',
         'mk_toolspec', 'split_think', 'parse_tool_tags', 'norm_resp', 'StreamSplit']

# private aliases: the shared helpers kept their old llama-side names so existing call sites still resolve
_mk_content, _mk_msg, _mk_msgs = mk_oai_content, mk_oai_msg, mk_oai_msgs
_oai_msg, _sum_usage, _strip_media, _is_media = to_oai_msg, sum_usage, strip_media, is_media
_parse_args, _mk_tag_tc, _acc_tc = parse_args, mk_tag_tc, acc_tc
_UsageCallback, _ToolReminderCallback = UsageCallback, ToolReminderCallback

# %% ../nbs/01_llama.ipynb #84426f78
qwen3_06b = 'Qwen/Qwen3-0.6B-GGUF'
qwen3_17b = 'Qwen/Qwen3-1.7B-GGUF'
qwen3_4b  = 'Qwen/Qwen3-4B-GGUF'
gemma3_1b = 'ggml-org/gemma-3-1b-it-GGUF'
gemma3_4b = 'ggml-org/gemma-3-4b-it-GGUF'
qwen3_6_fusion = 'Jackrong/Qwopus3.6-27B-Fusion-GGUF'
ornith_9b = 'unsloth/Ornith-1.0-9B-GGUF'
ornith_31b = 'unsloth/Ornith-1.0-35B-GGUF'

def _gguf(fs, quant='Q4_K_M'):
    "First `.gguf` path in `fs` matching `quant` (case-insensitive), else the first one (skips `mmproj` files)."
    ggufs = L(fs).filter(lambda p: p.lower().endswith('.gguf') and 'mmproj' not in p.lower())
    return first(ggufs, lambda p: quant.lower() in p.lower()) or first(ggufs)

def _cached_model(model_id, quant='Q4_K_M'):
    "Local `.gguf` path from the HF cache without hitting the network, else None."
    try: repo = first(scan_cache_dir().repos, lambda r: r.repo_id == model_id)
    except Exception: return None
    return _gguf([str(f.file_path) for r in repo.revisions for f in r.files], quant) if repo else None

def _get_model(model_id, model_path=None, quant='Q4_K_M'):
    "Return a local `.gguf` path: `model_path`, else HF cache, else download."
    if model_path and Path(model_path).exists(): return str(model_path)
    if (hit := _cached_model(model_id, quant)): return hit
    if not (fn := _gguf(list_repo_files(model_id), quant)): raise FileNotFoundError(f"No .gguf file found for {model_id}")
    return hf_hub_download(model_id, fn)

def _mmproj(fs):
    "First `mmproj` projector `.gguf` path in `fs` (the image encoder that sits beside the model)."
    return first(L(fs).filter(lambda p: p.lower().endswith('.gguf') and 'mmproj' in Path(p).name.lower()))

def _cached_mmproj(model_id):
    "Local `mmproj` path from the HF cache without hitting the network, else None."
    try: repo = first(scan_cache_dir().repos, lambda r: r.repo_id == model_id)
    except Exception: return None
    return _mmproj([str(f.file_path) for r in repo.revisions for f in r.files]) if repo else None

def get_mmproj(model_id, mmproj_path=None):
    "Return a local `mmproj` projector path: `mmproj_path`, else HF cache, else download."
    if mmproj_path and Path(mmproj_path).exists(): return str(mmproj_path)
    if (hit := _cached_mmproj(model_id)): return hit
    if not (fn := _mmproj(list_repo_files(model_id))): raise FileNotFoundError(f"No mmproj .gguf found for {model_id}")
    return hf_hub_download(model_id, fn)

# %% ../nbs/01_llama.ipynb #a1metal01
from llama_cpp import llama_supports_gpu_offload

def gpu_offload_supported():
    "True if the installed llama-cpp-python build has GPU (Metal/CUDA) offload compiled in."
    return bool(llama_supports_gpu_offload())

# %% ../nbs/01_llama.ipynb #572c1617
import soundfile as sf
from llama_cpp.llama_chat_format import MTMDChatHandler

def _resample(a, src, dst):
    "Linear-interpolation resample of mono float32 `a` from `src` Hz to `dst` Hz."
    if src == dst or not len(a): return a
    return np.interp(np.linspace(0, len(a) - 1, round(len(a) * dst / src)), np.arange(len(a)), a).astype(np.float32)

def read_audio(o, sr=16000):
    "Decode audio `bytes`/`Path` (any libsndfile format) to contiguous mono float32 samples at `sr` Hz, ready for mtmd."
    if isinstance(o, os.PathLike): o = Path(o).read_bytes()
    try: a, src = sf.read(io.BytesIO(o), dtype='float32', always_2d=False)
    except sf.LibsndfileError as e: raise ValueError(f"could not decode audio ({detect_mime(o)}): {e}") from None
    if a.ndim > 1: a = a.mean(axis=1)   # downmix to mono
    return np.ascontiguousarray(_resample(a, src, sr), dtype=np.float32)

# %% ../nbs/01_llama.ipynb #8da9504d
# capture the originals once, so re-importing this module can never chain a patch onto itself
if not hasattr(MTMDChatHandler, '_rishi_orig'):
    MTMDChatHandler._rishi_orig = {'init': MTMDChatHandler._init_mtmd_context,
                                   'bitmap': MTMDChatHandler._create_bitmap_from_bytes}
_orig_init, _orig_bitmap = MTMDChatHandler._rishi_orig['init'], MTMDChatHandler._rishi_orig['bitmap']

@patch
def _init_mtmd_context(self:MTMDChatHandler, llama_model):
    "As upstream, but accept an audio-only projector instead of hard-failing on the missing vision encoder."
    try: return _orig_init(self, llama_model)
    except ValueError:
        # upstream builds the ctx, then raises before registering cleanup when vision is unsupported; the
        # recoverable case is uniquely "ctx built + audio supported" - gate on that, not on the message text
        if self.mtmd_ctx is None or not self._mtmd_cpp.mtmd_support_audio(self.mtmd_ctx): raise
        def _free():   # upstream registers this only on the success path
            if self.mtmd_ctx is not None: self._mtmd_cpp.mtmd_free(self.mtmd_ctx); self.mtmd_ctx = None
        self._exit_stack.callback(_free)

@patch
def get_image_urls(self:MTMDChatHandler, messages):
    "Media data-URIs in document order - audio as well as images (upstream collects images only)."
    urls = []
    for m in messages:
        for p in (m.get('content') if isinstance(m.get('content'), list) else []):
            if not isinstance(p, dict): continue
            if p.get('type') == 'image_url':
                u = p['image_url']; urls.append(u['url'] if isinstance(u, dict) else u)
            elif p.get('type') == 'input_audio':
                a = p.get('input_audio') or {}
                urls.append(f"data:audio/{a.get('format', 'wav')};base64,{a.get('data', '')}")
    return urls

@patch
def _get_template_messages(self:MTMDChatHandler, messages, media_marker):
    "Swap media parts for the marker, then collapse an all-text content list to a string; templates that render `content` directly (Llama/Voxtral-style) would otherwise emit the list's Python repr."
    def _conv(m):
        c = m.get('content')
        if not isinstance(c, list): return dict(m)
        parts = [{'type': 'text', 'text': media_marker} if _is_media(p) else p for p in c]
        if all(isinstance(p, dict) and p.get('type') == 'text' for p in parts):
            return {**m, 'content': '\n'.join(p['text'] for p in parts)}
        return {**m, 'content': parts}
    return [_conv(m) for m in messages]

@patch
def _create_bitmap_from_bytes(self:MTMDChatHandler, image_bytes):
    "Audio bytes become an mtmd audio bitmap; anything else takes the original image path untouched."
    if not (detect_mime(image_bytes) or '').startswith('audio/'): return _orig_bitmap(self, image_bytes)
    sr = self._mtmd_cpp.mtmd_get_audio_sample_rate(self.mtmd_ctx)
    a = read_audio(image_bytes, sr if sr and sr > 0 else 16000)
    bm = self._mtmd_cpp.mtmd_bitmap_init_from_audio(len(a), a.ctypes.data_as(ctypes.POINTER(ctypes.c_float)))
    if bm is None: raise ValueError('Failed to create bitmap from audio samples')
    return bm

# %% ../nbs/01_llama.ipynb #62bf39bf
class LlamaChat(Chat):
    "Sync chat over a local llama.cpp model - the `rishi.core.Chat` API with a Python-side tool loop."
    _runtime = 'llama'
    _dflt_cbs = [_UsageCallback, _ToolReminderCallback]
    mk_content, mk_msg, mk_msgs = staticmethod(_mk_content), staticmethod(_mk_msg), staticmethod(_mk_msgs)

    @staticmethod
    def fmt2hist(msgs):
        "llama's messages are already canonical; just normalize to rishi history dicts."
        return _mk_msgs(msgs)
    @staticmethod
    def hist2fmt(msgs):
        "Canonical rishi history dicts -> OpenAI-style messages for llama.cpp (past-turn media -> placeholder)."
        return [_oai_msg(_strip_media(m)) for m in listify(msgs)]

    @classmethod
    def create_engine(cls, model_id=qwen3_06b, model_path=None, quant='Q4_K_M', n_ctx=8192,
                      n_gpu_layers=0, mmproj=None, verbose=False, **kw):
        'Build a `llama_cpp.Llama`; `mmproj` adds the projector needed for image/audio input. Override/`@patch` to customize.'
        ch = None
        if mmproj:
            from llama_cpp.llama_chat_format import MTMDChatHandler
            ch = MTMDChatHandler(get_mmproj(model_id, None if mmproj is True else mmproj), verbose=verbose)
        return Llama(_get_model(model_id, model_path, quant), n_ctx=n_ctx, n_gpu_layers=n_gpu_layers,
                     chat_handler=ch, verbose=verbose, **kw)

    def __init__(self, model=None, *, runtime=None, model_path=None, engine=None,
                 quant='Q4_K_M', n_ctx=8192, n_gpu_layers=0, mmproj=None, eng_kw=None,
                 sp='', messages=None, tools=None, ctx_limit=None, approve=None, tool_max_len=None,
                 max_steps=10, think=None, temp=None, top_k=None, top_p=None, seed=None,
                 max_output_tokens=None, comp_kw=None, cbs=None, default_cbs=True):
        model = core.split_runtime(model)[1]
        model_id = None if model is None or core._is_path(model) else model
        model_path = model_path or (model if model and core._is_path(model) else None)
        self._own_engine = engine is None
        if engine is None:
            engine = self.create_engine(model_id or qwen3_17b, model_path, quant, n_ctx=n_ctx,
                                        n_gpu_layers=n_gpu_layers, mmproj=mmproj, **(eng_kw or {}))
        self.engine = engine
        self.toolspecs = [mk_toolspec(t) for t in L(tools)]
        self.ns = mk_ns([t for t in L(tools) if callable(t)])
        self._samp = {k:v for k,v in dict(temperature=temp, top_k=top_k, top_p=top_p, seed=seed).items() if v is not None}
        store_attr('think,max_output_tokens', self)
        self.ctx_limit, self.comp_kw, self._ctx_tokens = ifnone(ctx_limit, engine.n_ctx()), comp_kw or {}, 0
        self._setup(model=model, sp=sp, messages=messages, tools=tools, approve=approve,
                    tool_max_len=tool_max_len, max_steps=max_steps, cbs=cbs, default_cbs=default_cbs)

    def close(self):
        "Release the engine (only if this Chat created it); idempotent."
        if self._own_engine and getattr(self, 'engine', None) is not None:
            if (c := getattr(self.engine, 'close', None)): c()
            self.engine = None

    @property
    def token_count(self):
        "Tokens in the model context after the last turn (prompt + completion)."
        return self._ctx_tokens
    def count_tokens(self, text):
        "Number of tokens in `text` per the engine tokenizer."
        return len(self.engine.tokenize(text.encode('utf-8'), add_bos=False, special=True))

    def _sys_msgs(self):
        sp = self.sp or ''
        if self.think is not None: sp = f"{sp}\n{'/think' if self.think else '/no_think'}".strip()
        return [{'role': 'system', 'content': sp}] if sp else []

    def _msgs(self):
        "OpenAI-style messages; media in earlier turns is stripped to a placeholder so only the live turn is re-encoded (llama.cpp re-tokenizes the whole list each call)."
        return self._sys_msgs() + [_oai_msg(m if m is self.turn_msg else _strip_media(m)) for m in self.hist]

    def _step(self, max_output_tokens=None, stream=False):
        return self.engine.create_chat_completion(self._msgs(), tools=self.toolspecs or None, stream=stream,
            max_tokens=ifnone(max_output_tokens, self.max_output_tokens), **self._samp, **self.comp_kw)

    def _run_tools(self, res):
        "Record `res` in `hist`, then execute its tool calls (with approval), appending the results."
        self.hist.append(res)
        for tc in res.get('tool_calls') or []:
            self.turn_tc = tc
            for _ in run_cbs(self, 'before_tool_calls'): pass
            if self.approve is None or self.approve(tc):
                try: out = call_func(tc['function']['name'], tc['function']['arguments'], ns=self.ns)
                except Exception as e: out = f"{type(e).__name__}: {e}"
            else: out = 'Denied by human operator'
            if self.tool_max_len and isinstance(out, str) and len(out) > self.tool_max_len:
                out = out[:self.tool_max_len] + ' ...[truncated]'
            self.turn_tool_result = out
            self.hist.append({'role': 'tool', 'tool_call_id': tc.get('id'), 'name': tc['function'].get('name', ''),
                              'content': str(out)})
            for _ in run_cbs(self, 'after_tool_calls'): pass

    def _oneshot(self, prompt, sp):
        "Stateless one-shot completion text."
        msgs = ([{'role':'system','content':sp}] if sp else []) + [{'role':'user','content':prompt}]
        return resp_text(norm_resp(self.engine.create_chat_completion(msgs, **self._samp)))
    def _structured_call(self, prompt, schema, sp):
        "Grammar-constrained JSON reply; returns the decoded argument dict."
        rf = {'type':'json_object','schema': get_schema(schema)['input_schema']}
        msgs = ([{'role':'system','content':sp}] if sp else []) + [{'role':'user','content':prompt}]
        return json.loads(resp_text(norm_resp(self.engine.create_chat_completion(msgs, response_format=rf, **self._samp))))
    def _send(self, msg, max_output_tokens=None):
        'Send one message through the callback pipeline, running the tool loop up to `max_steps` rounds.'
        self.turn_msg = _mk_msg(msg)
        for _ in run_cbs(self, 'before_send'): pass
        if self.turn_msg is not None: self.hist.append(self.turn_msg)
        us, steps = [], 0
        while True:
            res = norm_resp(self._step(max_output_tokens))
            us.append(res.get('usage'))
            if not res.get('tool_calls') or steps >= self.max_steps: break
            self._run_tools(res); steps += 1
        if (u := _sum_usage(us)): res['usage'] = u
        self._ctx_tokens = (us[-1] or {}).get('total_tokens', self._ctx_tokens)
        self.turn_res = res
        self.hist.append(res)
        for _ in run_cbs(self, 'after_response'): pass
        return self.turn_res

    def _stream_step(self, max_output_tokens=None):
        "Stream one completion; yields chunk dicts and leaves the merged `Resp` on `self._step_res`."
        split, tcs, fin = StreamSplit(), [], None
        for r in self._step(max_output_tokens, stream=True):
            ch = r['choices'][0]
            fin = ch.get('finish_reason') or fin
            d = ch.get('delta') or {}
            _acc_tc(tcs, d.get('tool_calls'))
            yield from split.feed(d.get('content') or '')
        yield from split.finish()
        tcs = [{'id': tc['id'] or f'call_{i}', 'type': 'function',
                'function': {'name': tc['function']['name'], 'arguments': _parse_args(tc['function']['arguments'])}}
               for i, tc in enumerate(tcs)] + split.tool_calls
        res = {'role': 'assistant', 'content': split.text}
        if split.thought: res['channels'] = {'thought': split.thought}
        if tcs: res['tool_calls'] = tcs
        if fin == 'length': res['truncated'] = True
        out = self.count_tokens(split.text + split.thought) if (split.text or split.thought) else 0
        n = self.engine.n_tokens
        res['usage'] = {'prompt_tokens': max(n - out, 0), 'completion_tokens': out, 'total_tokens': n}
        self._step_res = Resp(res)

    def _stream(self, msg, max_output_tokens=None, cbs=None):
        'Stream a turn as markdown chunks; per-call `cbs` live only for this turn.'
        added = self.add_cbs(cbs); prev = getattr(self, '_streaming', False); self._streaming = True
        try:
            self.turn_msg = _mk_msg(msg)
            for _ in run_cbs(self, 'before_send'): pass
            if self.turn_msg is not None: self.hist.append(self.turn_msg)
            fmt, us, steps = StreamFormatter(), [], 0
            while True:
                for o in self._stream_step(max_output_tokens):
                    if (s := fmt.format_item(o)): yield s
                if fmt._inthink: fmt._inthink = False; yield '\n\n'
                res = self._step_res
                us.append(res.get('usage'))
                if not res.get('tool_calls') or steps >= self.max_steps: break
                for tc in res['tool_calls']:
                    yield fmt.format_item({'content': [{'type': 'tool_call', 'name': tc['function'].get('name', ''),
                                                        'arguments': tc['function'].get('arguments', {})}]})
                self._run_tools(res); steps += 1
            if (u := _sum_usage(us)): res['usage'] = u
            self._ctx_tokens = (us[-1] or {}).get('total_tokens', self._ctx_tokens)
            self.turn_res = res
            self.hist.append(res)
            yield from run_cbs(self, 'after_response')
            return self.turn_res
        finally: self._streaming = prev; self.remove_cbs(added)

# %% ../nbs/01_llama.ipynb #038660da
def _mk_obj(schema, d):
    "Build `schema` from json-decoded `d`, rebuilding nested dataclasses; non-dict values pass through."
    if not isinstance(d, dict): return d
    if is_dataclass(schema):
        hints = get_type_hints(schema)
        return schema(**{k: (_mk_obj(hints[k], v) if k in hints else v) for k, v in d.items()})
    return schema(**d)
