"""Give a rishi `Chat` real hands: run any MCP server as a subprocess and hand its tools to the model, behind rishi's approval gate.

Docs: https://vedicreader.github.io/rishi/mcp.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_mcp.ipynb.

# %% auto #0
__all__ = ['BUZZ_MODES', 'SchemaTool', 'MCPError', 'MCPClient', 'mcp_text', 'mcp_tools', 'buzz_dev_mcp', 'buzz_chat']

# %% ../nbs/01_mcp.ipynb #43307d3e
import json, os, queue, signal, subprocess, threading, itertools, time
from fastcore.all import Path, store_attr, L, ifnone, first
from litert_lm.interfaces import Tool
from .core import Chat, hitl_policy

# %% ../nbs/01_mcp.ipynb #fbe0f617
class SchemaTool(Tool):
    "A litert `Tool` defined by a JSON schema and a callable, rather than by a Python signature."
    def __init__(self,
        name:str,            # tool name the model calls
        description:str='',  # what the tool does
        parameters:dict=None,# JSON Schema for the arguments
        fn=None              # `fn(args:dict)` implementing the call
    ):
        store_attr('name,description,fn')   # litert's `Tool` sets `__slots__`, so name the attrs explicitly
        self.parameters = ifnone(parameters, {'type': 'object', 'properties': {}})

    def get_tool_description(self):
        "OpenAI function-tool JSON, which is what litert serialises into the prompt."
        return {'type': 'function', 'function': {'name': self.name, 'description': self.description,
                                                 'parameters': self.parameters}}
    def execute(self, param):
        if self.fn is None: raise NotImplementedError(f"{self.name} has no implementation")
        return self.fn(dict(param))
    def __repr__(self): return f"SchemaTool({self.name})"

# %% ../nbs/01_mcp.ipynb #0a1f57b9
def _types(spec):
    "The JSON types a property accepts, ignoring `null` (schemars writes optionals as `['integer','null']`)."
    t = (spec or {}).get('type')
    return [x for x in (t if isinstance(t, list) else [t]) if x and x != 'null']

def _coerce(args, schema):
    "Cast model-supplied values to the JSON types `schema` asks for (models emit `21.0` for `21`)."
    props = (schema or {}).get('properties', {})
    out = {}
    for k, v in (args or {}).items():
        ts = _types(props.get(k))
        if v is None or not ts: out[k] = v; continue
        if 'integer' in ts and isinstance(v, float) and v.is_integer(): v = int(v)
        elif 'number' in ts and isinstance(v, str):
            try: v = float(v)
            except ValueError: pass
        elif 'string' in ts and not isinstance(v, str):
            v = json.dumps(v) if isinstance(v, (list, dict)) else str(v)
        out[k] = v
    return out

# %% ../nbs/01_mcp.ipynb #dab3d2b6
class MCPError(Exception): "An MCP server returned an error, timed out, or died."

_ENV_KEEP = ('PATH', 'HOME', 'TERM', 'LANG', 'LC_ALL', 'TMPDIR')

def _child_env(env=None):
    "Whitelisted environment for an MCP child, so local secrets do not leak into tools."
    keep = {k: v for k in _ENV_KEEP if (v := os.environ.get(k)) is not None}
    return {**keep, **(env or {})}

# %% ../nbs/01_mcp.ipynb #dad966c8
class MCPClient:
    "A stdio MCP server running as a subprocess, e.g. `buzz-dev-mcp`."
    def __init__(self,
        cmd:str,               # server executable
        args=(),               # its argv
        env:dict=None,         # extra environment (added to the whitelist)
        cwd=None,              # working directory - this is the workspace the tools act on
        timeout:float=180,     # seconds to wait for any one reply
        protocol:str='2025-06-18', # MCP protocol version to request
        log:bool=False,        # let the server's stderr through to yours
        name:str=None          # label, defaults to the executable name
    ):
        store_attr()
        self.name = name or Path(cmd).name
        self.proc, self.info, self.instructions = None, {}, ''
        self._ids, self._lock, self._q = itertools.count(1), threading.Lock(), queue.Queue()

    def start(self):
        "Spawn the server and complete the MCP handshake; idempotent."
        if self.proc: return self
        self.proc = subprocess.Popen([str(self.cmd), *map(str, self.args)],
            stdin=subprocess.PIPE, stdout=subprocess.PIPE,
            stderr=None if self.log else subprocess.DEVNULL,
            text=True, bufsize=1, env=_child_env(self.env), cwd=self.cwd, start_new_session=True)
        threading.Thread(target=self._reader, daemon=True).start()
        r = self._rpc('initialize', {'protocolVersion': self.protocol, 'capabilities': {},
                                     'clientInfo': {'name': 'rishi', 'version': '0.0.2'}})
        self.info, self.instructions = r.get('serverInfo', {}), r.get('instructions', '')
        self._notify('notifications/initialized')
        return self

    def _reader(self):
        for line in self.proc.stdout: self._q.put(line)
        self._q.put(None)

    def _send(self, o):
        if not self.proc: raise MCPError(f"{self.name} is not running")
        self.proc.stdin.write(json.dumps(o) + '\n'); self.proc.stdin.flush()

    def _notify(self, method, params=None):
        self._send({'jsonrpc': '2.0', 'method': method, **({'params': params} if params else {})})

    def _rpc(self, method, params=None, timeout=None):
        "One JSON-RPC round trip; skips notifications and any non-JSON the server prints."
        i, end = next(self._ids), time.monotonic() + ifnone(timeout, self.timeout)
        with self._lock:
            self._send({'jsonrpc': '2.0', 'id': i, 'method': method, 'params': params or {}})
            while True:
                try: line = self._q.get(timeout=max(0., end - time.monotonic()))
                except queue.Empty: raise MCPError(f"{self.name}: {method} timed out after {ifnone(timeout, self.timeout)}s")
                if line is None: raise MCPError(f"{self.name} exited during {method}")
                try: o = json.loads(line)
                except json.JSONDecodeError: continue
                if o.get('id') != i: continue
                if (e := o.get('error')): raise MCPError(f"{self.name}: {method}: {e.get('message', e)}")
                return o.get('result', {})

    def list_tools(self):
        "The tool definitions the server advertises."
        return self.start()._rpc('tools/list').get('tools', [])

    def call_tool(self, name, args=None, timeout=None):
        "Call `name` with `args`; returns the raw MCP result dict."
        return self.start()._rpc('tools/call', {'name': name, 'arguments': args or {}}, timeout=timeout)

    def close(self):
        "Close stdin, then kill the server's whole process group if it lingers. Idempotent."
        p, self.proc = self.proc, None
        if not p: return
        try: p.stdin.close()
        except Exception: pass
        try: p.wait(timeout=5)
        except subprocess.TimeoutExpired:
            try: os.killpg(os.getpgid(p.pid), signal.SIGKILL)
            except (ProcessLookupError, PermissionError): p.kill()
            p.wait(timeout=5)

    def __enter__(self): return self.start()
    def __exit__(self, *a): self.close()
    def __del__(self): self.close()
    def __repr__(self): return f"MCPClient({self.name}, {'running' if self.proc else 'stopped'})"

# %% ../nbs/01_mcp.ipynb #f354cbdb
def mcp_text(res, mx=None):
    "Flatten an MCP `tools/call` result into text for the model."
    if not isinstance(res, dict): return str(res)
    txt = '\n'.join(c.get('text', '') for c in res.get('content', []) if isinstance(c, dict) and c.get('type') == 'text')
    if not txt and (sc := res.get('structuredContent')) is not None: txt = json.dumps(sc)
    if res.get('isError'): txt = f"ERROR: {txt}"
    if mx and len(txt) > mx: txt = txt[:mx] + ' …[truncated]'
    return txt

# %% ../nbs/01_mcp.ipynb #7aa37f52
def mcp_tools(client, include=None, exclude=None, prefix='', mx=50_000, timeout=None):
    "litert tools for an MCP server's catalogue, ready to pass to `Chat(tools=...)`."
    def _mk(t):
        name, sch = t['name'], t.get('inputSchema') or {}
        def fn(args, _n=name, _s=sch):
            try: return mcp_text(client.call_tool(_n, _coerce(args, _s), timeout=timeout), mx)
            except MCPError as e: return f"ERROR: {e}"   # let the model retry rather than killing the turn
        return SchemaTool(prefix + name, t.get('description', ''), sch, fn=fn)
    ts = [t for t in client.list_tools() if not t['name'].startswith('_')]
    if include is not None: ts = [t for t in ts if t['name'] in include]
    if exclude is not None: ts = [t for t in ts if t['name'] not in exclude]
    return L(ts).map(_mk)

# %% ../nbs/01_mcp.ipynb #fee9794e
BUZZ_MODES = {'read_file': 'approved', 'view_image': 'approved', 'todo': 'approved',
              'str_replace': 'check', 'shell': 'check'}

def buzz_dev_mcp(workdir=None, path='buzz-dev-mcp', shell=None, **kw):
    "An `MCPClient` for buzz-dev-mcp, scoped to `workdir` (defaults to the current directory)."
    env = {'BUZZ_SHELL': shell} if shell else None
    return MCPClient(path, cwd=str(workdir or Path.cwd()), env=env, name='buzz-dev-mcp', **kw)

# %% ../nbs/01_mcp.ipynb #d09797ec
def buzz_chat(workdir=None, path='buzz-dev-mcp', modes=None, ask=None, sp=None, tools=None, **kw):
    "A `Chat` wired to buzz-dev-mcp's tools behind rishi's approval gate. Returns `(chat, client)`."
    cli = buzz_dev_mcp(workdir, path).start()
    ts = list(mcp_tools(cli)) + list(tools or [])
    pol = hitl_policy(ifnone(modes, BUZZ_MODES), **({'ask': ask} if ask else {}))
    sp = ifnone(sp, f"You are a coding agent working in a real workspace. Use the tools to do the work "
                    f"rather than describing it, and summarise what you did.\n\n{cli.instructions}")
    return Chat(tools=ts, approve=pol, sp=sp, **kw), cli
