"""[mlx-lm](https://github.com/ml-explore/mlx-lm) on Apple Silicon: an explicit prompt cache, speculative decoding, quantized KV, and mlx-vlm routing for vision and audio.

Docs: https://vedicreader.github.io/rishi/mlx.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_mlx.ipynb.

# %% auto #0
__all__ = ['qwen3_06b', 'qwen3_17b', 'DFLT_MAX_TOKENS', 'qwen3_4b', 'qwen3_8b', 'qwen3_30b', 'gemma3_4b', 'llama32_3b',
           'qwen3vl_4b', 'gemma4_e4b', 'qwen3omni_30b', 'read_config', 'is_vlm', 'ctx_len', 'cached_models',
           'MlxEngine', 'MlxChat', 'MlxVlmChat', 'MlxBroker', 'UsageStats', 'ChatCallback', 'run_cbs', 'resp_text',
           'thought', 'Resp', 'StreamFormatter', 'display_stream', 'mk_tr_details', 'truncated', 'hitl_policy',
           'extract_fence', 'mk_toolspec', 'split_think', 'parse_tool_tags', 'StreamSplit']

# %% ../nbs/03_mlx.ipynb #cf11fc103db8abae
import json, os
from base64 import b64decode
from tempfile import TemporaryDirectory
import mlx.core as mx
from mlx_lm import load as mlx_load, stream_generate
from mlx_lm.sample_utils import make_sampler
from mlx_lm.models.cache import (make_prompt_cache, trim_prompt_cache, can_trim_prompt_cache,
                                 save_prompt_cache, load_prompt_cache)
from huggingface_hub import hf_hub_download, scan_cache_dir
from fastcore.funccall import get_schema, mk_ns
from fastcore.all import Path, store_attr, patch, L, ifnone, first, listify
from . import core
from .core import *

# %% ../nbs/03_mlx.ipynb #4acf570e3a78c822
# re-exported so `from rishi.mlx import *` gives the same vocabulary as the other backends
_all_ = ['UsageStats', 'ChatCallback', 'run_cbs', 'resp_text', 'thought', 'Resp', 'StreamFormatter',
         'display_stream', 'mk_tr_details', 'truncated', 'hitl_policy', 'extract_fence',
         'mk_toolspec', 'split_think', 'parse_tool_tags', 'StreamSplit']

# %% ../nbs/03_mlx.ipynb #70712d3bc7721d7c
#: Common mlx-community repo ids.
qwen3_06b  = 'mlx-community/Qwen3-0.6B-4bit'    # tiny; useful as a speculative-decoding draft model
qwen3_17b  = 'mlx-community/Qwen3-1.7B-4bit'
DFLT_MAX_TOKENS = 1024   #: output cap when nothing says otherwise
qwen3_4b   = 'mlx-community/Qwen3-4B-4bit'
qwen3_8b   = 'mlx-community/Qwen3-8B-4bit'
qwen3_30b  = 'mlx-community/Qwen3-30B-A3B-4bit'
gemma3_4b  = 'mlx-community/gemma-3-4b-it-4bit'
llama32_3b = 'mlx-community/Llama-3.2-3B-Instruct-4bit'
qwen3vl_4b = 'mlx-community/Qwen3-VL-4B-Instruct-4bit'   # vision + text, needs `rishi[mlx-vlm]`
gemma4_e4b = 'mlx-community/gemma-4-e4b-it-4bit'         # vision + audio, needs `rishi[mlx-vlm]`
qwen3omni_30b = 'mlx-community/Qwen3-Omni-30B-A3B-Instruct-4bit'   # audio in, needs `rishi[mlx-vlm]`

def read_config(model):
    "A model's `config.json` as a dict, from a local directory or the hub, or `{}` if it cannot be read."
    try:
        if (p := Path(model)/'config.json').exists(): return json.loads(p.read_text())
    except OSError: pass
    try: return json.loads(Path(hf_hub_download(str(model), 'config.json')).read_text())
    except Exception: return {}

# a vision/audio model carries a second tower in its config; the key varies by architecture
_vlm_keys = ('vision_config', 'audio_config', 'vision_tower', 'image_token_index')

def is_vlm(model, cfg=None):
    "Does `model` declare a vision/audio tower, so it needs `mlx-vlm` rather than plain `mlx-lm`?"
    return any(k in (read_config(model) if cfg is None else cfg) for k in _vlm_keys)

def ctx_len(cfg, dflt=8192):
    "Context window from a model config (checking the nested text config VLMs use), else `dflt`."
    return cfg.get('max_position_embeddings') or (cfg.get('text_config') or {}).get('max_position_embeddings') or dflt

def cached_models():
    "MLX repo ids already in the local HuggingFace cache (no network)."
    try: return L(r.repo_id for r in scan_cache_dir().repos if 'mlx' in r.repo_id.lower())
    except Exception: return L()


# %% ../nbs/03_mlx.ipynb #9004a338faf74842
class MlxEngine:
    "A loaded MLX model and its tokenizer, plus an optional draft model for speculative decoding."
    def __init__(self, model, tokenizer, model_id=None, cfg=None, draft_model=None, draft_model_id=None):
        store_attr(); self.cfg = cfg or {}
    def __repr__(self): return f'MlxEngine({self.model_id})'
    def tokenize(self, text):
        "Token ids for `text`."
        return self.tokenizer.encode(text)
    @property
    def ctx_limit(self):
        "The model's context window, per its config."
        return ctx_len(self.cfg)
    def close(self):
        "Drop references to the weights so MLX can free them."
        self.model = self.draft_model = None

# %% ../nbs/03_mlx.ipynb #c9878e3a40848985
class MlxChat(ToolLoopMixin, Chat):
    "Sync chat over a local MLX model: the `rishi.core.Chat` API over `ToolLoopMixin`'s tool loop."
    _runtime = 'mlx'
    _dflt_cbs = [UsageCallback, ToolReminderCallback, SlidingWindowCallback]
    _media_ok = False    # text-only; `MlxVlmChat` flips this
    _media_note = ("this MLX model is text-only. Install `pip install 'rishi[mlx-vlm]'` and use a vision "
                   "model (e.g. rishi.mlx.qwen3vl_4b) for image or audio input, or pass vlm=True.")
    mk_content, mk_msg, mk_msgs = staticmethod(mk_oai_content), staticmethod(mk_oai_msg), staticmethod(mk_oai_msgs)

    def __new__(cls, model=None, *, runtime=None, model_path=None, vlm=None, **kw):
        "Send a vision or audio repo to `MlxVlmChat`. `vlm=True` or `vlm=False` overrides the config sniff."
        if cls is MlxChat:
            tgt = model_path or core.split_runtime(model)[1] or ''
            if vlm if vlm is not None else (bool(tgt) and is_vlm(tgt)): return object.__new__(MlxVlmChat)
        return object.__new__(cls)

    @staticmethod
    def fmt2hist(msgs):
        "Normalize MLX messages to rishi history dicts."
        return mk_oai_msgs(msgs)
    @staticmethod
    def hist2fmt(msgs):
        "Canonical rishi history dicts -> OpenAI-style messages for the chat template (past-turn media -> placeholder)."
        return [to_oai_msg(strip_media(m)) for m in listify(msgs)]

    @classmethod
    def create_engine(cls, model_id=qwen3_4b, model_path=None, adapter_path=None, draft_model=None, **kw):
        'Load an MLX model + tokenizer, optionally with a LoRA adapter and a draft model. Override/`@patch` to customize.'
        src = str(model_path or model_id)
        model, tok, cfg = mlx_load(src, adapter_path=adapter_path, return_config=True, **kw)
        draft_id = str(draft_model) if isinstance(draft_model, (str, os.PathLike)) else None
        dm = mlx_load(draft_id)[0] if draft_id else draft_model
        return MlxEngine(model, tok, model_id=src, cfg=cfg, draft_model=dm, draft_model_id=draft_id)

    #: MLX spells the sampler's temperature `temp`, so only the window needs renaming
    _opt_map = {'ctx': 'ctx_limit'}
    _opt_skip = ('effort', 'tool_mode', 'api_key', 'base_url')   # nothing local takes these

    def __init__(self, model=None, *, runtime=None, model_path=None, opts=None,
                 vlm=None,               # force the vision class on or off, rather than sniffing
                 engine=None,            # an engine to share instead of loading one
                 adapter_path=None,      # a LoRA adapter to apply
                 draft_model=None,       # a smaller model, for speculative decoding
                 eng_kw=None,            # passed to `create_engine` verbatim
                 min_p=None,
                 prompt_cache=True, max_kv_size=None, kv_bits=None, kv_group_size=64,
                 quantized_kv_start=0,
                 tmpl_kw=None,           # passed to `apply_chat_template`
                 gen_kw=None,            # passed to `stream_generate` verbatim
                 **kw):                  # portable options; see `urai.ChatOpts`
        o = ChatOpts.create(opts, **kw)
        model = core.split_runtime(model)[1]
        model_id = None if model is None or is_path(model) else model
        model_path = model_path or (model if model and is_path(model) else None)
        if o.seed is not None: mx.random.seed(o.seed)
        self._own_engine = engine is None
        if engine is None:
            engine = self.create_engine(model_id or qwen3_4b, model_path, adapter_path=adapter_path,
                                        draft_model=draft_model, **(eng_kw or {}))
        self.engine = engine
        self._set_tools(o.tools)
        samp = {k: v for k, v in dict(temp=o.temp, top_k=o.top_k, top_p=o.top_p,
                                      min_p=min_p).items() if v is not None}
        self.sampler = make_sampler(**samp) if samp else None
        self.think = o.think
        self.max_output_tokens = o.max_output_tokens or DFLT_MAX_TOKENS
        store_attr('max_kv_size,kv_bits,kv_group_size,quantized_kv_start', self)
        self.tmpl_kw, self.gen_kw = tmpl_kw or {}, gen_kw or {}
        self.ctx_limit, self._ctx_tokens = o.ctx or engine.ctx_limit, 0
        self._cache, self._cache_ids = None, []
        if prompt_cache: self._reset_cache()
        self._setup(model, o)

    @property
    def tokenizer(self): return self.engine.tokenizer

    @property
    def token_count(self):
        "Tokens in the model context after the last turn (prompt + completion)."
        return self._ctx_tokens
    @property
    def cached_tokens(self):
        "How many tokens the KV cache currently holds."
        return len(self._cache_ids)

    def count_tokens(self, text):
        "Number of tokens in `text` per the model tokenizer."
        return len(self.engine.tokenize(text))

    def _reset_cache(self):
        "Start fresh main and draft KV caches. The next step re-prefills the whole conversation."
        self._cache = make_prompt_cache(self.engine.model, self.max_kv_size)
        if self.engine.draft_model is not None:
            self._cache += make_prompt_cache(self.engine.draft_model, self.max_kv_size)
        self._cache_ids = []
    def _recreate_conv(self):
        "History was rewritten by context recovery, so the cache no longer matches it. Drop it."
        if self._cache is not None: self._reset_cache()

    def _trim(self, n):
        "Drop the last `n` tokens from the KV cache. On a cache that cannot be trimmed, reset it and return False."
        if can_trim_prompt_cache(self._cache) and trim_prompt_cache(self._cache, n) == n:
            self._cache_ids = self._cache_ids[:len(self._cache_ids) - n]
            return True
        self._reset_cache()
        return False

    def _msgs(self):
        "OpenAI-style messages for the chat template: system prompt plus canonical history."
        return ([{'role': 'system', 'content': self.sp}] if self.sp else []) + self.hist2fmt(self.hist)

    def _prompt_ids(self):
        "Token ids for the whole conversation, rendered with the model's own chat template."
        kw = dict(add_generation_prompt=True)
        if self.toolspecs: kw['tools'] = self.toolspecs
        if self.think is not None: kw['enable_thinking'] = self.think
        return list(self.tokenizer.apply_chat_template(self._msgs(), **kw, **self.tmpl_kw))

    def _feed_ids(self):
        "`(all_ids, ids_still_to_prefill, n_cached)`, reusing however much of the prompt the KV cache covers."
        ids = self._prompt_ids()
        if self._cache is None: return ids, ids, 0
        n = common_prefix_len(ids, self._cache_ids)
        if (drop := len(self._cache_ids) - n) and not self._trim(drop): n = 0
        if n and n == len(ids):                 # nothing left to feed; give back one token to generate from
            n = n - 1 if self._trim(1) else 0
        return ids, ids[n:], n

    _turn_samp = ('temp', 'top_k', 'top_p', 'min_p')   #: these build a sampler, not a generate call
    #: ...and these have no `stream_generate` argument at all
    _turn_drop = ('ctx_limit', 'think', 'effort', 'tool_mode', 'seed')

    def _turn_sampler(self, turn):
        "This turn's sampler, when it overrode any sampling setting, else the chat's own."
        samp = {k: v for k, v in turn.items() if k in self._turn_samp}
        return make_sampler(**samp) if samp else self.sampler

    def _gen_kw(self, **turn):
        "Keyword arguments for `stream_generate`: sampler, prompt cache, KV quantization, draft model."
        t = self.map_opts(turn)
        s = self._turn_sampler(t)
        for k in self._turn_samp + self._turn_drop: t.pop(k, None)
        kw = dict(max_tokens=ifnone(t.pop('max_output_tokens', None), self.max_output_tokens))
        if s is not None: kw['sampler'] = s
        if self._cache is not None: kw['prompt_cache'] = self._cache
        if self.kv_bits: kw.update(kv_bits=self.kv_bits, kv_group_size=self.kv_group_size, quantized_kv_start=self.quantized_kv_start)
        if self.engine.draft_model is not None: kw['draft_model'] = self.engine.draft_model
        return {**kw, **self.gen_kw, **t}

    def _generate(self, feed, **turn):
        "Yield mlx-lm `GenerationResponse` chunks for the token ids in `feed`."
        return stream_generate(self.engine.model, self.tokenizer, feed, **self._gen_kw(**turn))

    def _stream_step(self, **kw):
        "Stream one completion, yielding chunk dicts and leaving the merged `Resp` on `self._step_res`."
        ids, feed, cached = self._feed_ids()
        split, fin, gen, pt, gt = StreamSplit(), None, [], 0, 0
        try:
            for r in self._generate(feed, **kw):
                fin, pt, gt = r.finish_reason or fin, r.prompt_tokens, r.generation_tokens
                gen.append(r.token)
                yield from split.feed(r.text)
        finally:
            # `stream_generate` grows the cache a token at a time, so abandoning it half way leaves
            # `_cache_ids` short of what the cache holds and the next turn trims the wrong amount
            if self._cache is not None: self._cache_ids = ids + gen
        yield from split.finish()
        self._step_res = self._mk_resp(split, fin, cached, pt, gt)

    def _mk_resp(self, split, fin, cached, pt, gt):
        "Assemble one step's `Resp` from the parsed stream plus mlx-lm's token counts."
        res = {'role': 'assistant', 'content': split.text}
        if split.thought: res['channels'] = {'thought': split.thought}
        if split.tool_calls: res['tool_calls'] = split.tool_calls
        if fin == 'length': res['truncated'] = True
        res['usage'] = {'prompt_tokens': cached + pt, 'completion_tokens': gt,
                        'total_tokens': cached + pt + gt, 'cached_tokens': cached}
        return Resp(res)

    def _model_step(self, **kw):
        "One completion, normalized to a `Resp`. MLX generates by streaming, so this drains `_stream_step`."
        for _ in self._stream_step(**kw): pass
        return self._step_res

    def _cache_metadata(self):
        "Identity/settings that must match before a persisted KV cache can safely be reused."
        cfg = dict(model_id=self.engine.model_id, draft_model_id=self.engine.draft_model_id,
                   max_kv_size=self.max_kv_size, kv_bits=self.kv_bits,
                   kv_group_size=self.kv_group_size, quantized_kv_start=self.quantized_kv_start)
        return {'ids': json.dumps(self._cache_ids), 'rishi_mlx_cache': json.dumps(cfg, sort_keys=True)}

    def save_cache(self, fn):
        "Persist the KV cache and the tokens it holds, so a compatible chat can reuse it."
        if self._cache is None: raise ValueError('prompt_cache=False: there is no KV cache to save')
        save_prompt_cache(str(fn), self._cache, self._cache_metadata())
        return self
    def load_cache(self, fn):
        "Restore a compatible KV cache written by `save_cache`, rejecting model and setting mismatches."
        cache, md = load_prompt_cache(str(fn), return_metadata=True)
        got = md.get('rishi_mlx_cache')
        if not got: raise ValueError('not a rishi MLX cache (missing compatibility metadata)')
        expected = json.loads(self._cache_metadata()['rishi_mlx_cache'])
        if (actual := json.loads(got)) != expected:
            raise ValueError(f'incompatible MLX prompt cache: expected {expected}, got {actual}')
        self._cache, self._cache_ids = cache, json.loads(md.get('ids', '[]'))
        return self

    def _raw(self, msgs, max_output_tokens=None, think=None):
        "Stateless completion text for `msgs`, with no history and no prompt cache."
        tkw = {} if think is None else dict(enable_thinking=think)
        ids = list(self.tokenizer.apply_chat_template(msgs, add_generation_prompt=True, **tkw))
        kw = dict(max_tokens=ifnone(max_output_tokens, self.max_output_tokens))
        if self.sampler is not None: kw['sampler'] = self.sampler
        return ''.join(r.text for r in stream_generate(self.engine.model, self.tokenizer, ids, **kw))

    def _oneshot(self, prompt, sp='', think=None, max_tokens=None):
        """Stateless one-shot completion text, with any thinking stripped."""
        msgs = ([{'role': 'system', 'content': sp}] if sp else []) + [{'role': 'user', 'content': prompt}]
        return split_think(self._raw(msgs, max_output_tokens=max_tokens, think=think))[0]

    def _structured_call(self, prompt, schema, sp):
        "JSON reply for `schema`, parsed out of the model's text. mlx-lm has no grammar constraint built in, so this asks and then parses."
        p = f"{prompt}\n\nReply with only a JSON object matching this schema:\n{json.dumps(get_schema(schema)['input_schema'])}"
        txt = self._oneshot(p, sp, think=False)
        try: return json.loads(extract_fence(txt, 'json'))
        except (json.JSONDecodeError, TypeError): pass
        try: return json.loads(txt[txt.index('{'):txt.rindex('}') + 1])   # last resort: the outermost braces
        except Exception as e: raise ValueError(f"model did not return JSON; reply: {txt[:200]!r}") from e

    def close(self):
        "Release the model, if this Chat loaded it, and drop the cache. Idempotent."
        if getattr(self, '_own_engine', False) and getattr(self, 'engine', None) is not None:
            self.engine.close()
            self.engine = None
        self._cache, self._cache_ids = None, []

# %% ../nbs/03_mlx.ipynb #80e075e87717ecf0
def _media_bytes(p):
    "Raw bytes out of an OpenAI-style image/audio content part."
    if p.get('type') == 'image_url':
        url = p['image_url']['url'] if isinstance(p['image_url'], dict) else p['image_url']
        if not url.startswith('data:'):
            raise ValueError('MLX VLM accepts local image bytes/Paths, not remote image URLs')
        return b64decode(url.split(',', 1)[1])
    return b64decode(p['input_audio']['data'])

class MlxVlmChat(MlxChat):
    "MLX chat for vision and audio models, via `mlx-vlm`. Same API as `MlxChat`, and media in the live turn reaches the model."
    _media_ok = True

    @classmethod
    def create_engine(cls, model_id=qwen3vl_4b, model_path=None, adapter_path=None, draft_model=None, **kw):
        'Load a vision or audio model with `mlx_vlm.load`. The "tokenizer" here is a HF processor.'
        try: from mlx_vlm import load as vlm_load
        except ImportError as e:
            raise ImportError(f"vision/audio MLX models need mlx-vlm ({e}). "
                              "Install it with: pip install 'rishi[mlx-vlm]'") from None
        src = str(model_path or model_id)
        if adapter_path: kw['adapter_path'] = adapter_path
        model, proc = vlm_load(src, **kw)
        return MlxEngine(model, proc, model_id=src, cfg=read_config(src))

    def _reset_cache(self):
        "No token-level KV cache on this path: mlx-vlm keeps its own vision-feature cache instead."
        self._cache, self._cache_ids = None, []

    def _tmpdir(self):
        "A per-chat temp directory to stage media files for mlx-vlm."
        if getattr(self, '_td', None) is None: self._td = TemporaryDirectory()
        return Path(self._td.name)

    def _stage(self, data, ext):
        "Write `data` to a temp file and return its path (mlx-vlm takes paths/PIL images, not bytes)."
        p = self._tmpdir()/f'{len(list(self._tmpdir().iterdir()))}{ext}'
        p.write_bytes(data)
        return str(p)

    def _turn_media(self):
        "Image and audio paths from the live turn, staged for mlx-vlm."
        imgs, auds = [], []
        for p in ((self.turn_msg or {}).get('content') or []):
            if not (isinstance(p, dict) and is_media(p)): continue
            if not (data := _media_bytes(p)): continue
            if p['type'] == 'image_url': imgs.append(self._stage(data, '.png'))
            else: auds.append(self._stage(data, f".{p['input_audio'].get('format', 'wav')}"))
        return imgs, auds

    def _prompt(self, imgs, auds):
        "The formatted prompt string mlx-vlm expects, including media counts and tool schemas."
        from mlx_vlm.prompt_utils import apply_chat_template as vlm_tmpl
        # mlx-vlm defaults to `enable_thinking=False`, which prefills an empty `<think></think>` block
        # into the assistant turn. A model told it has already finished thinking can end the turn on the
        # spot - Qwen3-Omni answers an audio prompt with nothing at all. Pass rishi's own `think` through
        # instead, so `think=None` (the default) leaves the model's chat template default alone.
        kw = dict(num_images=len(imgs), num_audios=len(auds), enable_thinking=self.think)
        if self.toolspecs: kw['tools'] = self.toolspecs
        return vlm_tmpl(self.tokenizer, self.engine.cfg, self._msgs(), **{**kw, **self.tmpl_kw})

    def _stream_step(self, **turn):
        "Stream one completion through mlx-vlm, leaving the merged `Resp` on `self._step_res`."
        from mlx_vlm import stream_generate as vlm_stream
        imgs, auds = self._turn_media()
        t = self.map_opts(turn)
        s = self._turn_sampler(t)
        for k in self._turn_samp + self._turn_drop: t.pop(k, None)
        kw = dict(max_tokens=ifnone(t.pop('max_output_tokens', None), self.max_output_tokens),
                  **self.gen_kw, **t)
        if imgs: kw['image'] = imgs
        # mlx-vlm decodes each audio file and resamples it to the processor's own feature-extractor
        # rate, so the source rate is its business, not ours - handing it one is how you get silence
        if auds: kw['audio'] = auds
        split, fin, pt, gt = StreamSplit(), None, 0, 0
        if s is not None: kw['sampler'] = s
        for r in vlm_stream(self.engine.model, self.tokenizer, self._prompt(imgs, auds), **kw):
            fin = getattr(r, 'finish_reason', None) or fin
            pt, gt = getattr(r, 'prompt_tokens', pt), getattr(r, 'generation_tokens', gt)
            yield from split.feed(r.text)
        yield from split.finish()
        self._step_res = self._mk_resp(split, fin, 0, pt, gt)

    def close(self):
        "Release the model and clean up any staged media files."
        if getattr(self, '_td', None) is not None: self._td.cleanup(); self._td = None
        super().close()

# %% ../nbs/03_mlx.ipynb #2d1feab0
class MlxBroker(ChatBroker):
    'Shared MLX model broker. Each client gets an isolated `MlxChat` prompt cache.'
    def __init__(self, address, engine=None, model_id=qwen3_4b, **engine_kw):
        super().__init__(address, MlxChat, engine, model_id, **engine_kw)
