"""`Chat` over a local [Ollama](https://ollama.com) daemon: install, model pull and `ollama serve` driven from Python, native thinking levels and schema-constrained JSON.

Docs: https://vedicreader.github.io/rishi/ollama.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_ollama.ipynb.

# %% auto #0
__all__ = ['OLLAMA_HOST', 'LOCAL_HOSTS', 'qwen3_06b', 'qwen3_17b', 'qwen3_4b', 'gemma3_1b', 'gemma3_4b', 'llama32_3b',
           'dflt_model', 'HF_HOSTS', 'OLLAMA_DIR', 'SERVE_ENV', 'CAP_INPUT', 'ollama_url', 'is_local', 'ollama_model',
           'OllamaError', 'OllamaClient', 'fmt_bytes', 'pull_progress', 'install_url', 'ollama_bin', 'extract_archive',
           'download', 'install_ollama', 'OllamaServer', 'ensure_ollama', 'stop_ollama', 'to_ollama_msg',
           'to_ollama_msgs', 'ollama_usage', 'norm_ochat', 'dflt_ctx', 'OllamaChat', 'ollama_caps', 'UsageStats',
           'ChatCallback', 'run_cbs', 'resp_text', 'thought', 'Resp', 'StreamFormatter', 'display_stream',
           'mk_tr_details', 'truncated', 'hitl_policy', 'extract_fence', 'mk_toolspec', 'ToolCall', 'mk_tool_res_msg',
           'Caps']

# %% ../nbs/08_ollama.ipynb #ol_imports
import json, os, time, atexit, platform, shutil, subprocess, tarfile, zipfile
import httpx2 as httpx
from urllib.parse import urlsplit
from fastcore.funccall import get_schema
from fastcore.all import Path, store_attr, L, ifnone, first, listify
from . import core
from .core import *

# %% ../nbs/08_ollama.ipynb #ol_reexport
# shared names re-exported, so `from rishi.ollama import *` gives what the other backends give
_all_ = ['UsageStats', 'ChatCallback', 'run_cbs', 'resp_text', 'thought', 'Resp', 'StreamFormatter',
         'display_stream', 'mk_tr_details', 'truncated', 'hitl_policy', 'extract_fence', 'mk_toolspec',
         'ToolCall', 'mk_tool_res_msg', 'Caps']

# %% ../nbs/08_ollama.ipynb #ol_addr
#: Where Ollama listens unless `$OLLAMA_HOST` says otherwise.
OLLAMA_HOST = '127.0.0.1:11434'

#: Hostnames that mean this machine, and so must bypass any configured HTTP proxy.
LOCAL_HOSTS = ('127.0.0.1', 'localhost', '::1', '0.0.0.0')

def ollama_url(host=None):
    "Normalize an Ollama host (`:11434`, `host:port`, or a full URL) to a base URL. `None` reads `$OLLAMA_HOST`."
    h = str(host or os.getenv('OLLAMA_HOST') or OLLAMA_HOST).strip()
    if '://' not in h: h = 'http://' + h.lstrip('/')
    u = urlsplit(h)
    return f"{u.scheme}://{u.hostname or '127.0.0.1'}:{u.port or (443 if u.scheme == 'https' else 11434)}"

def is_local(url):
    "Is `url` on this machine? A loopback daemon must not be sent through `$HTTPS_PROXY`."
    return (urlsplit(url).hostname or '') in LOCAL_HOSTS

# %% ../nbs/08_ollama.ipynb #ol_ids
#: Ollama library ids that make useful defaults, smallest first. Any id from https://ollama.com/library works.
qwen3_06b  = 'qwen3:0.6b'
qwen3_17b  = 'qwen3:1.7b'
qwen3_4b   = 'qwen3:4b'
gemma3_1b  = 'gemma3:1b'
gemma3_4b  = 'gemma3:4b'
llama32_3b = 'llama3.2:3b'
dflt_model = qwen3_17b   #: what `OllamaChat()` loads when given no model

#: How Ollama addresses the HuggingFace Hub.
HF_HOSTS = ('hf.co/', 'huggingface.co/')

def ollama_model(model=None, quant='Q4_K_M'):
    "A rishi model id as Ollama addresses it: a hub GGUF repo becomes `hf.co/<repo>:<quant>`, an Ollama id passes through."
    m = str(model or dflt_model).strip()
    if core._is_path(m): raise ValueError(
        f"Ollama serves models from its own store, not a path: {m!r}. Use runtime='llama' for a "
        f"local GGUF file, or import it into Ollama first with `ollama create`.")
    if m.lower().startswith(HF_HOSTS) or '/' not in m: return m
    return f'hf.co/{m}:{quant}' if quant else f'hf.co/{m}'

# %% ../nbs/08_ollama.ipynb #ol_client
class OllamaError(RuntimeError):
    "What the daemon said went wrong, or that nothing answered."

def _err(r):
    "The daemon's own `error` message from a failed response, else the status line."
    try: msg = (r.json() or {}).get('error')
    except Exception: msg = None
    return msg or f'HTTP {r.status_code}: {(r.text or "")[:200]}'

class OllamaClient:
    "One Ollama daemon over HTTP: `/api/chat`, plus the model-management endpoints rishi drives."
    def __init__(self, host=None, timeout=600, client=None):
        self.url, self.timeout, self._own = ollama_url(host), timeout, client is None
        # a loopback daemon must not be sent through $HTTPS_PROXY, which is what `trust_env` would do
        self.client = client or httpx.Client(base_url=self.url, timeout=timeout,
                                             trust_env=not is_local(self.url))

    def __repr__(self): return f'OllamaClient({self.url})'

    def close(self):
        "Close the HTTP client, if this object made it. Idempotent."
        if self._own and getattr(self, 'client', None) is not None: self.client.close()
        self.client = None

    def _check(self, r):
        if r.status_code >= 400: raise OllamaError(_err(r))
        return r

    def get(self, path, **kw):
        "GET `path` as JSON."
        return self._check(self.client.get(path, **kw)).json()

    def post(self, path, payload, **kw):
        "POST `payload` to `path`, as JSON."
        return self._check(self.client.post(path, json=payload, **kw)).json()

    def stream(self, path, payload, timeout=None):
        "POST `payload`, yielding the daemon's newline-delimited JSON as it arrives."
        with self.client.stream('POST', path, json=payload, timeout=ifnone(timeout, self.timeout)) as r:
            if r.status_code >= 400:
                r.read(); raise OllamaError(_err(r))
            for line in r.iter_lines():
                if not (line := line.strip()): continue
                d = json.loads(line)
                # a stream can turn into an error after its 200, so this is not the check above again
                if (e := d.get('error')): raise OllamaError(e)
                yield d

    def version(self, timeout=5):
        "The daemon's version, or None when nothing answers at `url`."
        try: return self.get('/api/version', timeout=timeout).get('version')
        except Exception: return None

    def up(self, timeout=5):
        "Is a daemon answering at `url`?"
        return self.version(timeout) is not None

    def models(self):
        "Model names in the local store."
        return [m['name'] for m in (self.get('/api/tags').get('models') or [])]

    def have(self, model):
        "Is `model` downloaded already? Matches Ollama's implicit `:latest` tag."
        ms = self.models()
        return model in ms or f'{model}:latest' in ms

    def show(self, model):
        "What the daemon knows about `model`: `capabilities`, `template`, `model_info`."
        return self.post('/api/show', {'model': model})

    def ps(self):
        "Models currently loaded in memory."
        return self.get('/api/ps').get('models') or []

    def delete(self, model):
        "Remove `model` from the local store."
        self._check(self.client.request('DELETE', '/api/delete', json={'model': model}))
        return True

    def pull(self, model, on_progress=None):
        "Download `model`, handing each progress record to `on_progress`. Returns `model`."
        for d in self.stream('/api/pull', {'model': model, 'stream': True}):
            if on_progress: on_progress(d)
        return model

    def chat(self, payload, stream=False):
        "One `/api/chat` call: the whole response, or the chunk iterator when `stream` is set."
        if stream: return self.stream('/api/chat', {**payload, 'stream': True})
        return self.post('/api/chat', {**payload, 'stream': False})

# %% ../nbs/08_ollama.ipynb #ol_prog
def fmt_bytes(n):
    "Bytes as a short human string."
    for u in ('B', 'KB', 'MB', 'GB'):
        if n < 1024 or u == 'GB': break
        n /= 1024
    return f'{n:.0f}B' if u == 'B' else f'{n:.1f}{u}'

def pull_progress(out=None):
    "A `pull` callback printing one rewritten line: the status, and how far the bytes have got."
    def show(d):
        s, done, total = d.get('status', ''), d.get('completed') or 0, d.get('total')
        line = f'{s} {fmt_bytes(done)}/{fmt_bytes(total)}' if total else s
        print(f'\r{line[:78]:<78}', end='', flush=True, file=out)
        if s in ('success', 'error'): print(file=out)
    return show

# %% ../nbs/08_ollama.ipynb #ol_install
#: Where rishi installs its own copy of Ollama, when the machine has none.
OLLAMA_DIR = Path.home()/'.cache'/'rishi'/'ollama'

def install_url(system=None, machine=None):
    "URL of the Ollama release archive for this platform."
    s, m = (system or platform.system()).lower(), (machine or platform.machine()).lower()
    if s == 'darwin':  return 'https://ollama.com/download/ollama-darwin.tgz'
    if s == 'windows': return 'https://ollama.com/download/ollama-windows-amd64.zip'
    if s == 'linux':
        return f"https://ollama.com/download/ollama-linux-{'arm64' if m in ('arm64', 'aarch64') else 'amd64'}.tar.zst"
    raise OllamaError(f'no Ollama release for {s}/{m}; install it from https://ollama.com/download')

def ollama_bin(dir=None, system=True):
    "An `ollama` binary: `$OLLAMA_BIN`, then rishi's own install, then `$PATH` unless `system=False`. None if there is none."
    exe = 'ollama.exe' if platform.system() == 'Windows' else 'ollama'
    if (b := os.getenv('OLLAMA_BIN')) and Path(b).exists(): return Path(b)
    d = Path(dir or OLLAMA_DIR)
    if (p := first((d/'bin'/exe, d/exe), Path.exists)): return p
    return Path(w) if system and (w := shutil.which('ollama')) else None

# %% ../nbs/08_ollama.ipynb #ol_extract
def _zstd_reader(f):
    "A decompressing reader over zstd file `f`: stdlib on Python 3.14+, else the `zstandard` package."
    try:
        from compression.zstd import ZstdFile
        return ZstdFile(f)
    except ImportError: pass
    try: from zstandard import ZstdDecompressor
    except ImportError: raise OllamaError(
        "the Linux Ollama archive is zstd-compressed, which needs Python 3.14+ or the zstandard "
        "package: pip install 'rishi[ollama]'") from None
    return ZstdDecompressor().stream_reader(f)

def _untar(t, dest):
    "Extract tarfile `t`, asking for the `tar` filter where the runtime has PEP 706 filters."
    try: t.extractall(dest, filter='tar')
    except TypeError: t.extractall(dest)

def extract_archive(src, dest):
    "Extract a `.tgz`, `.tar.zst` or `.zip` release archive into `dest`."
    dest, src = Path(dest), str(src)
    dest.mkdir(parents=True, exist_ok=True)
    if src.endswith('.zip'):
        with zipfile.ZipFile(src) as z: z.extractall(dest)
    elif src.endswith('.zst'):
        # not seekable: `r|` reads the tar forwards, as the decompressor hands it over
        with open(src, 'rb') as f, _zstd_reader(f) as r, tarfile.open(fileobj=r, mode='r|') as t:
            _untar(t, dest)
    else:
        with tarfile.open(src, 'r:gz') as t: _untar(t, dest)
    return dest

def download(url, dest, on_progress=None, timeout=600):
    "Stream `url` to `dest`, reporting `(done, total)` bytes to `on_progress`."
    with httpx.stream('GET', url, follow_redirects=True, timeout=timeout) as r:
        r.raise_for_status()
        total, done = int(r.headers.get('content-length') or 0), 0
        with open(dest, 'wb') as f:
            for chunk in r.iter_bytes(1<<20):
                f.write(chunk); done += len(chunk)
                if on_progress: on_progress(done, total)
    return Path(dest)

def install_ollama(dir=OLLAMA_DIR, url=None, force=False, on_progress=None):
    "Install Ollama under `dir` for this user: no root, no package manager, no system service. Returns the binary."
    if not force and (b := ollama_bin(dir, system=False)): return b
    url, dir = url or install_url(), Path(dir)
    dir.mkdir(parents=True, exist_ok=True)
    tmp = dir/('rishi-download' + ''.join(Path(urlsplit(url).path).suffixes))
    try:
        download(url, tmp, on_progress)
        extract_archive(tmp, dir)
    finally: tmp.unlink(missing_ok=True)
    if not (b := ollama_bin(dir, system=False)):
        raise OllamaError(f'no ollama binary under {dir} after extracting {url}')
    b.chmod(0o755)
    return b

# %% ../nbs/08_ollama.ipynb #ol_server
#: Constructor argument -> the environment variable `ollama serve` reads it from.
SERVE_ENV = {'models': 'OLLAMA_MODELS', 'n_ctx': 'OLLAMA_CONTEXT_LENGTH', 'keep_alive': 'OLLAMA_KEEP_ALIVE',
             'flash_attn': 'OLLAMA_FLASH_ATTENTION', 'kv_cache_type': 'OLLAMA_KV_CACHE_TYPE',
             'num_parallel': 'OLLAMA_NUM_PARALLEL', 'max_loaded': 'OLLAMA_MAX_LOADED_MODELS'}

class OllamaServer:
    "An `ollama serve` process rishi starts and owns, installing Ollama first if the machine has none."
    def __init__(self, host=None, bin=None, dir=OLLAMA_DIR, models=None, n_ctx=None, keep_alive=None,
                 flash_attn=None, kv_cache_type=None, num_parallel=None, max_loaded=None, log=None):
        self.url, self.proc = ollama_url(host), None
        store_attr('bin,dir,models,n_ctx,keep_alive,flash_attn,kv_cache_type,num_parallel,max_loaded,log')

    def __repr__(self): return f'OllamaServer({self.url}, running={self.running})'

    @property
    def running(self):
        "Is the process this object started still alive?"
        return self.proc is not None and self.proc.poll() is None

    def env(self):
        "The environment `ollama serve` gets: this process's own, plus what this server configures."
        e = dict(os.environ, OLLAMA_HOST=self.url)
        for k, var in SERVE_ENV.items():
            if (v := getattr(self, k)) is not None: e[var] = str(int(v) if isinstance(v, bool) else v)
        return e

    def client(self, **kw):
        "An `OllamaClient` pointed at this server."
        return OllamaClient(self.url, **kw)

    def start(self, install=True, timeout=60, on_progress=None):
        "Start the daemon and wait for it to answer. A daemon already listening at `url` is left alone."
        cl = self.client(timeout=30)
        try:
            if cl.up(): return self
            if (b := self.bin) is not None:
                # an explicit `bin` that is not there is a mistake to report, not one to route around
                if not Path(b).exists(): raise OllamaError(f'no ollama binary at {b}')
            elif not (b := ollama_bin(self.dir)):
                if not install: raise OllamaError(
                    'no ollama binary found; install one, or call install_ollama()')
                b = install_ollama(self.dir, on_progress=on_progress)
            self.bin = b
            out = open(self.log, 'ab') if self.log else subprocess.DEVNULL
            # its own session, so a Ctrl-C meant for the parent does not also kill the daemon
            self.proc = subprocess.Popen([str(b), 'serve'], env=self.env(), stdout=out, stderr=out,
                                         start_new_session=True)
            atexit.register(self.stop)
            for _ in range(int(timeout*10)):
                if cl.up(timeout=2): return self
                if not self.running: raise OllamaError(
                    f'`{b} serve` exited with {self.proc.returncode}' + (f'; see {self.log}' if self.log else ''))
                time.sleep(0.1)
            self.stop()
            raise OllamaError(f'`{b} serve` did not answer at {self.url} within {timeout}s')
        finally: cl.close()

    def stop(self, timeout=10):
        "Stop the daemon, if this object started it. Idempotent, and registered to run at exit."
        p, self.proc = self.proc, None
        if p is None or p.poll() is not None: return self
        p.terminate()
        try: p.wait(timeout)
        except subprocess.TimeoutExpired: p.kill(); p.wait()
        return self

# %% ../nbs/08_ollama.ipynb #ol_ensure
#: Daemons rishi started, by URL, so a second chat reuses the first one's server.
_servers = {}

def ensure_ollama(host=None, install=True, serve=True, timeout=60, on_progress=None, srv_kw=None):
    "A client for a live daemon at `host`: reuse one already listening, else start one, installing Ollama if needed."
    url = ollama_url(host)
    cl = OllamaClient(url)
    if cl.up(): return cl
    cl.close()
    if not serve: raise OllamaError(
        f'nothing is listening at {url}. Start one with `ollama serve`, or pass serve=True.')
    srv = _servers.get(url) or OllamaServer(url, **(srv_kw or {}))
    srv.start(install=install, timeout=timeout, on_progress=on_progress)
    _servers[url] = srv
    return srv.client()

def stop_ollama(host=None):
    "Stop the daemon rishi started at `host`, or every one of them when `host` is None."
    for url in ([ollama_url(host)] if host else list(_servers)):
        if (s := _servers.pop(url, None)): s.stop()

# %% ../nbs/08_ollama.ipynb #ol_msgs
def _img_b64(p):
    "The bare base64 of an OpenAI-style image part, with any data-URL wrapper taken off."
    u = p.get('image_url')
    u = u.get('url', '') if isinstance(u, dict) else (u or '')
    return u.split(',', 1)[1] if u.startswith('data:') else u

def to_ollama_msg(m):
    "One canonical rishi history dict -> an Ollama chat message."
    if (role := m.get('role', 'user')) == 'tool':
        return {'role': 'tool', 'content': str(m.get('content', '')), 'tool_name': m.get('name', '')}
    c = m.get('content')
    txt, imgs = [], []
    for p in (c if isinstance(c, list) else [{'type': 'text', 'text': c or ''}]):
        if not isinstance(p, dict): continue
        if (t := p.get('type')) == 'text': txt.append(p.get('text', ''))
        elif t == 'image_url': imgs.append(_img_b64(p))
        elif t == 'input_audio': raise TypeError(
            "Ollama's chat API carries text and images only. For audio use runtime='llama' (mtmd) "
            "or runtime='mlx'.")
    out = {'role': role, 'content': '\n'.join(x for x in txt if x)}
    if imgs: out['images'] = imgs
    if (th := (m.get('channels') or {}).get('thought')): out['thinking'] = th
    if (tcs := m.get('tool_calls')):
        out['tool_calls'] = [{'function': {'name': tc_name(tc),
                                           'arguments': (tc.get('function') or {}).get('arguments') or {}}}
                             for tc in tcs]
    return out

def to_ollama_msgs(msgs, sp=''):
    "Canonical rishi history -> Ollama messages, with `sp` as the leading system message."
    sys = [{'role': 'system', 'content': sp}] if sp else []
    return sys + [to_ollama_msg(m) for m in listify(msgs) if m.get('role') != 'system']

# %% ../nbs/08_ollama.ipynb #ol_resp
def ollama_usage(r, model=None):
    "Ollama's eval counts -> a rishi usage dict."
    p, c = r.get('prompt_eval_count') or 0, r.get('eval_count') or 0
    return {'prompt_tokens': p, 'completion_tokens': c, 'total_tokens': p + c,
            'model': model or r.get('model')}

def _tcs(tcs):
    "Ollama tool calls -> canonical `ToolCall`s. Ollama sends arguments as an object, and no call id."
    return [ToolCall(name=(f := tc.get('function') or {}).get('name', ''),
                     arguments=parse_args(f.get('arguments'))) for tc in (tcs or [])]

def _tag_tcs(tcs):
    "`<tool_call>` blocks parsed out of reply text -> canonical `ToolCall`s."
    return [ToolCall(name=tc['function']['name'], arguments=tc['function']['arguments'], id=tc['id'])
            for tc in tcs]

def norm_ochat(r, model=None):
    "One `/api/chat` response -> a rishi `Resp`, reading `<think>` and `<tool_call>` text as well as the native fields."
    m = r.get('message') or {}
    text, th = split_think(m.get('content') or '')
    text, tag_tcs = parse_tool_tags(text)
    th = '\n'.join(x for x in (m.get('thinking') or '', th) if x)
    res = {'role': 'assistant', 'content': text}
    if th: res['channels'] = {'thought': th}
    if (tcs := _tcs(m.get('tool_calls')) + _tag_tcs(tag_tcs)): res['tool_calls'] = tcs
    if r.get('done_reason') == 'length': res['truncated'] = True
    res['usage'] = ollama_usage(r, model)
    return Resp(res)

# %% ../nbs/08_ollama.ipynb #ol_chat
def dflt_ctx():
    "The context length the daemon uses when a request names none: `$OLLAMA_CONTEXT_LENGTH`, else Ollama's own 4096."
    try: return int(os.getenv('OLLAMA_CONTEXT_LENGTH') or 4096)
    except ValueError: return 4096

class OllamaChat(ToolLoopMixin, Chat):
    "Sync chat against a model on an Ollama daemon: the `rishi.core.Chat` API over `ToolLoopMixin`'s tool loop."
    _runtime = 'ollama'
    _dflt_cbs = [UsageCallback, ToolReminderCallback, SlidingWindowCallback]
    mk_content, mk_msg, mk_msgs = staticmethod(mk_oai_content), staticmethod(mk_oai_msg), staticmethod(mk_oai_msgs)

    @staticmethod
    def fmt2hist(msgs):
        "Normalize incoming messages to canonical rishi history dicts."
        return mk_oai_msgs(msgs)
    @staticmethod
    def hist2fmt(msgs):
        "Canonical rishi history dicts -> Ollama messages."
        return [to_ollama_msg(m) for m in listify(msgs)]

    def __init__(self, model=None, *, runtime=None, model_path=None, host=None, client=None,
                 quant='Q4_K_M', pull=True, install=True, serve=True, srv_kw=None, on_progress=None,
                 n_ctx=None, n_gpu_layers=None, keep_alive=None, options=None,
                 sp='', messages=None, tools=None, ctx_limit=None, approve=None, tool_max_len=None,
                 max_steps=10, parallel_tools=False, max_parallel_tools=None, final_prompt=dflt_final_prompt_,
                 think=None, temp=None, top_k=None, top_p=None, seed=None,
                 max_output_tokens=None, comp_kw=None, cbs=None, default_cbs=True):
        model = core.split_runtime(model)[1]
        self.model_id = ollama_model(model or model_path, quant)
        self._own_client = client is None
        self.client = client or ensure_ollama(host, install=install, serve=serve, srv_kw=srv_kw,
                                              on_progress=on_progress)
        self._opts = {k: v for k, v in dict(temperature=temp, top_k=top_k, top_p=top_p, seed=seed,
                                            num_ctx=n_ctx, num_gpu=n_gpu_layers).items() if v is not None}
        self._opts.update(options or {})
        store_attr('think,keep_alive,max_output_tokens', self)
        # a model with no thinking refuses `think`; this goes false on the first refusal
        self._think_ok, self.comp_kw, self._ctx_tokens = think is not None, comp_kw or {}, 0
        self._set_tools(tools)
        if pull and not self.client.have(self.model_id):
            self.client.pull(self.model_id, ifnone(on_progress, pull_progress()))
        self.ctx_limit = ctx_limit or n_ctx or dflt_ctx()
        self._setup(model=model, sp=sp, messages=messages, tools=tools, approve=approve,
                    tool_max_len=tool_max_len, max_steps=max_steps, parallel_tools=parallel_tools,
                    max_parallel_tools=max_parallel_tools, final_prompt=final_prompt, cbs=cbs,
                    default_cbs=default_cbs)

    def close(self):
        "Release this chat's HTTP client. The daemon is shared, so it stays up; `stop_ollama()` ends one rishi started."
        if self._own_client and getattr(self, 'client', None) is not None: self.client.close()
        self.client = None

    @property
    def token_count(self):
        "Tokens the last turn reported (prompt + completion). Ollama has no live context read-out."
        return self._ctx_tokens

    def count_tokens(self, text):
        "Estimated tokens in `text`. Ollama exposes no tokenizer, so the real count only arrives in `use`, after a turn."
        return est_tokens(text)

    def unload(self):
        "Drop the model from the daemon's memory now, rather than when `keep_alive` runs out."
        self.client.chat({'model': self.model_id, 'messages': [], 'keep_alive': 0})
        return self

    def _msgs(self):
        "The whole conversation as Ollama messages, system prompt first."
        return to_ollama_msgs(self.hist, self.sp)

    def _payload(self, stream=False, max_output_tokens=None, msgs=None, tools=True, fmt=None, think=...):
        "One `/api/chat` request body."
        opts = dict(self._opts)
        if (n := ifnone(max_output_tokens, self.max_output_tokens)) is not None: opts['num_predict'] = int(n)
        p = {'model': self.model_id, 'messages': ifnone(msgs, self._msgs()), 'stream': stream}
        if opts: p['options'] = opts
        if tools and self.toolspecs: p['tools'] = self.toolspecs
        if fmt is not None: p['format'] = fmt
        if self.keep_alive is not None: p['keep_alive'] = self.keep_alive
        if (th := self.think if think is ... else think) is not None and self._think_ok: p['think'] = th
        return {**p, **self.comp_kw}

    def _drop_think(self, payload, e):
        "Was `e` the daemon refusing `think`? Then take it off `payload` and stop sending it."
        if 'think' not in payload or 'think' not in str(e).lower(): return False
        self._think_ok = False
        payload.pop('think')
        return True

    def _ask(self, payload):
        "One request, retried once without `think` if the model has no thinking to give."
        try: return self.client.chat(payload)
        except OllamaError as e:
            if not self._drop_think(payload, e): raise
            return self.client.chat(payload)

    def _ask_stream(self, payload):
        "Stream one request. A refusal only lands on the first chunk, so the retry has to sit there."
        it = iter(self.client.chat(payload, stream=True))
        try: first_chunk = next(it)
        except StopIteration: return
        except OllamaError as e:
            if not self._drop_think(payload, e): raise
            it = iter(self.client.chat(payload, stream=True))
            first_chunk = next(it)
        yield first_chunk
        yield from it

    def _model_step(self, max_output_tokens=None):
        "One completion, normalized to a `Resp`. The single wire call `ToolLoopMixin` drives."
        return norm_ochat(self._ask(self._payload(max_output_tokens=max_output_tokens)), self.model_id)

    def _stream_step(self, max_output_tokens=None):
        "Stream one completion, yielding chunk dicts and leaving the merged `Resp` on `self._step_res`."
        split, tcs, native_th, last = StreamSplit(), [], '', {}
        for d in self._ask_stream(self._payload(stream=True, max_output_tokens=max_output_tokens)):
            msg = d.get('message') or {}
            if (th := msg.get('thinking')):
                native_th += th
                yield {'channels': {'thought': th}}
            if (c := msg.get('content')): yield from split.feed(c)
            tcs += msg.get('tool_calls') or []
            if d.get('done'): last = d
        yield from split.finish()
        res = {'role': 'assistant', 'content': split.text}
        if (th := '\n'.join(x for x in (native_th, split.thought) if x)): res['channels'] = {'thought': th}
        if (calls := _tcs(tcs) + _tag_tcs(split.tool_calls)): res['tool_calls'] = calls
        if last.get('done_reason') == 'length': res['truncated'] = True
        res['usage'] = ollama_usage(last, self.model_id)
        self._step_res = Resp(res)

    def _oneshot(self, prompt, sp='', think=None, max_tokens=None):
        "Stateless completion text: no history, no tools. It shares the daemon, which caches per conversation."
        msgs = ([{'role': 'system', 'content': sp}] if sp else []) + [{'role': 'user', 'content': prompt}]
        p = self._payload(max_output_tokens=max_tokens, msgs=msgs, tools=False, think=think)
        return resp_text(norm_ochat(self._ask(p), self.model_id))

    def _structured_call(self, prompt, schema, sp):
        "Schema-constrained JSON through Ollama's own `format`, returning the decoded argument dict."
        msgs = ([{'role': 'system', 'content': sp}] if sp else []) + [{'role': 'user', 'content': prompt}]
        p = self._payload(msgs=msgs, tools=False, fmt=get_schema(schema)['input_schema'])
        txt = resp_text(norm_ochat(self._ask(p), self.model_id))
        try: return json.loads(txt)
        except json.JSONDecodeError:
            raise ValueError(f'model returned no JSON for the schema; reply: {txt[:200]!r}') from None

# %% ../nbs/08_ollama.ipynb #ol_caps
#: `/api/show` capability -> what `rishi.core.Caps` calls that input modality.
CAP_INPUT = {'vision': 'image'}

def ollama_caps(model=None, client=None, quant='Q4_K_M'):
    "What an Ollama model accepts, from the daemon's own `/api/show`. None when no daemon answers."
    try:
        cl = client or OllamaClient()
        if not cl.up(): return None
        caps = cl.show(ollama_model(model, quant)).get('capabilities') or []
    except Exception: return None
    return Caps(('text',) + tuple(dict.fromkeys(CAP_INPUT[c] for c in caps if c in CAP_INPUT)),
                ('text',), (), 'runtime')
