"""Hosted models through the same `Chat` API, via [fastllm](https://github.com/AnswerDotAI/fastllm).

Docs: https://vedicreader.github.io/rishi/remote.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_remote.ipynb.

# %% auto #0
__all__ = ['NO_THINK_EFFORT', 'to_msg', 'to_hist', 'norm_usage', 'norm_completion', 'RemoteChat', 'UsageStats', 'ChatCallback',
           'run_cbs', 'resp_text', 'thought', 'Resp', 'StreamFormatter', 'display_stream', 'mk_tr_details', 'truncated',
           'hitl_policy', 'extract_fence', 'mk_toolspec', 'ToolCall', 'mk_tool_res_msg']

# %% ../nbs/04_remote.ipynb #rm_imports
import json, os, asyncio
from base64 import b64encode
from fastllm.acomplete import acomplete
from fastllm.types import Completion, Usage
from aidialog.msg_parts import Msg, Part, PartType, data_url
from fastcore.funccall import mk_ns
from fastcore.all import Path, store_attr, patch, L, ifnone, first, listify
from . import core
from .core import *

# %% ../nbs/04_remote.ipynb #rm_reexport
_all_ = ['UsageStats', 'ChatCallback', 'run_cbs', 'resp_text', 'thought', 'Resp', 'StreamFormatter',
         'display_stream', 'mk_tr_details', 'truncated', 'hitl_policy', 'extract_fence', 'mk_toolspec',
         'ToolCall', 'mk_tool_res_msg']

# %% ../nbs/04_remote.ipynb #rm_msgs
def _img_url(p):
    "Data URL for an OpenAI-style image part (`image_url` may be a dict or a bare string)."
    u = p.get('image_url')
    return u.get('url') if isinstance(u, dict) else u

def _aud_url(p):
    "Data URL for an OpenAI-style `input_audio` part."
    a = p.get('input_audio') or {}
    return f"data:audio/{a.get('format', 'wav')};base64,{a.get('data', '')}"

def _parts(content):
    "Canonical rishi content (str or list of parts) -> fastllm `Part`s."
    if content is None: return []
    if isinstance(content, str): return [Part(type=PartType.text, text=content)]
    out = []
    for p in content:
        if not isinstance(p, dict): continue
        t = p.get('type')
        if   t == 'text':        out.append(Part(type=PartType.text, text=p.get('text', '')))
        elif t == 'image_url':   out.append(Part(type=PartType.input_image, text=_img_url(p)))
        elif t == 'input_audio': out.append(Part(type=PartType.input_audio, text=_aud_url(p)))
    return out

def to_msg(m):
    "One canonical rishi history dict -> a fastllm `Msg`."
    role = m.get('role', 'user')
    if role == 'tool':
        return Msg(role='tool', content=[Part(type=PartType.tool_result, text=str(m.get('content', '')),
                                              data={'id': m.get('tool_call_id'), 'name': m.get('name', '')})])
    parts = []
    if role == 'assistant' and (th := (m.get('channels') or {}).get('thought')):
        parts.append(Part(type=PartType.thinking, text=th))
    parts += _parts(m.get('content'))
    for tc in (m.get('tool_calls') or []):
        fn = tc.get('function') or {}
        parts.append(Part(type=PartType.tool_use, data={'id': tc.get('id'), 'name': fn.get('name', ''),
                                                        'arguments': fn.get('arguments') or {},
                                                        'server': bool(tc.get('server'))}))
    return Msg(role=role, content=parts)

def to_hist(m):
    "A fastllm `Msg` -> canonical rishi history dicts (a tool `Msg` can hold several results)."
    if m.role == 'tool':
        return [{'role': 'tool', 'tool_call_id': (p.data or {}).get('id'), 'name': (p.data or {}).get('name', ''),
                 'content': str(p.text)} for p in m.content if p.type == PartType.tool_result]
    text = ''.join(p.text or '' for p in m.content if p.type == PartType.text)
    th   = ''.join(p.text or '' for p in m.content if p.type == PartType.thinking)
    media = [p for p in m.content if p.type in (PartType.input_image, PartType.input_audio)]
    out = {'role': m.role, 'content': text}
    if media:
        parts = ([{'type': 'text', 'text': text}] if text else []) + [_media_part(p) for p in media]
        out['content'] = parts
    if th: out['channels'] = {'thought': th}
    tcs = [ToolCall(name=(p.data or {}).get('name', ''), arguments=(p.data or {}).get('arguments') or {},
                    id=(p.data or {}).get('id'), server=bool((p.data or {}).get('server')))
           for p in m.content if p.type == PartType.tool_use]
    if tcs: out['tool_calls'] = tcs
    return [out]

def _media_part(p):
    "A fastllm media `Part` -> an OpenAI-style content part."
    if p.type == PartType.input_image: return {'type': 'image_url', 'image_url': {'url': p.text}}
    mime, b64 = data_url(p.text) or ('audio/wav', '')
    return {'type': 'input_audio', 'input_audio': {'data': b64, 'format': mime.split('/')[-1]}}

# %% ../nbs/04_remote.ipynb #rm_resp
def norm_usage(u, model=None):
    "fastllm `Usage` -> rishi `UsageStats`."
    if u is None: return {}
    return {'prompt_tokens': u.prompt_tokens, 'completion_tokens': u.completion_tokens,
            'total_tokens': u.total_tokens or (u.prompt_tokens + u.completion_tokens),
            'cached_tokens': u.cached_tokens, 'model': model}

def norm_completion(comp):
    """fastllm `Completion` -> rishi `Resp`.

    Tag calls are read out of the text as well as native ones, exactly as `core.norm_resp`
    does for the OpenAI-shaped path. A hosted model asked to use the tag protocol -- because
    its transport has no tool field, or policy forbids the one it has -- would otherwise emit
    a perfectly good `<tool_call>` block and have it rendered as prose.
    """
    res = to_hist(comp.message)[0]
    res.setdefault('role', 'assistant')
    if isinstance(res.get('content'), str):
        res['content'], tag_tcs = parse_tool_tags(res['content'])
    else: tag_tcs = []
    if comp.tool_calls or tag_tcs:
        res['tool_calls'] = [ToolCall(name=tc.name, arguments=tc.arguments, id=tc.id, server=tc.server)
                             for tc in (comp.tool_calls or [])] + [
                            ToolCall(name=tc['function']['name'], arguments=tc['function']['arguments'],
                                     id=tc['id']) for tc in tag_tcs]
    if comp.finish_reason == 'length': res['truncated'] = True
    res['usage'] = norm_usage(comp.usage, comp.model)
    return Resp(res)

# %% ../nbs/04_remote.ipynb #rm_chat
#: What `think=False` asks a hosted model for. There is no cross-provider "do not think" --
#: the local backends have a chat-template switch and hosted ones have `reasoning_effort` --
#: so it is spelled as the lowest effort the current APIs understand, and it is a name here
#: rather than a literal so a deployment whose provider spells it otherwise can say so.
NO_THINK_EFFORT = 'minimal'

class RemoteChat(ToolLoopMixin, Chat):
    "Chat against a hosted model through fastllm - the same `rishi.core.Chat` API as the local backends."
    _runtime = 'remote'
    _dflt_cbs = [UsageCallback, ToolReminderCallback, SlidingWindowCallback]
    mk_content, mk_msg, mk_msgs = staticmethod(mk_oai_content), staticmethod(mk_oai_msg), staticmethod(mk_oai_msgs)

    @staticmethod
    def fmt2hist(msgs):
        "fastllm `Msg`s (or canonical dicts) -> canonical rishi history dicts."
        out = []
        for m in listify(msgs): out += to_hist(m) if isinstance(m, Msg) else [mk_oai_msg(m)]
        return out
    @staticmethod
    def hist2fmt(msgs):
        "Canonical rishi history dicts -> fastllm `Msg`s (media carried through, not stripped)."
        return [to_msg(m) for m in listify(msgs) if m.get('role') != 'system']

    def __init__(self, model=None, *, runtime=None, model_path=None, api_key=None, base_url=None,
                 vendor_name=None, api_name=None, sp='', messages=None, tools=None, ctx_limit=None,
                 approve=None, tool_max_len=None, max_steps=10, parallel_tools=False,
                 max_parallel_tools=None, final_prompt=dflt_final_prompt_, tool_choice=None, reasoning_effort=None,
                 temp=None, max_output_tokens=4096, retries=2, comp_kw=None, cbs=None, default_cbs=True,
                 tool_mode='native'):   # 'native' sends schemas on the wire; 'tags' puts them in the system prompt
        model = core.split_runtime(model)[1]
        self.tool_mode = tool_mode
        self.model_id = model or 'gpt-5.1'
        self.toolspecs = [mk_toolspec(t) for t in L(tools)]
        self.ns = mk_ns([t for t in L(tools) if callable(t)])
        store_attr('api_key,base_url,vendor_name,api_name,tool_choice,reasoning_effort,temp,'
                   'max_output_tokens,retries', self)
        self.comp_kw, self._ctx_tokens = comp_kw or {}, 0
        self.ctx_limit = ctx_limit
        self._setup(model=model, sp=sp, messages=messages, tools=tools, approve=approve,
                    tool_max_len=tool_max_len, max_steps=max_steps, parallel_tools=parallel_tools,
                    max_parallel_tools=max_parallel_tools, final_prompt=final_prompt, cbs=cbs, default_cbs=default_cbs)

    @property
    def token_count(self):
        "Tokens the last turn reported (prompt + completion); hosted APIs have no live context read-out."
        return self._ctx_tokens

    def _kw(self, stream=False, max_output_tokens=None):
        "Keyword arguments for `acomplete`."
        kw = dict(stream=stream, api_key=self.api_key, base_url=self.base_url, retries=self.retries,
                  vendor_name=self.vendor_name, api_name=self.api_name,
                  max_tokens=ifnone(max_output_tokens, self.max_output_tokens))
        tags = self.tool_mode == 'tags'
        sp = tag_tools_sp(self.toolspecs, self.sp) if tags else self.sp
        if sp: kw['system'] = sp
        # In tag mode the schemas have already gone out in the system prompt, and putting them
        # on the wire as well is the thing the transport cannot do.
        if self.toolspecs and not tags: kw['tools'] = self.toolspecs
        if self.tool_choice is not None and not tags: kw['tool_choice'] = self.tool_choice
        if self.reasoning_effort is not None: kw['reasoning_effort'] = self.reasoning_effort
        if self.temp is not None: kw['temperature'] = self.temp
        return {**kw, **self.comp_kw}

    async def _acomplete(self, msgs, stream=False, max_output_tokens=None):
        "One `acomplete` call for `msgs` (canonical rishi dicts)."
        return await acomplete(self.hist2fmt(msgs), self.model_id, **self._kw(stream, max_output_tokens))

    def _model_step(self, max_output_tokens=None):
        "One completion, normalized to a `Resp` - the wire call `ToolLoopMixin` drives."
        return norm_completion(run_coro(self._acomplete(self.hist, False, max_output_tokens)))

    def _stream_step(self, max_output_tokens=None):
        "Stream one completion; yields chunk dicts and leaves the merged `Resp` on `self._step_res`."
        async def _agen():
            agen = await self._acomplete(self.hist, True, max_output_tokens)
            async for o in agen: yield o
        comp, split = None, StreamSplit() if self.tool_mode == 'tags' else None
        for o in sync_iter(_agen):
            if isinstance(o, Completion): comp = o
            elif isinstance(o, Part):
                if o.type == PartType.tool_use and o.data:
                    yield {'content': [{'type': 'tool_call', 'name': o.data.get('name', ''),
                                        'arguments': o.data.get('arguments') or {}}]}
            elif isinstance(o, dict):
                # In tag mode the calls arrive as text, so the text is split on the way past --
                # otherwise a `<tool_call>` block renders in the transcript as prose before the
                # final `Resp` quietly turns it into a call.
                if (t := o.get('text')): yield from (split.feed(t) if split else
                                                     [{'content': [{'type': 'text', 'text': t}]}])
                if (th := o.get('thinking')): yield {'channels': {'thought': th}}
        if split is not None: yield from split.finish()
        if comp is None: raise RuntimeError('stream ended without a final Completion')
        self._step_res = norm_completion(comp)

    def _oneshot(self, prompt, sp='', think=None, max_tokens=None):
        """Stateless one-shot completion text (no history, no tools).

        A hosted reasoning model has no `/no_think` and no chat template to reach; the lever
        is `reasoning_effort`, and the vocabulary for it is the provider's. So `think=False`
        asks for `NO_THINK_EFFORT` and, if the API refuses the word, asks again without it --
        one wasted round trip on a provider that spells it differently, rather than a cheap
        job that fails outright on a model whose only fault is being hosted.
        """
        msgs = [{'role': 'user', 'content': prompt}]
        kw = {**self._kw(max_output_tokens=max_tokens), 'system': sp or None, 'tools': None, 'tool_choice': None}
        if think is not None: kw['reasoning_effort'] = NO_THINK_EFFORT if think is False else self.reasoning_effort
        send = lambda k: resp_text(norm_completion(run_coro(acomplete([to_msg(m) for m in msgs], self.model_id, **k))))
        try: return send(kw)
        except Exception:
            if think is None: raise
            return send({**kw, 'reasoning_effort': self.reasoning_effort})

    def _structured_call(self, prompt, schema, sp):
        "Force the tool call for `schema` and return its arguments; falls back to parsing JSON from prose."
        spec = mk_toolspec(schema)
        name = spec['function']['name']
        kw = {**self._kw(), 'system': sp or None, 'tools': [spec], 'tool_choice': name}
        comp = run_coro(acomplete([to_msg({'role': 'user', 'content': prompt})], self.model_id, **kw))
        r = norm_completion(comp)
        if tcs := r.get('tool_calls'): return tcs[0].arguments
        txt = resp_text(r)
        try: return json.loads(extract_fence(txt, 'json'))
        except (json.JSONDecodeError, TypeError):
            raise ValueError(f"model neither called the tool nor returned JSON; reply: {txt[:200]!r}")

    def close(self):
        "Nothing to release - the HTTP client is fastllm's, and cached across chats."
        pass
