"""Hosted models through [fastllm](https://github.com/AnswerDotAI/fastllm). The same `Chat` API, with API keys in the environment (`ANTHROPIC_API_KEY`, `OPENAI_API_KEY`, `GEMINI_API_KEY`, ...).

Docs: https://vedicreader.github.io/rishi/remote.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_remote.ipynb.

# %% auto #0
__all__ = ['NO_THINK_EFFORT', 'dflt_remote', 'DFLT_MAX_TOKENS', 'STREAM_ONLY', 'to_msg', 'to_hist', 'norm_usage', 'gen_media',
           'norm_completion', 'RemoteChat']

# %% ../nbs/04_remote.ipynb #rm_imports
import json
from base64 import b64decode
from fastllm.acomplete import acomplete, split_vendor
from fastllm.types import Completion
from aidialog.msg_parts import (Msg, Part, PartType, Text, Thinking, ToolUse, ToolResult,
                                InputImage, InputAudio, data_url)
from fastcore.all import store_attr, ifnone, listify
import rishi.core
from urai import (Chat, ChatOpts, Resp, SlidingWindowCallback, StreamSplit, ToolCall, ToolLoopMixin, ToolReminderCallback,
                  UsageCallback, UsageStats, display_stream, extract_fence, mk_content, mk_msg, mk_msgs, mk_toolspec, parse_tool_tags, resp_text, run_coro, split_runtime,
                  sum_usage, sync_iter, thought, tag_tools_sp, to_media_part)

# %% ../nbs/04_remote.ipynb #httpx2fix
def _client_httpx():
    "The httpx the OpenAPI client itself imported: fastspec is on httpx2 in some installs, httpx in others."
    import fastspec.oapi as o
    return getattr(o, 'httpx2', None) or getattr(o, 'httpx', None)

def _fix_client_timeout():
    "fastllm builds `mk_client`'s default timeout with its own httpx, which need not be the client's."
    import fastllm.acomplete as fa
    mod = _client_httpx()
    if mod is None: return
    f = getattr(fa.mk_client, '__wrapped__', fa.mk_client)
    def swap(x):
        if isinstance(x, mod.Timeout) or not all(hasattr(x, k) for k in ('connect','read','write','pool')): return x
        return mod.Timeout(connect=x.connect, read=x.read, write=x.write, pool=x.pool)
    f.__defaults__ = tuple(swap(x) for x in (f.__defaults__ or ()))
    cache = getattr(fa.mk_client, 'cache', None)
    if cache is not None:
        try: cache.clear()
        except Exception: pass

_fix_client_timeout()

# %% ../nbs/04_remote.ipynb #rm_msgs
def _parts(content):
    "Canonical rishi content (str or list of parts) -> aidialog `Part`s."
    if content is None: return []
    if isinstance(content, str): return [Text(text=content)] if content else []   # no empty part on a tool-call turn
    out = []
    for p in content:
        if not isinstance(p, dict): continue
        t = p.get('type')
        if   t == 'text' and (text := p.get('text', '')): out.append(Text(text=text))
        elif t in ('image_url','input_audio') and (media := to_media_part(p)): out.append(media)
    return out

def to_msg(m):
    "One canonical rishi history dict -> a fastllm `Msg`."
    role = m.get('role', 'user')
    if role == 'tool':
        return Msg(role='tool', content=[ToolResult(id=m.get('tool_call_id'), name=m.get('name', ''),
                                                   text=str(m.get('content', '')))])
    parts = []
    if role == 'assistant' and (th := (m.get('channels') or {}).get('thought')):
        parts.append(Thinking(text=th))
    parts += _parts(m.get('content'))
    for tc in (m.get('tool_calls') or []):
        fn = tc.get('function') or {}
        parts.append(ToolUse(id=tc.get('id'), name=fn.get('name', ''), arguments=fn.get('arguments') or {},
                             server=bool(tc.get('server'))))
    return Msg(role=role, content=parts)

def to_hist(m):
    "A fastllm `Msg` -> canonical rishi history dicts (a tool `Msg` can hold several results)."
    if m.role == 'tool':
        return [{'role': 'tool', 'tool_call_id': p.id, 'name': p.name or '', 'content': str(p.text)}
                for p in m.content if p.type == PartType.tool_result]
    text = ''.join(p.text or '' for p in m.content if p.type in (PartType.text, PartType.refusal))
    th   = ''.join(p.text or '' for p in m.content if p.type == PartType.thinking)
    media = [p for p in m.content if p.type in (PartType.input_image, PartType.input_audio)]
    out = {'role': m.role, 'content': text}
    if media:
        parts = ([{'type': 'text', 'text': text}] if text else []) + [_media_part(p) for p in media]
        out['content'] = parts
    if th: out['channels'] = {'thought': th}
    tcs = [ToolCall(name=p.name or '', arguments=p.arguments or {}, id=p.id, server=bool(p.server))
           for p in m.content if p.type == PartType.tool_use]
    if tcs: out['tool_calls'] = tcs
    return [out]

def _media_part(p):
    "An aidialog media `Part` -> an OpenAI-style content part."
    if p.type == PartType.input_image: return {'type': 'image_url', 'image_url': {'url': p.text}}
    mime, b64 = data_url(p.text) or ('audio/wav', '')
    return {'type': 'input_audio', 'input_audio': {'data': b64, 'format': mime.split('/')[-1]}}

# %% ../nbs/04_remote.ipynb #rm_resp
def norm_usage(u, model=None):
    "fastllm `Usage` -> a rishi usage dict, including the reasoning and cache-write counts providers bill for."
    if u is None: return {}
    out = {'prompt_tokens': u.prompt_tokens, 'completion_tokens': u.completion_tokens,
           'total_tokens': u.total_tokens or (u.prompt_tokens + u.completion_tokens),
           'cached_tokens': u.cached_tokens, 'model': model}
    for k in ('reasoning_tokens', 'cache_creation_tokens'):
        if (v := getattr(u, k, 0)): out[k] = v
    return out

#: Keys a provider hides a generated image behind, and the mime key beside it.
_inline_keys = (('inlineData', 'mimeType'), ('inline_data', 'mime_type'))

def _d(o):
    "`o` as a plain dict, whether it arrived as one or as a provider's response object."
    if isinstance(o, dict): return o
    for a in ('model_dump', 'dict', 'to_dict'):
        if callable(f := getattr(o, a, None)):
            try: return f()
            except Exception: pass
    return getattr(o, '__dict__', {}) or {}

def _media_from(o):
    "Generated media in one raw response node, as `(mime, bytes)` pairs."
    d, out = _d(o), []
    for k, mk in _inline_keys:
        if (inl := d.get(k)):
            inl = _d(inl)
            if inl.get('data'): out.append((inl.get(mk) or 'image/png', b64decode(inl['data'])))
    u = _d(d.get('image_url') or {}).get('url') or (d.get('image_url') if isinstance(d.get('image_url'), str) else None)
    if u and (du := data_url(u)): out.append((du[0], b64decode(du[1])))
    for k in ('result', 'b64_json'):
        if isinstance(d.get(k), str) and d[k]: out.append(('image/png', b64decode(d[k])))
    return out

def _walk(o, depth=0):
    "Every dict-ish node in a raw response."
    if depth > 6: return
    if isinstance(o, (list, tuple)):
        for x in o: yield from _walk(x, depth+1)
        return
    d = _d(o)
    if not d: return
    yield d
    for v in d.values():
        if isinstance(v, (dict, list, tuple)) or hasattr(v, '__dict__'): yield from _walk(v, depth+1)

def gen_media(raw):
    "Images a model generated, dug out of `Completion.raw`. fastllm's `PartType` is input-only."
    if raw is None: return []
    seen, out = set(), []
    for node in _walk(raw):
        for mime, data in _media_from(node):
            if (h := hash(data)) not in seen:
                seen.add(h); out.append({'mime': mime, 'data': data})
    return out

def norm_completion(comp):
    "fastllm `Completion` -> rishi `Resp`, reading `<tool_call>` tags out of the text as `core.norm_resp` does."
    res = to_hist(comp.message)[0]
    res.setdefault('role', 'assistant')
    tag_tcs = []
    if isinstance(res.get('content'), str): res['content'], tag_tcs = parse_tool_tags(res['content'])
    tcs = [ToolCall(name=tc.name, arguments=tc.arguments, id=tc.id, server=tc.server) for tc in (comp.tool_calls or [])]
    tcs += [ToolCall(name=tc['function']['name'], arguments=tc['function']['arguments'], id=tc['id']) for tc in tag_tcs]
    if tcs: res['tool_calls'] = tcs
    if comp.finish_reason == 'length': res['truncated'] = True
    res['usage'] = norm_usage(comp.usage, comp.model)
    # off `content`, so everything that walks response text is unchanged
    if (media := gen_media(getattr(comp, 'raw', None))): res['media'] = media
    return Resp(res)

# %% ../nbs/04_remote.ipynb #rm_chat
#: What `think=False` asks a hosted model for. A name, not a literal, so a deployment whose
#: provider spells the lowest reasoning effort differently can say so.
NO_THINK_EFFORT = 'minimal'
dflt_remote = 'gpt-5.1'      #: model for a `RemoteChat` with none named
DFLT_MAX_TOKENS = 4096
#: Vendors whose transport answers a streamed request and refuses every other one.
STREAM_ONLY = {'codex'}

class RemoteChat(ToolLoopMixin, Chat):
    "Chat against a hosted model through fastllm, with the same `Chat` API as the local backends."
    _runtime = 'remote'
    _dflt_cbs = [UsageCallback, ToolReminderCallback, SlidingWindowCallback]
    #: what this transport calls each portable option
    _opt_map = {'ctx': 'ctx_limit', 'temp': 'temperature', 'effort': 'reasoning_effort',
                'max_output_tokens': 'max_tokens'}
    _opt_skip = ('top_k', 'top_p', 'seed', 'think')   # no hosted API takes these
    mk_content, mk_msg, mk_msgs = staticmethod(mk_content), staticmethod(mk_msg), staticmethod(mk_msgs)

    @staticmethod
    def fmt2hist(msgs):
        "fastllm `Msg`s (or canonical dicts) -> canonical history dicts."
        out = []
        for m in listify(msgs): out += to_hist(m) if isinstance(m, Msg) else [mk_msg(m)]
        return out

    @staticmethod
    def hist2fmt(msgs):
        "Canonical history dicts -> fastllm `Msg`s, media carried through rather than stripped."
        return [to_msg(m) for m in listify(msgs) if m.get('role') != 'system']

    def __init__(self, model=None, *, runtime=None, model_path=None, opts=None,
                 vendor_name=None,   # override the vendor fastllm infers from the model id
                 api_name=None,      # ...and the api name
                 tool_choice=None,   # force a particular tool, or 'required'
                 retries=2,
                 comp_kw=None,       # passed to `acomplete` verbatim
                 **kw):              # portable options; see `urai.ChatOpts`
        o = ChatOpts.create(opts, **kw)
        self.model_id = split_runtime(model)[1] or dflt_remote
        self.tool_mode = o.tool_mode or 'native'
        self.api_key, self.base_url = o.key, o.base_url or None
        self.reasoning_effort, self.temp = o.effort or None, o.temp
        self.max_output_tokens = o.max_output_tokens or DFLT_MAX_TOKENS
        self.ctx_limit = o.ctx or None
        store_attr('vendor_name,api_name,tool_choice,retries', self)
        self.comp_kw, self._ctx_tokens = comp_kw or {}, 0
        self._set_tools(o.tools)
        self._setup(model, o)

    @property
    def token_count(self):
        "Tokens the last turn reported. Hosted APIs have no live context read-out."
        return self._ctx_tokens

    def _kw(self, stream=False, **turn):
        "Keyword arguments for `acomplete`, with this turn's own generation options applied."
        t = self.map_opts(turn)
        kw = dict(stream=stream, api_key=self.api_key, base_url=self.base_url, retries=self.retries,
                  vendor_name=self.vendor_name, api_name=self.api_name,
                  max_tokens=t.pop('max_tokens', None) or self.max_output_tokens)
        tags = t.pop('tool_mode', self.tool_mode) == 'tags'
        sp = tag_tools_sp(self.toolspecs, self.sp) if tags else self.sp
        if sp: kw['system'] = sp
        # in tag mode the schemas already went out in the system prompt, and sending them on the
        # wire as well is the one thing the transport cannot do
        if self.toolspecs and not tags: kw['tools'] = self.toolspecs
        if self.tool_choice is not None and not tags: kw['tool_choice'] = self.tool_choice
        if (eff := t.pop('reasoning_effort', self.reasoning_effort)) is not None: kw['reasoning_effort'] = eff
        if (tmp := t.pop('temperature', self.temp)) is not None: kw['temperature'] = tmp
        t.pop('ctx_limit', None)                       # a window is not a completion argument
        return {**kw, **self.comp_kw, **t}

    async def _acomplete(self, msgs, stream=False, **turn):
        "One `acomplete` call for `msgs` (canonical history dicts)."
        return await acomplete(self.hist2fmt(msgs), self.model_id, **self._kw(stream, **turn))

    @property
    def _stream_only(self):
        "Whether this model's vendor will not answer a request that is not streamed."
        return (self.vendor_name or split_vendor(self.model_id)[0]) in STREAM_ONLY

    async def _collect(self, msgs, **kw):
        "One `Completion`, gathered from a stream."
        agen = await acomplete(msgs, self.model_id, **{**kw, 'stream': True})
        comp = None
        async for part in agen:
            if isinstance(part, Completion): comp = part
        if comp is None: raise RuntimeError('stream ended without a final Completion')
        return comp

    async def _one(self, msgs, **kw):
        "One `Completion`, streamed and gathered where the vendor takes nothing else."
        if self._stream_only: return await self._collect(msgs, **kw)
        return await acomplete(msgs, self.model_id, **kw)

    def _model_step(self, **kw):
        "One completion, normalized to a `Resp`. The wire call `ToolLoopMixin` drives."
        return norm_completion(run_coro(self._one(self.hist2fmt(self.hist), **self._kw(**kw))))

    def _stream_step(self, **kw):
        "Stream one completion, yielding chunk dicts and leaving the merged `Resp` on `self._step_res`."
        async def _agen():
            agen = await self._acomplete(self.hist, True, **kw)
            async for o in agen: yield o
        comp, split = None, StreamSplit() if self.tool_mode == 'tags' else None
        for o in sync_iter(_agen, stop=self._cancel):
            if isinstance(o, Completion): comp = o
            elif not isinstance(o, Part): continue          # a `Status` marker, not model content
            elif o.type == PartType.tool_use:
                yield {'content': [{'type': 'tool_call', 'name': o.name or '',
                                    'arguments': o.arguments or {}}]}
            elif o.type == PartType.thinking: yield {'channels': {'thought': o.text or ''}}
            elif o.type in (PartType.text, PartType.refusal) and (t := o.text):
                # in tag mode the calls arrive as text, so split it on the way past: otherwise the
                # `<tool_call>` block renders as prose before the final `Resp` turns it into a call
                yield from (split.feed(t) if split else [{'content': [{'type': 'text', 'text': t}]}])
        if split is not None: yield from split.finish()
        if comp is None: raise RuntimeError('stream ended without a final Completion')
        self._step_res = norm_completion(comp)

    def _oneshot(self, prompt, sp='', think=None, max_tokens=None):
        "Stateless completion text, with no history and no tools. `think=False` asks for `NO_THINK_EFFORT`."
        msgs = [to_msg({'role': 'user', 'content': prompt})]
        kw = {**self._kw(max_output_tokens=max_tokens), 'system': sp or None,
              'tools': None, 'tool_choice': None}
        send = lambda k: resp_text(norm_completion(run_coro(self._collect(msgs, **k))))
        if think is not False: return send(kw)
        try: return send({**kw, 'reasoning_effort': NO_THINK_EFFORT})
        except Exception: return send(kw)   # a provider that spells the effort differently

    def _structured_call(self, prompt, schema, sp):
        "Force the tool call for `schema` and return its arguments, falling back to JSON found in prose."
        spec = mk_toolspec(schema)
        name = spec['function']['name']
        kw = {**self._kw(), 'system': sp or None, 'tools': [spec], 'tool_choice': name}
        comp = run_coro(self._one([to_msg({'role': 'user', 'content': prompt})], **kw))
        r = norm_completion(comp)
        if tcs := r.get('tool_calls'): return tcs[0].arguments
        txt = resp_text(r)
        try: return json.loads(extract_fence(txt, 'json'))
        except (json.JSONDecodeError, TypeError):
            raise ValueError(f'model neither called the tool nor returned JSON; reply: {txt[:200]!r}')

    def close(self):
        "Nothing to release. The HTTP client is fastllm's, and cached across chats."
        pass

